### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by soumyadip007** [stanfordnlp/CoreNLP#1005]
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at edu.stanford.nlp.parser.nndep.Classifier.preCompute(Classifier.java:662)
	at edu.stanford.nlp.parser.nndep.Classifier.preCompute(Classifier.java:644)
	at edu.stanford.nlp.parser.nndep.DependencyParser.initialize(DependencyParser.java:1189)
	at edu.stanford.nlp.parser.nndep.DependencyParser.loadModelFile(DependencyParser.java:630)
	at edu.stanford.nlp.parser.nndep.DependencyParser.loadFromModelFile(DependencyParser.java:499)
	at edu.stanford.nlp.pipeline.DependencyParseAnnotator.<init>(DependencyParseAnnotator.java:57)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.dependencies(AnnotatorImplementations.java:240)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$18(StanfordCoreNLP.java:536)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$29/240650537.apply(Unknown Source)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$null$30(StanfordCoreNLP.java:602)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$38/2054798982.get(Unknown Source)
	at edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:126)
	at edu.stanford.nlp.util.Lazy.get(Lazy.java:31)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:149)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:251)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:192)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:188)
	at com.java.nlp.main.Pipeline.getPipeline(Pipeline.java:23)
	at com.java.nlp.Tokenize.main(Tokenize.java:15)

**Comment by AngledLuffa** [comment]
Run it with more memory?

**Comment by soumyadip007** [comment]
Yes
with -Xms2048M

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1747)
	at java.util.HashMap.putVal(HashMap.java:631)
	at java.util.HashMap.put(HashMap.java:612)
	at edu.stanford.nlp.ling.tokensregex.Env.bind(Env.java:313)
	at edu.stanford.nlp.ling.tokensregex.Env.initDefaultBindings(Env.java:150)
	at edu.stanford.nlp.ling.tokensregex.TokenSequencePattern.getNewEnv(TokenSequencePattern.java:159)
	at edu.stanford.nlp.pipeline.TokensRegexNERAnnotator.createPatternMatcher(TokensRegexNERAnnotator.java:365)
	at edu.stanford.nlp.pipeline.TokensRegexNERAnnotator.<init>(TokensRegexNERAnnotator.java:317)
	at edu.stanford.nlp.pipeline.NERCombinerAnnotator.setUpFineGrainedNER(NERCombinerAnnotator.java:220)
	at edu.stanford.nlp.pipeline.NERCombinerAnnotator.<init>(NERCombinerAnnotator.java:145)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.ner(AnnotatorImplementations.java:68)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$5(StanfordCoreNLP.java:523)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$16/747464370.apply(Unknown Source)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$null$30(StanfordCoreNLP.java:602)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$38/2054798982.get(Unknown Source)
	at edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:126)
	at edu.stanford.nlp.util.Lazy.get(Lazy.java:31)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:149)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:251)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:192)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:188)
	at com.java.nlp.main.Pipeline.getPipeline(Pipeline.java:23)
	at com.java.nlp.Tokenize.main(Tokenize.java:15)
