### ISSUE TITLE
NERCombinerAnnotator NullPointerException 

### ISSUE THREAD

**Issue by kay-wong** [stanfordnlp/CoreNLP#1037]
Command used:
```
/usr/bin/java -mx150g -cp "stanford-corenlp/*" edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse -ssplit.eolonly -tokenize.whitespace true -file infile -outputFormat xml -outputDirectory outdir
```
Error:
```
Exception in thread "main" java.lang.NullPointerException
	at edu.stanford.nlp.pipeline.NERCombinerAnnotator.annotate(NERCombinerAnnotator.java:322)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:637)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:647)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1226)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1060)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.run(StanfordCoreNLP.java:1326)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1389)
```

I obtained a NullPointerException when running the above command. The pipeline works fine up till the NER annotator is added. I was able to isolate the issue for the `ssplit.eolonly` property to the fact that the unsuccessfully parsed files had CRLF line endings. This may be similar to the issue in #966 where the delimiter regex for the ArabicSegmenterAnnotator mishandled `\r\n`. 

Changing the encoding for the line endings resulted in the pipeline running successfully when using only the `-ssplit.eolonly` property. However I still obtain a NullPointerException with the `-tokenize.whitespace` property on NERCombinerAnnotator. 

I have a feeling it's something of the same issue; with the NER annotator in handling the tokenize.whitespace property when performing NER-specific tokenisation. Any help on this would be appreciated.

**Comment by AngledLuffa** [comment]
If you upgrade to 4.0.0, this is hopefully already fixed.

Please remember to include the version number when posting bug reports.

**Comment by J38** [comment]
I ran this command with Stanford CoreNLP 4.0.0 

```
java -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner -tokenize.whitespace -ssplit.eolonly -file example.txt
```

and it worked fine. I fixed this issue a while back. There is also a test for it now:

```
edu.stanford.nlp.pipeline.PreTokenizedSentenceSplitITest
```
