### ISSUE TITLE
java.lang.ClassNotFoundException: edu.stanford.nlp.tagger.maxent.ExtractorNonAlphanumeric for Part of Speech Tagger

### ISSUE THREAD

**Issue by JustCunn** [stanfordnlp/CoreNLP#1070]
Hi,

I am trying to parse an English text file (around 800k sentences large) with the POS tagger. The file `stanford-postagger.sh` is set up like so:

```
#!/bin/sh

java -mx1000m -cp stanford-postagger.jar edu.stanford.nlp.tagger.maxent.MaxentTagger -model $1 -textFile $2
```

And this is the command I use in the Linux/Ubuntu terminal:

```
./stanford-postagger.sh models/english-left3words-distsim.tagger train/train.dtk.en > train/train.localtag.en
```

Here is the full error:

```
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Error while loading a tagger model (probably missing model file)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:937)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:825)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:799)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:322)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:305)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.runTagger(MaxentTagger.java:1564)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.main(MaxentTagger.java:1908)
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.tagger.maxent.ExtractorNonAlphanumeric
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:720)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1925)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2099)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1625)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2032)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2344)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2268)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2126)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1625)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:465)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:423)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readExtractors(MaxentTagger.java:630)
	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:876)
	... 6 more
```
I checked the `CLASSPATH` and tried it both as it's written when you download the tagger and without the quotation marks (like above). I am not to familiar with Java so troubleshooting is proving very difficult for me. Any help would be appreciated.

**Comment by AngledLuffa** [comment]
Yeah, this is a known issue.  We're preparing a new release which fixes
this and other bugs.  In the meantime, you can try one of these:

http://nlp.stanford.edu/software/stanford-postagger-full-2020-07-09.zip

http://nlp.stanford.edu/software/stanford-corenlp-full-2020-07-09.zip

**Comment by JustCunn** [comment]
Oh, sorry, I probably should've checked first to see if this was an issue raised before. Thanks for clarifying though, I'll make sure to check those out.
