### ISSUE TITLE
Using newly trained model of clarkkev/deep-coref in Stanford neural coref system

### ISSUE THREAD

**Issue by cruncher64** [stanfordnlp/CoreNLP#1086]
Hi,
I am working with the neural system of Stanford coreNLP and want to train a new extended model. To do so, one has to use Kevin Clark's python software deep-coref as instructed from the coreNLP online docs, but this one is saving model weights in hdf5 format. It is obvious, that this is not usable by the coreNLP software (which uses the serialized java object of e.s.n.c.n.NeuralCorefModel in the file english-model-conll.ser). So my guess is that the outcome of deep-coref is not usable by Stanford neural coref directly or am I missing something? 
Or in other words, how was english-model-conll.ser trained?

Dirk

**Comment by AngledLuffa** [comment]
We have a script that converts them... just a matter of finding where it
went all these years ago.  We'll let you know when we find it.

**Comment by cruncher64** [comment]
Thank you very much John for your effort and have a nice weekend.

Dirk

Von: John Bauer <notifications@github.com>
Gesendet: Freitag, 25. September 2020 16:53
An: stanfordnlp/CoreNLP <CoreNLP@noreply.github.com>
Cc: Mühlenberg, Dirk <dirk.muehlenberg@iosb.fraunhofer.de>; Author <author@noreply.github.com>
Betreff: Re: [stanfordnlp/CoreNLP] Using newly trained model of clarkkev/deep-coref in Stanford neural coref system (#1086)

We have a script that converts them... just a matter of finding where it
went all these years ago. We'll let you know when we find it.

**Comment by AngledLuffa** [comment]
There's a piece which should convert the output of the training from hdf5 to text, and another piece which converts that text to a java serialized model.  Are you able to share the model with us?  If so, I can spend some time making sure the conversion script is working.

If by any chance you're working on a German model, we'd also be happy to try integrating it.

**Comment by cruncher64** [comment]
Yes I can share the weight files, but which one is correct, there are several directories containing hdf5 called final_weights, they are all_pairs, top_pairs or reward_rescaling in data/models directory. Each is 32MB in size, so how to share (github only allows 25MB)?
I am sorry to say, that it is an English model trained from a relatively small coref dataset to see if all works well. Our intention is to merge additional coref data to CoNLL-2012, to see, if we get a quality gaiin.

**Comment by wajdalahmad** [comment]
I am still unable to activate the setup feature of Stanford corenlp. I
installed Java and python, what should I do next?

**Comment by AngledLuffa** [comment]
I actually don't know which of those is more applicable.  However, in terms of testing the conversion, it hopefully doesn't matter much.  Alternatively you can just send them all and I'll figure it out on this end.

I've had good luck transferring large chunks of data using

https://wetransfer.com/

Can you see my email address?  You need it for wetransfer

**Comment by AngledLuffa** [comment]
@wajdalahmad that seems completely unrelated.  Would you open a new issue on the appropriate repo?

**Comment by AngledLuffa** [comment]
PS you'll also need to zip up the options file with the rest, I believe...
but I'm not 100% sure of that.  If it isn't obvious which file I'm talking
about, then forget it

**Comment by cruncher64** [comment]
I have just sent you the hdf5 files via wetransfer to your email addess.

**Comment by AngledLuffa** [comment]
Are you using python2 or python3, btw?

**Comment by cruncher64** [comment]
It is python3

Mit SecurePIM gesendet

Am 28.09.20 17:44, John Bauer <notifications@github.com> schrieb:


Are you using python2 or python3, btw?

**Comment by AngledLuffa** [comment]
That's a little surprising to me because all of the print statements are in
python2 style.  Did you edit those yourself first?

**Comment by AngledLuffa** [comment]
Also, were there any pickle files that could be sent along?  For example,
the conversion script I'm trying to use is looking for

./data/features/mention_data/vocabulary.pkl

**Comment by cruncher64** [comment]
I have converted the source code from 2 to 3, as I only have python3 environment. There were some non trivial parts like integer division or lambdas.
Also the versions of the dependencies are nowhere declared (or I wasn't able to find that), but now it runs.
I have packed all pickles in the attachment.
[pickles.zip](https://github.com/stanfordnlp/CoreNLP/files/5296800/pickles.zip)

**Comment by AngledLuffa** [comment]
Thank you!

Are the code changes something you could send as a pull request?  That
sounds quite useful.  I have gotten as far as updating the print statements
and the pickle imports, but I hadn't looked at division yet and lambdas
didn't even occur to me.

**Comment by AngledLuffa** [comment]
Converting a model is a two step process which I haven't gotten to work yet
because of some apparent changes from python2 to python3.

First you dump the matrices using this:

https://github.com/AngledLuffa/deep-coref/blob/python3/export.py

Then you convert them to a serialized file using this:

https://github.com/stanfordnlp/CoreNLP/blob/1371bbe68ce38f095981d1452e10d7b9427b8f7d/src/edu/stanford/nlp/coref/neural/ModelSerializer.java

I'll keep working on it too.  I'll let you know if I figure it out

**Comment by cruncher64** [comment]
Thank you. No problem, to share the code, but I am not familiar with pull request, so I have simply packed the deep-coref directory and attached that. I hope this will work for you. 
The dependencies are: Theano 0.8, numpy 1.19.1, h5py 2.6.0
[deep-coref.zip](https://github.com/stanfordnlp/CoreNLP/files/5296988/deep-coref.zip)
 and scikit-learn 0.22.2 for the out-dated keras 0.2. Also I did not manage to get it run in a gpu docker environment, as the keras is too old and complains about current nvidia driver.

**Comment by AngledLuffa** [comment]
Ah, maybe that's the problem with the pickle.  I figured out that I needed
to install an older theano, but my h5py is not several years out of date.
Maybe you'll have better luck using the export script than I've had so far

Thanks for sharing!

**Comment by cruncher64** [comment]
I have managed to export the files after changing some lines in export.py (I had to zip it :) ).
[export.zip](https://github.com/stanfordnlp/CoreNLP/files/5297289/export.zip)

**Comment by cruncher64** [comment]
Well with the ModelSerializer I had not so much luck, it is throwing an
Exception in thread "main" java.lang.RuntimeException: Unexpected row length in line 675
	at edu.stanford.nlp.neural.NeuralUtils.convertTextMatrix(NeuralUtils.java:80)
	at edu.stanford.nlp.neural.NeuralUtils.loadTextMatrices(NeuralUtils.java:63)
	at edu.stanford.nlp.coref.neural.ModelSerializer.main(ModelSerializer.java:21)
I am now stuck there, as line 675 in anaphoricity_weights has a item count of only 500, while it should be 1000.

**Comment by AngledLuffa** [comment]
I can't quite get that far - it seems I may need to ask you for .npy files
from your data directory as well.  I believe those were created during
training rather than as a byproduct of the export script.

One horrifying thought which just occurred to me is, what if the
"modified_keras" package also would need to be changed for python3?  It
wouldn't surprise me to learn that there's a bunch of integer division
which needs to be updated.  At least there is a "from future import
division" in keras/layers/core.py, though.

Anyway, it seems you are mostly doing my job for me.  Thanks for all the
help!

**Comment by cruncher64** [comment]
Here are the numpies 
[numpies.zip](https://github.com/stanfordnlp/CoreNLP/files/5303467/numpies.zip)

It was no problem with Keras 0.2, as the readme states compatibility with python 2.7 - 3.4 and the training went through (with low quality as it was a small dataset).

You are welcome, John. I have to thank you. Without your help I would have been stuck at a critical point. It is no problem at all as it is also very important for me to get the whole training workflow running and gather experience with extended or new models and so in the end I think it is a benefit for both of us.

**Comment by AngledLuffa** [comment]
I'm not getting an error when I run the conversion, but I do get an error further downstream when I try to run it in corenlp.  I'll try to figure that out next.  I made a few updates to the serializer to accept command line arguments which describe the paths.

https://github.com/stanfordnlp/CoreNLP/blob/dev/src/edu/stanford/nlp/coref/neural/ModelSerializer.java

**Comment by AngledLuffa** [comment]
As near as I can tell, there is a discrepancy in the features produced by the python and the java code.  In python, the features becomes a 674 dimension vector, whereas in java it becomes a 668 dimension vector.  This discrepancy is what is preventing the model from running for me when I convert it from python to java.

I asked the original author if he can point out any known differences in the features, since that would save us quite a bit of time debugging that.  Otherwise, as soon as I can figure out how to reconcile the two, I'll let you know.  If any of the matrix sets that were saved happen to have 668 instead of 674 rows, that would also work (but I highly doubt that will be the case).

**Comment by AngledLuffa** [comment]
Also, random observation - did you notice it running on GPU, or did you see any flags etc which would put it on the GPU?  My nvidia-smi shows my GPU at a nice even room temperature

**Comment by cruncher64** [comment]
I am sorry, but I did not manage to get it run in a gpu docker environment, as the keras is too old and complained about low quality of the current nvidia driver version 455.23.05 (no joke). I remember the configuration to instruct keras/theano to use the GPU was to drop a .theanorc file in the home with this content:
[global]
floatX = float32
device = cuda0

[gpuarray]
preallocate = 1

But if it runs on CPU while training, it is using all the cores it can get and the gpus are idling. My CPU has 24 cores, so it was a matter of one week to train the standard conll-2012 set.
Meanwhile I have found out that for the anaphoricity model, both 1000 and 500 size is intended (see the end of model_properties.py). But NeuralUtils.convertTextMatrix was complaining about that.

**Comment by AngledLuffa** [comment]
To train the models with 668 dimensions instead of 674, there's a couple
lines I changed in model_properties.py of deep-coref:

-        self.use_genre = use_genre
+        self.use_genre = False

-        self.single_size = 855 if directories.CHINESE else 674
+        self.single_size = 855 if directories.CHINESE else 668

I suppose that should be made into an option, but for now I just hardcoded
it.

I adjusted the java half of the conversion script to accept various command
line options for the paths used when converting.
For example, if I have the data in the subdirectory

data/models/all_pairs/exported_weights

I can then run

java edu.stanford.nlp.coref.neural.ModelSerializer -language "" -name ""
-path data/models/all_pairs/exported_weights

I am not experiencing any errors in the conversion, but if you are, please
send me as many details as you can and I will investigate.

I can then use the neural coref as follows.  Note that it needs the parse
annotator, which is currently not part of the default annotators:

java edu.stanford.nlp.pipeline.StanfordCoreNLP -coref.algorithm neural
-annotators "tokenize,ssplit,pos,lemma,ner,depparse,parse,coref"
-coref.neural.modelPath data/models/all_pairs/exported_weights/model.ser.gz
-coref.neural.embeddingsPath
data/models/all_pairs/exported_weights/embeddings.ser.gz

**Comment by cruncher64** [comment]
I am experiencing no more issues, thank you very much John for the great support. From my side we could close this issue.

**Comment by AngledLuffa** [comment]
Just a small heads up, with the next version we're upgrading ejml from 0.38
to 0.39.  This breaks the serialization of existing coref models...

Internally we used a tool to first convert all SimpleMatrix objects to
List<List<Double>>, then to convert back to SimpleMatrix with the ejml
upgrade.  If you want to preserve any models you've already trained, you
could use that tool:

checkout out the corenlp repo at hash
09838b70108abe0d27b12b90eec0902f88dbcd36
look for the edu.stanford.nlp.neural.ConvertModels tool.  You use it once
with the old version of ejml (appropriately, with the flag -stage OLD) and
then use it with the new version of ejml on the output of the first process.

We'll include that in the next release, why not.

Alternatively, when the new version comes out, you can also
just reserialized the python output to a new java version or retrain the
whole thing.  Up to you

**Comment by cruncher64** [comment]
We experience very low numbers in F1 for CoNLL of around 40%. I found out, that we missed constituent parse information in our data, and that is definitely needed for training (exported to dep_relation feature). So my question is, if it is possible, that the degredation in score is based on the missing parse info or should I look for another reason?

**Comment by AngledLuffa** [comment]
My understanding is it relies on the constituency parses for features, so
this will indeed cause problems.  Can't promise it will fix everything,
though...

**Comment by cruncher64** [comment]
We have included parse tree information into training data (conll-2012 files). But to no avail, results are bad. Some days ago, I stumbled over these parts of code:

class MentionRankingProps (in model_properties.py)
    def __init__(self, name=None, mode='ranking',
…
                # mention features
                 use_length=True, use_mention_type=True,  use_position=True, **use_dep_reln=False**,
…
in datasets.py:
        self.words.append(np.array([
            get_word(head_index),
            get_word(start_index),
            get_word(end_index - 1),
            get_word(start_index - 1),
            get_word(end_index),
            get_word(start_index - 2),
            get_word(end_index + 1),
            vectors[m["dep_parent"]],
            vectors["dep=" + m["dep_relation"]]
        ], dtype='int32'))
…
        if not model_props.**use_dep_reln**:
            self.words = self.words[:, :-1]

This results in the removal of the right column in the words matrix (which is the column for the dependency relations), am I correct? So this woud mean, that with this configuration, dependency relations are not included in the training run, perhaps resulting in the low 40's of CoNLL score.

**Comment by AngledLuffa** [comment]
It's worth a try.  Have you recreated the original results using the conll
coref data?  It might be worth verifying that is working, too.

**Comment by cruncher64** [comment]
No. I could not recreate the results from the publications (my results are more than 20% off the published results), although I used the original CoNLL-2012 data with parse tree information. And I used the original  python2 code, not the updated version.

**Comment by AngledLuffa** [comment]
I don't have a ton of time to devote to debugging it now, but I can
probably pick it up in a couple weeks.

Can you send me a summary of how you tried recreating the results, so I can
pass it on to the author or use it for my own reference?  The author has
been quite busy trying to graduate, though, so there's a good chance it
will take a while

**Comment by cruncher64** [comment]
Checking this morning the setup, I found out that the training was started on old data without parse tree info, the container, where the training is running, had not got the right configuration. Sorry for bothering you and stealing your time, but iI was also confused by the code snippets above.
I set up a new run this morning and the software is now consuming more time (each epoch nearly 3 times). So I think, that  I am on a good way. Nevertheless, I will double-check next time, before commenting.
