### ISSUE TITLE
NullPointer Exception Thrown when using NERClassifierCombiner to Combine RegexSequenceNERClassifier and CRFClassifier

### ISSUE THREAD

**Issue by rushabhdharia** [stanfordnlp/CoreNLP#1160]
I am using NERClassifierCombiner in CoreNLP to combine RegexNERSequenceClassifier and CRFClassifier. (The same exception was thrown when I used the ClassifierCombiner).

```
import edu.stanford.nlp.ie.ClassifierCombiner;
import edu.stanford.nlp.ie.NERClassifierCombiner;
import edu.stanford.nlp.ie.crf.CRFClassifier;
import edu.stanford.nlp.ie.regexp.RegexNERSequenceClassifier;
import edu.stanford.nlp.io.IOUtils;
import java.io.IOException;

public class Main {

    public static void main(String[] args) throws IOException, ClassNotFoundException {

        String basePath = "some_base_path";
        String filename = basePath + "input.txt";
        String inputText = IOUtils.slurpFile(filename);

        String mucClassifierPath = basePath +  "english.muc.7class.distsim.crf.ser.gz";
        String connlClassifierPath = basePath + "english.conll.4class.distsim.crf.ser.gz";

        CRFClassifier classifier_muc = CRFClassifier.getClassifier(mucClassifierPath);
        CRFClassifier classifier_connl = CRFClassifier.getClassifier(connlClassifierPath);

        String mappingPath = basePath + "regexner.rules";
        RegexNERSequenceClassifier regexNERSequenceClassifier = new RegexNERSequenceClassifier(mappingPath, true, true, null);

        NERClassifierCombiner combinedNERClassifier = new NERClassifierCombiner(false, false, classifier_connl, classifier_muc, regexNERSequenceClassifier);

        String output = combinedNERClassifer.classifyToString(inputText);
        System.out.println(output);

        return;

    }
}
```

Here is the stack trace of the exception which is thrown when the classifyToText method is called.

```
Exception in thread "main" java.lang.NullPointerException
    at edu.stanford.nlp.ie.AbstractSequenceClassifier.labels(AbstractSequenceClassifier.java:286)
    at edu.stanford.nlp.ie.ClassifierCombiner.mergeDocuments(ClassifierCombiner.java:334)
    at edu.stanford.nlp.ie.ClassifierCombiner.classify(ClassifierCombiner.java:481)
    at edu.stanford.nlp.ie.NERClassifierCombiner.classifyWithGlobalInformation(NERClassifierCombiner.java:273)
    at edu.stanford.nlp.ie.NERClassifierCombiner.classify(NERClassifierCombiner.java:268)
    at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyObjectBank(AbstractSequenceClassifier.java:481)
    at edu.stanford.nlp.ie.AbstractSequenceClassifier.classify(AbstractSequenceClassifier.java:441)
    at com.company.Main.main(Main.java:27)
```
PS: I can't use the CoreNLP Pipeline need to merge RegexNER with the existing CRFClassifiers in Production.

**Comment by AngledLuffa** [comment]
Clearly no one has ever tried to use a RegexNER as part of an
NERClassifierCombiner before, as there is a class variable which should be
filled out and isn't.

I just put out a new release last week, too :/

**Comment by AngledLuffa** [comment]
Here you go, sneak peek of the next version.  Should stop crashing -
hopefully the results are good too

http://downloads.cs.stanford.edu/nlp/software/stanford-corenlp-4.2.2.zip

**Comment by AngledLuffa** [comment]
Alright, I refreshed that link with a version which I think works in terms
of setting the annotations.  I'm not 100% sure this will be the final
version included in the next release, but for now at least you can give it
a shot

**Comment by rushabhdharia** [comment]
Thanks John, It's working now.  I'll close the issue.

Latest output for reference
```
All Classifiers
Phone/O number/O styles/O -/O +1/O(812)812-8121/PHONE_NUMBER,/O (812)912-8121/PHONE_NUMBER,/O +1 812 812 8217/O,/O +1/O(812) 912-9212/O,/O (812) 812-1012/O,/O 8128128121/PHONE_NUMBER,/O 202 555 0125/O,/O 202.555.0125/PHONE_NUMBER,/O 202-555-0125/PHONE_NUMBER./O
My/O SSN/ORGANIZATION number/O is/O 000-11-1111/SOCIAL_SECURITY_NUM./O
Email/O addresses/O -/O abz@gmail.com/EMAIL,/O xxx.yyy@outlook.com/EMAIL,/O abc.123@yahoo.com/EMAIL
1234-1234-1234-1234/CREDIT_CARD,/O 1234 1234 1234 1234/O,/O 1234123412341234/CREDIT_CARD./O
Bill/PERSON Gates/PERSON is/O the/O founder/O of/O Microsoft/ORGANIZATION./O His/O net/O worth/O is/O 60/MONEY billion/MONEY dollars/MONEY./O

```
