### ISSUE TITLE
ParserAnnotator exception if "annotators" property is not set

### ISSUE THREAD

**Issue by reckart** [stanfordnlp/CoreNLP#121]
ParserAnnotator throws an exception if "annotators" property is not set:

```
Caused by: java.lang.RuntimeException: Missing property: "annotators"
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.getRequiredProperty(StanfordCoreNLP.java:179)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.usesBinaryTrees(StanfordCoreNLP.java:426)
	at edu.stanford.nlp.pipeline.ParserAnnotator.<init>(ParserAnnotator.java:140)
```

`StanfordCoreNLP.usesBinaryTrees(Properties)` tries to detect the presence of the sentiment annotator and uses this to set the default value of `usesBinary`.

I am instantiating the `ParserAnnotator` directly, so I have no need for the `annotators` property. 

I would expect that `StanfordCoreNLP.usesBinaryTrees(Properties)` simply assumes the sentiment annotator not to be present if the `annotators` property is missing.

As a workaround, I am setting `annotators` to an empty string now when creating the `ParserAnnotator`.

**Comment by J38** [comment]
Thanks for pointing out this issue.  I have changed that function to return empty string if "annotators" is not set.
