### ISSUE TITLE
 java.io.IOException: Unable to open "edu/stanford/nlp/models/pos-tagger/english-left3words-distsim.tagger" as class path, filename or URL

### ISSUE THREAD

**Issue by jakoboo1** [stanfordnlp/CoreNLP#1309]
Hi everyone, 

I wanted to get started with the StanfordCorenlp library in Java. I added the library with the correct dependencies to the project. After that I wrote a simple program that should display the sentiment of a couple of sentences.  I made two classes: Pipeline and SentimentAnalysis

Pipeline class:
![image](https://user-images.githubusercontent.com/99398513/196154942-f2ae4a18-25a2-481a-a238-47da77f11dd0.png)

SentimentAnalysis class:
![image](https://user-images.githubusercontent.com/99398513/196155383-8d5d0b80-9d9e-4fba-8d59-72bfde436138.png)

When i run this code i get the following error.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Error while loading a tagger model (probably missing model file)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:798)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:322)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:275)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.pipeline.POSTaggerAnnotator.loadModel(POSTaggerAnnotator.java:85)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.pipeline.POSTaggerAnnotator.<init>(POSTaggerAnnotator.java:73)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.pipeline.AnnotatorImplementations.posTagger(AnnotatorImplementations.java:75)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$6(StanfordCoreNLP.java:566)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$constructAnnotatorPool$33(StanfordCoreNLP.java:647)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:126)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.util.Lazy.get(Lazy.java:31)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:149)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:278)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:194)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:190)
	at com.example.oefenenstanford/com.example.oefenenstanford.Pipeline.getPipeline(Pipeline.java:22)
	at com.example.oefenenstanford/com.example.oefenenstanford.SentimentAnlysis.main(SentimentAnlysis.java:13)
Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/pos-tagger/english-left3words-distsim.tagger" as class path, filename or URL
	at stanford.corenlp@4.4.0/edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:501)
	at stanford.corenlp@4.4.0/edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:795)
	
I have no idea what is causing this problem.

**Comment by AngledLuffa** [comment]
Probably the models file isn't in your classpath
