### ISSUE TITLE
Core NLP 3.4 with SR parser – Null pointer exception issue

### ISSUE THREAD

**Issue by vasudevdaruvuri** [stanfordnlp/CoreNLP#132]
Hi,
I am working with coreNLP 3.4 models with python wrappers specifically to mimic the project ```https://github.com/openeventdata/stanford_pipeline``` which is based on 3.4 version and  with SR parser 

I am using following jar files with JAVA 1.7 in place :
```
~/stanford_pipeline$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```
JAR files:
```
stanford-corenlp-3.4.jar
stanford-corenlp-3.4-models.jar
Stanford-srparser-2014-10-23-models.jar 
```
When parsing the sentences, it is throwing Null pointer exception at shiftreduceparser step. I tried with SRparser and beam-SRparser and played with file paths and configurations for a fair amount of time..

Please suggest me possible workaround for this issue.

```
Setting up StanfordNLP. The program isn't dead. Promise.
/home/i57167/stanford-corenlp-jars
/home/i57167
('core nlp jar paths:', ['/home/i57167/stanford-corenlp-jars/stanford-corenlp-3.4.jar', '/home/i57167/stanford-corenlp-jars/stanford-corenlp-3.4-models.jar', '/home/i57167/stanford-corenlp-jars/stanford-srparser-2014-10-23-models.jar'])
('*****************Test*************:', '/home/i57167/stanford_pipeline/src/stanford-corenlp-pywrapper-master/stanford_corenlp_pywrapper/lib')

INFO:StanfordSocketWrap:Starting pipe subprocess, and waiting for signal it's ready, with command:  exec java -Xmx4g -cp /home/i57167/stanford_pipeline/src/stanford-corenlp-pywrapper-master/stanford_corenlp_pywrapper/lib/piperunner.jar:/home/i57167/stanford_pipeline/src/stanford-corenlp-pywrapper-master/stanford_corenlp_pywrapper/lib/guava-13.0.1.jar:/home/i57167/stanford_pipeline/src/stanford-corenlp-pywrapper-master/stanford_corenlp_pywrapper/lib/jackson-all-1.9.11.jar:/home/i57167/stanford-corenlp-jars/stanford-corenlp-3.4.jar:/home/i57167/stanford-corenlp-jars/stanford-corenlp-3.4-models.jar:/home/i57167/stanford-corenlp-jars/stanford-srparser-2014-10-23-models.jar     corenlp.PipeCommandRunner --server 12340  --configfile stanford_config.ini
[Server] Using CoreNLP configuration file: stanford_config.ini
Adding annotator tokenize
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
Adding annotator ssplit

Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
done [3.6 sec].
Adding annotator lemma
Adding annotator parse
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
Loading parser from serialized file edu/stanford/nlp/models/srparser/englishSR.beam.ser.gz INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
INFO:StanfordSocketWrap:Waiting for startup: ping got exception: <class 'socket.error'> [Errno 111] Connection refused
done [32.8 sec].
[Server] Started socket server on port 12340
INFO:StanfordSocketWrap:Successful ping. The server has started.
INFO:StanfordSocketWrap:Subprocess is ready.
Stanford setup complete. Starting parse of 2042 stories...
INFO:stanford:Finished CoreNLP setup.
Processing story 56a964c7becf200b7dd9d5ab. 2016-01-28 18:03:01.842613
INFO:stanford:    Processing story 56a964c7becf200b7dd9d5ab
('Sample text:', 'This is Example Sentence. To Test Stanford NLP')
java.lang.NullPointerException
    at edu.stanford.nlp.parser.shiftreduce.ShiftReduceParserQuery.parseInternal(ShiftReduceParserQuery.java:73)
    at edu.stanford.nlp.parser.shiftreduce.ShiftReduceParserQuery.parse(ShiftReduceParserQuery.java:48)
    at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:283)
    at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:250)
    at edu.stanford.nlp.pipeline.ParserAnnotator.annotate(ParserAnnotator.java:232)
    at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:67)
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:871)
    at corenlp.Parse.processTextDocument(Parse.java:240)
    at corenlp.PipeCommandRunner.runCommand(PipeCommandRunner.java:128)
    at corenlp.PipeCommandRunner.socketServerLoop(PipeCommandRunner.java:172)
    at corenlp.PipeCommandRunner.main(PipeCommandRunner.java:96)
```

**Comment by gangeli** [comment]
Can you try to replicate this bug in the GitHub codebase, or at least in the 3.6 release? 3.4 was a while ago, and there's a chance this bug is solved by now. Also, there's not really a way for us to fix bugs retroactively in past releases...

**Comment by manning** [comment]
This has come up on our mailing lists before -- see, e.g., [this page](https://mailman.stanford.edu/pipermail/java-nlp-user/2014-October/006344.html) and the answer by the code's author, @AngledLuffa, was always that this was caused by a mismatch between the version of the parser code and the model files. This appears again to be the case here. According to [the parser page release history](http://nlp.stanford.edu/software/lex-parser.html#History), you should be using `http://nlp.stanford.edu/software/stanford-srparser-2014-06-16-models.jar` with version 3.4 of the parser/CoreNLP.
