### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by nicholas-leonard** [stanfordnlp/CoreNLP#138]
Hi,

I am trying to get the cmd-line stanford tokenizer to run. I haven't used or installed anything java related in about 10 years. How can I get this working?

So far I have tried : 
```bash
$ git clone thisrepo
$ cd CoreNLP
$ CLASSPATH=stanford-parser.jar java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file input.txt
```

I am guessing I somehow need to install something.

Thank you

**Comment by AngledLuffa** [comment]
Helps to know what platform.  Generally speaking you need to install Java 8
and include it in your path.  Whichever platform you are using should have
instructions for how to do that on the java webpage.  If you plan on doing
any development on your own, you need the java sdk, not just the java
runtime.

**Comment by nicholas-leonard** [comment]
@AngledLuffa Ubuntu 12.04 . I am looking for a quick 10 line guide to get this working. Here is the error I get for the above : 
```bash
$ CLASSPATH=stanford-parser.jar java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file input.txt
Exception in thread "main" java.lang.NoClassDefFoundError: edu/stanford/nlp/pipeline/StanfordCoreNLP
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: edu.stanford.nlp.pipeline.StanfordCoreNLP. Program will exit.
```

**Comment by sebschu** [comment]
You can find the documentation on how to run CoreNLP from the command line on this page:

  http://stanfordnlp.github.io/CoreNLP/cmdline.html

It looks like you downloaded the Stanford Parser instead of the entire CoreNLP suite and that's why Java cannot find some of the required classes.

**Comment by nicholas-leonard** [comment]
@sebschu Yeah I saw that. I cloned this entire repository so I have CoreNLP. Once I clone, what do I need to do to be able to run from command line?

**Comment by nicholas-leonard** [comment]
So I am from Lua. When I want to install a package I run : 
```bash
luarocks install package
```
I can also install it by cloning and then making : 
```bash
git clone mypackage
cd mypackage
luarocks make package.rockspec
```

So I am guessing I need to do the same thing for these java classes and such. So my question is how?

**Comment by nicholas-leonard** [comment]
Here is my java verison : 
```bash
$ java -version
java version "1.6.0_38"
OpenJDK Runtime Environment (IcedTea6 1.13.10) (6b38-1.13.10-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```

**Comment by nicholas-leonard** [comment]
I just updated to 1.8 following instructions [here](http://stackoverflow.com/questions/13716843/error-using-stanford-corenlp-in-command-line) : 
```lua
$ java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
```

I still get error : 
```
CoreNLP$ java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file input.txt
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP
```

**Comment by nicholas-leonard** [comment]
I installed maven : 
```bash
sudo apt-get install maven
```
Then I made myself a CoreNLP/pom.xml file : 
```
?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>intoxicant.analytics</groupId>
    <artifactId>coreNlpExtensions</artifactId>
    <version>1.0</version>

<dependencies>
<dependency>
    <groupId>edu.stanford.nlp</groupId>
    <artifactId>stanford-corenlp</artifactId>
    <version>3.6.0</version>
</dependency>
<dependency>
    <groupId>edu.stanford.nlp</groupId>
    <artifactId>stanford-corenlp</artifactId>
    <version>3.6.0</version>
    <classifier>models</classifier>
</dependency>
</dependencies>

</project>
```

Then I installed CoreNLP : 
```
CoreNLP$ mvn install
```

I still get error : 
```
CoreNLP$ java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file input.txt
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP
```

**Comment by nicholas-leonard** [comment]
Ok so I found [this](http://stackoverflow.com/questions/27955569/stanford-nlp-could-not-find-main-class-error). One of the comments suggested compiling with : 
```
CoreNLP$ ant
...
BUILD SUCCESSFUL
```
The above command files the `classes/` directory with files. I tried to run CoreNLP from cmd-line again : 
```
~/projects/CoreNLP$ java -cp "/home/nicholas/projects/CoreNLP/classes:/home/nicholas/.m2/repository/edu/stanford/nlp/stanford-corenlp/3.6.0/stanford-corenlp-3.6.0-models.jar" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file input.txt
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at edu.stanford.nlp.util.logging.SLF4JHandler.getLoggerAndLevel(SLF4JHandler.java:38)
	at edu.stanford.nlp.util.logging.SLF4JHandler.handle(SLF4JHandler.java:60)
	at edu.stanford.nlp.util.logging.Redwood$RecordHandlerTree.process(Redwood.java:741)
	at edu.stanford.nlp.util.logging.Redwood$RecordHandlerTree.process(Redwood.java:777)
	at edu.stanford.nlp.util.logging.Redwood$RecordHandlerTree.process(Redwood.java:777)
	at edu.stanford.nlp.util.logging.Redwood$RecordHandlerTree.access$000(Redwood.java:618)
	at edu.stanford.nlp.util.logging.Redwood.log(Redwood.java:304)
	at edu.stanford.nlp.util.logging.Redwood$RedwoodChannels.log(Redwood.java:1224)
	at edu.stanford.nlp.util.logging.Redwood$RedwoodChannels.info(Redwood.java:1276)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:393)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:141)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:137)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1257)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```
Yay another error.

**Comment by nicholas-leonard** [comment]
Got it working : 
```bash
$java -cp "/home/nicholas/projects/CoreNLP/classes" edu.stanford.nlp.process.PTBTokenizer -preserveLines sample.txt
```

Ok so anyway, maybe you guys should look into providing installation documentation that doesn't assume users are used to working with java. And my god, if this is how all java projects are installed, what hell this language must be to use! Thank you for your help.
