### ISSUE TITLE
Getting TimeoutException for longer sentences

### ISSUE THREAD

**Issue by anupamme** [stanfordnlp/CoreNLP#147]
For longer sentences e.g.

i was thrilled to discover the existence of the destiny farmstay as i felt it would serve the dual purpose of giving the group of adults we were travelling with a chance to unwind while the children would get their first exposure to life on a farm

and annotators: 'tokenize,ssplit,parse,pos,lemma'

I get 

java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:389)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Corenlp version 3.6. Running it as a server by running

java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer

**Comment by gangeli** [comment]
The particular problem here is that the parser is taking too long to parse the sentence. Try setting the `-timeout` flag when starting the server; or, alternately, set the `"timeout": xyz` JSON entry in the properties passed to the server. Either should increase the timeout to something larger.

**Comment by gangeli** [comment]
Did setting the timeout help? The likely underlying cause here is probably the `parse` annotator. On long sentences, this takes cubicly long time. Anything over 40 or 50 words begins to be noticeably slow. If you only want dependencies, I can recommend the `depparse` annotator. Otherwise, you can also try to load the shift-reduce constituency models, which scale linearly with sentence length.

**Comment by anupamme** [comment]
I tried 

1. Could not get -timeout param to work.

java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -timeout

But it throws java.lang.NumberFormatException: For input string: "true"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:730)

2. And adding timeout in properties works.

properties={'annotators': 'tokenize,ssplit,parse,pos,lemma', 'outputFormat': 'json', 'timeout': 30000}

did the trick.

3. replacing parse with depparse also works (with no need of timeout).

4. Did not try shift-reduce models.

So I can close this issue.
