### ISSUE TITLE
NullPointerException when calling the server

### ISSUE THREAD

**Issue by Izhaki** [stanfordnlp/CoreNLP#153]
So, the server fails with NullPointer exception, the console output looks as below.

## How the server was constructed

I had troubles getting the server working by building the git version, so this particular server version was patched like so (which may be the cause):

- Downloaded version 3.6.0, extract.
- Github (mainly to get sentiment working):
    - Downloaded master.
    - `ant build`
    - Copy `javanlp-core.jar` to the extracted downloaded folder.
- Extra models (to get kbp working):
    - Downloaded `http://nlp.stanford.edu/software/stanford-english-corenlp-models-current.jar`
    - Copy to the extracted downloaded folder.

corenlp.run times out on this, so I  can't confirm whether it works there.

## Console output

``
[pool-1-thread-4] INFO CoreNLP - [/127.0.0.1:64231] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner,parse,entitymentions,mention,coref,sentiment,kbp
A Conservative Welsh assembly election candidate has been criticised for "offensive" remarks made on Facebook. Cardiff Central candidate Matt Smith has been reprimanded by his party after comparing the left-wing Respect party to paedophiles. Respect said the comments - made last year when he was a council candidate in Tower Hamlets, London - were "insulting and offensive".  The Labour Anglesey candidate has also faced criticism for Facebook comments. Mr Smith, a personal injury lawyer, is also a special adviser on education policy to Nick Bourne, leader of the Conservatives in the assembly. Responding to Mr Smith's comments, Clive Searle, national secretary of Respect, said: "Matt Smith's comments are both insulting and offensive in that they trivialise paedophilia.  "Politics should be about debating the real issues affecting our society, not throwing around puerile insults.   "Respect is very proud of our record in Tower Hamlets - especially of engaging young people in the political process.  "When so few young people see any point in voting, the Respect Party is proud to have vibrant young members making their voices and concerns heard." A Conservative spokesman said Mr Smith's comments had been noted, which were made before his selection as an assembly candidate. He added: "The comments were completely unacceptable and Matt has made it clear he apologises unreservedly for any offence he may have caused. 'Inexperienced candidate' "We have issued Mr Smith with a warning as to his future conduct, which he has accepted." The Liberal Democrats, who are defending the Cardiff Central seat, said said: "The comments speak for themselves and we would not wish to comment further other than to say that the Conservatives' choice of an inexperienced candidate prone to misjudged and immature comments will remind Conservative supporters how completely out of the race the Conservative Party are locally." A Plaid Cymru spokeswoman said Mr Smith's comments were "thoroughly tasteless and immoral". She added: "However, it seems that the three London parties are intent on turning this election into a mud-slinging contest in order to avoid talking about the issues that are important to the people of Wales." Welsh Labour declined to comment. The latest news comes after Joe Lock, who is Labour's Anglesey candidate, apologised on Thursday for postings he made last year about the former Conservative Prime Minister Margaret Thatcher.
[pool-2-thread-4] INFO debug-preprocessor - Cannot find node in dependency for word defending
[pool-2-thread-4] INFO debug-preprocessor - Cannot find node in dependency for word said
[pool-2-thread-4] INFO debug-preprocessor - Cannot find node in dependency for word said
[pool-2-thread-4] INFO debug-preprocessor - Cannot find node in dependency for word defending
[pool-2-thread-4] INFO debug-preprocessor - Cannot find node in dependency for word said
[pool-2-thread-4] INFO debug-preprocessor - Cannot find node in dependency for word said
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:400)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.toProto(ProtobufAnnotationSerializer.java:570)
	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.toProtoBuilder(ProtobufAnnotationSerializer.java:402)
	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.toProto(ProtobufAnnotationSerializer.java:347)
	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.toProtoBuilder(ProtobufAnnotationSerializer.java:502)
	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.toProto(ProtobufAnnotationSerializer.java:464)
	at edu.stanford.nlp.pipeline.KBPAnnotator.annotate(KBPAnnotator.java:249)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:75)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:541)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.lambda$handle$299(StanfordCoreNLPServer.java:382)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
``

**Comment by Izhaki** [comment]
Seems to work fine on a machine with more memory/disk space.

**Comment by ryan-gilbert** [comment]
How much memory did you ultimately need? I'm having this issue for quote attribution w/ 16 gigs of ram and 3gb free disk space.

**Comment by Izhaki** [comment]
@ryan-gilbert Sorry, this was long time ago in another part of town to which I have no access...
