### ISSUE TITLE
nullpointer expression while running coref in the simple API

### ISSUE THREAD

**Issue by siddhartha-gadgil** [stanfordnlp/CoreNLP#159]
I am getting a nullpointer expression for co-references for a certain complex sentence, though this sentence is parsed fine and co-references work fine for simpler sentences. This is in a scala REPL (ammonite REPL)

```scala
new Sentence("""In mathematics a divisor of an integer n, also called a factor of n, is an integer that can be multiplied by some other integer to produce n.""").coref 
java.lang.NullPointerException
  edu.stanford.nlp.hcoref.md.CorefMentionFinder.parse(CorefMentionFinder.java:600)
  edu.stanford.nlp.hcoref.md.CorefMentionFinder.findSyntacticHead(CorefMentionFinder.java:491)
  edu.stanford.nlp.hcoref.md.CorefMentionFinder.findHead(CorefMentionFinder.java:411)
  edu.stanford.nlp.hcoref.md.RuleBasedCorefMentionFinder.findMentions(RuleBasedCorefMentionFinder.java:95)
  edu.stanford.nlp.pipeline.MentionAnnotator.annotate(MentionAnnotator.java:79)
  edu.stanford.nlp.simple.Document.coref(Document.java:534)
  edu.stanford.nlp.simple.Document.coref(Document.java:553)
  edu.stanford.nlp.simple.Sentence.coref(Sentence.java:858)
  cmd28$.<init>(Main.scala:251)
  cmd28$.<clinit>(Main.scala:-1)
```

For contrast, here is a command that works (on the same REPL)
```scala
new Sentence("John likes his car").coref 
res29: java.util.Map[Integer, edu.stanford.nlp.hcoref.data.CorefChain] = {2=CHAIN2-["John" in sentence 1, "his" in sentence 1]}
```

**Comment by manning** [comment]
Are you running with some properties, such as selecting a non-default parser?  That is, if I test this sentence with the default English pipeline, it doesn't seem to crash, it just returns an empty Map.

If you just want to fix your problem for the short term, you should be able to by setting the property `coref.allowReparsing = false`.

**Comment by siddhartha-gadgil** [comment]
Thanks. I will use the workaround.

I was using the "Simple API" of the core-nlp  without any further
configuration. I re-ran with a fresh session and got the same error. My
library dependencies (in sbt) are

```scala

lazy val nlpSettings = Seq(

  libraryDependencies ++= Seq(

    "edu.stanford.nlp" % "stanford-corenlp" % "3.6.0",

    "edu.stanford.nlp" % "stanford-corenlp" % "3.6.0" classifier "models",

    "com.google.protobuf" % "protobuf-java" % "2.6.1"

    )
```

 Below is the complete REPL session.


```scala

@ import edu.stanford.nlp.simple._

import edu.stanford.nlp.simple._

@

 new Sentence("""In mathematics a divisor of an integer N, also called a
factor of N, is an integer that can be multiplied by some other integer to
produce N.""").parse

SLF4J: Class path contains multiple SLF4J bindings.

SLF4J: Found binding in
[jar:file:/home/gadgil/.ivy2/cache/org.slf4j/slf4j-nop/jars/slf4j-nop-1.7.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: Found binding in
[jar:file:/home/gadgil/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an
explanation.

SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]

done [1.4 sec].

res1: edu.stanford.nlp.trees.Tree = (ROOT (PP (IN In) (NP (NP (NNS
mathematics)) (SBAR (S (NP (NP (DT a) (NN divisor)) (PP (IN of) (NP (DT an)
(NN integer) (NNP N))) (, ,) (VP (ADVP (RB also)) (VBN called) (NP (NP (DT
a) (NN factor)) (PP (IN of) (NP (NNP N))))) (, ,)) (VP (VBZ is) (NP (NP (DT
an) (NN integer)) (SBAR (WHNP (WDT that)) (S (VP (MD can) (VP (VB be) (VP
(VBN multiplied) (PP (IN by) (NP (DT some) (JJ other) (NN integer))) (S (VP
(TO to) (VP (VB produce) (NP (NNP N.)))))))))))))))))

@

 new Sentence("""In mathematics a divisor of an integer N, also called a
factor of N, is an integer that can be multiplied by some other integer to
produce N.""").coref

Reading POS tagger model from
edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger
... done [1.0 sec].

Loading classifier from
edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done
[1.5 sec].

Loading classifier from
edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done
[0.7 sec].

Loading classifier from
edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ...
done [0.8 sec].

Reading TokensRegex rules from
edu/stanford/nlp/models/sutime/defs.sutime.txt

Mar 14, 2016 6:12:14 AM
edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules

INFO: Read 83 rules

Reading TokensRegex rules from
edu/stanford/nlp/models/sutime/english.sutime.txt

Mar 14, 2016 6:12:15 AM
edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules

INFO: Read 267 rules

Reading TokensRegex rules from
edu/stanford/nlp/models/sutime/english.holidays.sutime.txt

Mar 14, 2016 6:12:15 AM
edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules

INFO: Read 25 rules

Using mention detector type: rule

java.lang.NullPointerException


edu.stanford.nlp.hcoref.md.CorefMentionFinder.parse(CorefMentionFinder.java:600)


edu.stanford.nlp.hcoref.md.CorefMentionFinder.findSyntacticHead(CorefMentionFinder.java:491)


edu.stanford.nlp.hcoref.md.CorefMentionFinder.findHead(CorefMentionFinder.java:411)


edu.stanford.nlp.hcoref.md.RuleBasedCorefMentionFinder.findMentions(RuleBasedCorefMentionFinder.java:95)


edu.stanford.nlp.pipeline.MentionAnnotator.annotate(MentionAnnotator.java:79)

  edu.stanford.nlp.simple.Document.coref(Document.java:534)

  edu.stanford.nlp.simple.Document.coref(Document.java:553)

  edu.stanford.nlp.simple.Sentence.coref(Sentence.java:858)

  cmd2$.<init>(Main.scala:90)

  cmd2$.<clinit>(Main.scala:-1)


@  new Sentence("""In mathematics a divisor of an integer N is an integer
that can be multiplied by some other integer to produce N.""").coref

res3: java.util.Map[Integer, edu.stanford.nlp.hcoref.data.CorefChain] = {}

@  new Sentence("""In mathematics a divisor of an integer N is an integer
that can be multiplied by some other integer to produce it.""").coref

res4: java.util.Map[Integer, edu.stanford.nlp.hcoref.data.CorefChain] = {}

@  new Sentence("""If a prime number P divides MN, it divides one of M and
N""").coref

res5: java.util.Map[Integer, edu.stanford.nlp.hcoref.data.CorefChain] =
{1=CHAIN1-["a prime number P" in sentence 1, "it" in sentence 1]}
```

**Comment by gangeli** [comment]
Are you using the GitHub code or the official release? I tried your sentence in Java and it seems to work for me from HEAD:

`new Sentence("In mathematics a divisor of an integer n, also called a factor of n, is an integer that can be multiplied by some other integer to produce n.").coref();`

**Comment by siddhartha-gadgil** [comment]
I was using the official release downloaded by sbt from (I assume) Maven central. This is version 3.6.0 with the corresponding classifiers. In case it matters, I was using protocol buffers version 2.6.1.

I tried again in the standard scala sbt console and got the same error. Below is my full session.
```scala
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_74).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import edu.stanford.nlp.simple._
import edu.stanford.nlp.simple._

scala> new Sentence("""In mathematics a divisor of an integer n, also called a factor of n, is an integer that can be multiplied by some other integer to produce n.""").coref
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/gadgil/.ivy2/cache/org.slf4j/slf4j-nop/jars/slf4j-nop-1.7.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/gadgil/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.0 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.1 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.2 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.4 sec].
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/defs.sutime.txt
Mar 18, 2016 2:03:33 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Read 83 rules
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.sutime.txt
Mar 18, 2016 2:03:33 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Read 267 rules
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
Mar 18, 2016 2:03:33 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Read 25 rules
done [0.3 sec].
Using mention detector type: rule
java.lang.NullPointerException
  at edu.stanford.nlp.hcoref.md.CorefMentionFinder.parse(CorefMentionFinder.java:600)
  at edu.stanford.nlp.hcoref.md.CorefMentionFinder.findSyntacticHead(CorefMentionFinder.java:491)
  at edu.stanford.nlp.hcoref.md.CorefMentionFinder.findHead(CorefMentionFinder.java:411)
  at edu.stanford.nlp.hcoref.md.RuleBasedCorefMentionFinder.findMentions(RuleBasedCorefMentionFinder.java:95)
  at edu.stanford.nlp.pipeline.MentionAnnotator.annotate(MentionAnnotator.java:79)
  at edu.stanford.nlp.simple.Document.coref(Document.java:534)
  at edu.stanford.nlp.simple.Document.coref(Document.java:553)
  at edu.stanford.nlp.simple.Sentence.coref(Sentence.java:858)
  ... 43 elided

scala> 
```

**Comment by gangeli** [comment]
Can you try with the GitHub code? If it works on GitHub, then the problem will be fixed in the next release.

**Comment by J38** [comment]
I am seeing this work with our in development version of stanford-corenlp-3.7.0 and seeing it *NOT* work with stanford-corenlp-3.6.0, so I believe this bug has been fixed in the current code base!
