### ISSUE TITLE
Sentiment annotator not working with CoreNLP server

### ISSUE THREAD

**Issue by smilli** [stanfordnlp/CoreNLP#170]
If I try to use the sentiment annotator against the CoreNLP server, for example with the following command,

`wget --post-data 'The quick brown fox jumped over the lazy dog.' 'localhost:9000/?properties={"annotators":"sentiment","outputFormat":"json"}' -O -`

 I get a `java.lang.IllegalArgumentException: Unknown annotator: sentiment`

Any idea why this would be the case? Thanks.

**Comment by J38** [comment]
Do you get this error if you use the latest commit?

**Comment by smilli** [comment]
Oh you're right, I don't get the error when using the latest commit.

**Comment by smilli** [comment]
What is the correct way to build the project with the current models jar?

**Comment by J38** [comment]
If you go into the "javanlp/projects/core" and type "ant" it should build fine.  The build shouldn't depend on the model jars at all.  Then at runtime just make sure $CLASSPATH includes the version of the models that you want.

**Comment by smilli** [comment]
Is the sentiment model not bundled with the rest? I'm using the stanford-english-corenlp-models-current.jar and I get this error trace specifically when trying to use the sentiment annotator:

```
Adding annotator sentiment
Exception in thread "pool-1-thread-7" java.lang.NoClassDefFoundError: org/ejml/simple/SimpleBase
        at edu.stanford.nlp.pipeline.SentimentAnnotator.<init>(SentimentAnnotator.java:52)
        at edu.stanford.nlp.pipeline.AnnotatorImplementations.sentiment(AnnotatorImplementations.java:245)
        at edu.stanford.nlp.pipeline.AnnotatorFactories$16.create(AnnotatorFactories.java:577)
        at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:89)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:403)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:142)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:138)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.mkStanfordCoreNLP(StanfordCoreNLPServer.java:199)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$400(StanfordCoreNLPServer.java:42)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:380)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.ejml.simple.SimpleBase
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 19 more
```

**Comment by gangeli** [comment]
This is actually a library dependency that's missing. If you include `ejml-0.23.jar` in your classpath, it should work.

**Comment by smilli** [comment]
Oh got it.  Works perfect now, thanks!

**Comment by loretoparisi** [comment]
@gangeli I have added the jar and the annotators load...but given the example text (from the live demo [here](http://nlp.stanford.edu:8080/sentiment/rntnDemo.html))

`This movie doesn't care about cleverness, wit or any other kind of intelligent humor.`

I get like

```json
{
	"sentences": [{
		"index": 0,
		"parse": "(ROOT\n  (S\n    (NP (DT This) (NN movie))\n    (VP (VBZ does) (RB n't)\n      (VP (VB care)\n        (PP (IN about)\n          (NP\n            (NP (NN cleverness))\n            (, ,)\n            (NP (NN wit))\n            (CC or)\n            (NP\n              (NP (DT any) (JJ other) (NN kind))\n              (PP (IN of)\n                (NP (JJ intelligent) (NN humor))))))))\n    (. .)))",
		"basicDependencies": [{
			"dep": "ROOT",
			"governor": 0,
			"governorGloss": "ROOT",
			"dependent": 5,
			"dependentGloss": "care"
		}, {
			"dep": "det",
			"governor": 2,
			"governorGloss": "movie",
			"dependent": 1,
			"dependentGloss": "This"
		}, {
			"dep": "nsubj",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 2,
			"dependentGloss": "movie"
		}, {
			"dep": "aux",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 3,
			"dependentGloss": "does"
		}, {
			"dep": "neg",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 4,
			"dependentGloss": "n't"
		}, {
			"dep": "case",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 6,
			"dependentGloss": "about"
		}, {
			"dep": "nmod",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 7,
			"dependentGloss": "cleverness"
		}, {
			"dep": "punct",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 8,
			"dependentGloss": ","
		}, {
			"dep": "conj",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 9,
			"dependentGloss": "wit"
		}, {
			"dep": "cc",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 10,
			"dependentGloss": "or"
		}, {
			"dep": "det",
			"governor": 13,
			"governorGloss": "kind",
			"dependent": 11,
			"dependentGloss": "any"
		}, {
			"dep": "amod",
			"governor": 13,
			"governorGloss": "kind",
			"dependent": 12,
			"dependentGloss": "other"
		}, {
			"dep": "conj",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 13,
			"dependentGloss": "kind"
		}, {
			"dep": "case",
			"governor": 16,
			"governorGloss": "humor",
			"dependent": 14,
			"dependentGloss": "of"
		}, {
			"dep": "amod",
			"governor": 16,
			"governorGloss": "humor",
			"dependent": 15,
			"dependentGloss": "intelligent"
		}, {
			"dep": "nmod",
			"governor": 13,
			"governorGloss": "kind",
			"dependent": 16,
			"dependentGloss": "humor"
		}, {
			"dep": "punct",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 17,
			"dependentGloss": "."
		}],
		"enhancedDependencies": [{
			"dep": "ROOT",
			"governor": 0,
			"governorGloss": "ROOT",
			"dependent": 5,
			"dependentGloss": "care"
		}, {
			"dep": "det",
			"governor": 2,
			"governorGloss": "movie",
			"dependent": 1,
			"dependentGloss": "This"
		}, {
			"dep": "nsubj",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 2,
			"dependentGloss": "movie"
		}, {
			"dep": "aux",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 3,
			"dependentGloss": "does"
		}, {
			"dep": "neg",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 4,
			"dependentGloss": "n't"
		}, {
			"dep": "case",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 6,
			"dependentGloss": "about"
		}, {
			"dep": "nmod:about",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 7,
			"dependentGloss": "cleverness"
		}, {
			"dep": "punct",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 8,
			"dependentGloss": ","
		}, {
			"dep": "nmod:about",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 9,
			"dependentGloss": "wit"
		}, {
			"dep": "conj:or",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 9,
			"dependentGloss": "wit"
		}, {
			"dep": "cc",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 10,
			"dependentGloss": "or"
		}, {
			"dep": "det",
			"governor": 13,
			"governorGloss": "kind",
			"dependent": 11,
			"dependentGloss": "any"
		}, {
			"dep": "amod",
			"governor": 13,
			"governorGloss": "kind",
			"dependent": 12,
			"dependentGloss": "other"
		}, {
			"dep": "nmod:about",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 13,
			"dependentGloss": "kind"
		}, {
			"dep": "conj:or",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 13,
			"dependentGloss": "kind"
		}, {
			"dep": "case",
			"governor": 16,
			"governorGloss": "humor",
			"dependent": 14,
			"dependentGloss": "of"
		}, {
			"dep": "amod",
			"governor": 16,
			"governorGloss": "humor",
			"dependent": 15,
			"dependentGloss": "intelligent"
		}, {
			"dep": "nmod:of",
			"governor": 13,
			"governorGloss": "kind",
			"dependent": 16,
			"dependentGloss": "humor"
		}, {
			"dep": "punct",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 17,
			"dependentGloss": "."
		}],
		"enhancedPlusPlusDependencies": [{
			"dep": "ROOT",
			"governor": 0,
			"governorGloss": "ROOT",
			"dependent": 5,
			"dependentGloss": "care"
		}, {
			"dep": "det",
			"governor": 2,
			"governorGloss": "movie",
			"dependent": 1,
			"dependentGloss": "This"
		}, {
			"dep": "nsubj",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 2,
			"dependentGloss": "movie"
		}, {
			"dep": "aux",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 3,
			"dependentGloss": "does"
		}, {
			"dep": "neg",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 4,
			"dependentGloss": "n't"
		}, {
			"dep": "case",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 6,
			"dependentGloss": "about"
		}, {
			"dep": "nmod:about",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 7,
			"dependentGloss": "cleverness"
		}, {
			"dep": "punct",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 8,
			"dependentGloss": ","
		}, {
			"dep": "nmod:about",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 9,
			"dependentGloss": "wit"
		}, {
			"dep": "conj:or",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 9,
			"dependentGloss": "wit"
		}, {
			"dep": "cc",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 10,
			"dependentGloss": "or"
		}, {
			"dep": "det",
			"governor": 13,
			"governorGloss": "kind",
			"dependent": 11,
			"dependentGloss": "any"
		}, {
			"dep": "amod",
			"governor": 13,
			"governorGloss": "kind",
			"dependent": 12,
			"dependentGloss": "other"
		}, {
			"dep": "nmod:about",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 13,
			"dependentGloss": "kind"
		}, {
			"dep": "conj:or",
			"governor": 7,
			"governorGloss": "cleverness",
			"dependent": 13,
			"dependentGloss": "kind"
		}, {
			"dep": "case",
			"governor": 16,
			"governorGloss": "humor",
			"dependent": 14,
			"dependentGloss": "of"
		}, {
			"dep": "amod",
			"governor": 16,
			"governorGloss": "humor",
			"dependent": 15,
			"dependentGloss": "intelligent"
		}, {
			"dep": "nmod:of",
			"governor": 13,
			"governorGloss": "kind",
			"dependent": 16,
			"dependentGloss": "humor"
		}, {
			"dep": "punct",
			"governor": 5,
			"governorGloss": "care",
			"dependent": 17,
			"dependentGloss": "."
		}],
		"sentimentValue": "1",
		"sentiment": "Negative",
		"tokens": [{
			"index": 1,
			"word": "This",
			"originalText": "This",
			"characterOffsetBegin": 0,
			"characterOffsetEnd": 4,
			"pos": "DT",
			"before": "",
			"after": " "
		}, {
			"index": 2,
			"word": "movie",
			"originalText": "movie",
			"characterOffsetBegin": 5,
			"characterOffsetEnd": 10,
			"pos": "NN",
			"before": " ",
			"after": " "
		}, {
			"index": 3,
			"word": "does",
			"originalText": "does",
			"characterOffsetBegin": 11,
			"characterOffsetEnd": 15,
			"pos": "VBZ",
			"before": " ",
			"after": ""
		}, {
			"index": 4,
			"word": "n't",
			"originalText": "n't",
			"characterOffsetBegin": 15,
			"characterOffsetEnd": 18,
			"pos": "RB",
			"before": "",
			"after": " "
		}, {
			"index": 5,
			"word": "care",
			"originalText": "care",
			"characterOffsetBegin": 19,
			"characterOffsetEnd": 23,
			"pos": "VB",
			"before": " ",
			"after": " "
		}, {
			"index": 6,
			"word": "about",
			"originalText": "about",
			"characterOffsetBegin": 24,
			"characterOffsetEnd": 29,
			"pos": "IN",
			"before": " ",
			"after": " "
		}, {
			"index": 7,
			"word": "cleverness",
			"originalText": "cleverness",
			"characterOffsetBegin": 30,
			"characterOffsetEnd": 40,
			"pos": "NN",
			"before": " ",
			"after": ""
		}, {
			"index": 8,
			"word": ",",
			"originalText": ",",
			"characterOffsetBegin": 40,
			"characterOffsetEnd": 41,
			"pos": ",",
			"before": "",
			"after": " "
		}, {
			"index": 9,
			"word": "wit",
			"originalText": "wit",
			"characterOffsetBegin": 42,
			"characterOffsetEnd": 45,
			"pos": "NN",
			"before": " ",
			"after": " "
		}, {
			"index": 10,
			"word": "or",
			"originalText": "or",
			"characterOffsetBegin": 46,
			"characterOffsetEnd": 48,
			"pos": "CC",
			"before": " ",
			"after": " "
		}, {
			"index": 11,
			"word": "any",
			"originalText": "any",
			"characterOffsetBegin": 49,
			"characterOffsetEnd": 52,
			"pos": "DT",
			"before": " ",
			"after": " "
		}, {
			"index": 12,
			"word": "other",
			"originalText": "other",
			"characterOffsetBegin": 53,
			"characterOffsetEnd": 58,
			"pos": "JJ",
			"before": " ",
			"after": " "
		}, {
			"index": 13,
			"word": "kind",
			"originalText": "kind",
			"characterOffsetBegin": 59,
			"characterOffsetEnd": 63,
			"pos": "NN",
			"before": " ",
			"after": " "
		}, {
			"index": 14,
			"word": "of",
			"originalText": "of",
			"characterOffsetBegin": 64,
			"characterOffsetEnd": 66,
			"pos": "IN",
			"before": " ",
			"after": " "
		}, {
			"index": 15,
			"word": "intelligent",
			"originalText": "intelligent",
			"characterOffsetBegin": 67,
			"characterOffsetEnd": 78,
			"pos": "JJ",
			"before": " ",
			"after": " "
		}, {
			"index": 16,
			"word": "humor",
			"originalText": "humor",
			"characterOffsetBegin": 79,
			"characterOffsetEnd": 84,
			"pos": "NN",
			"before": " ",
			"after": ""
		}, {
			"index": 17,
			"word": ".",
			"originalText": ".",
			"characterOffsetBegin": 84,
			"characterOffsetEnd": 85,
			"pos": ".",
			"before": "",
			"after": ""
		}]
	}]
}
```

so just 

```json
{
"sentimentValue": "1",
"sentiment": "Negative"
}
```

While from the live demo I get a more complex representation for the binary tree like [here](https://gist.github.com/loretoparisi/4bba7a9cd00d34e8e211484d454b928c).

**Comment by gangeli** [comment]
Is this the live demo on corenlp.run, or the live demo for the actual sentiment project? Currently the JsonOutputter class doesn't output the full sentiment information to JSON -- see https://github.com/stanfordnlp/CoreNLP/blob/2a4db022709e93ca484a0104d160b99176166b16/src/edu/stanford/nlp/pipeline/JSONOutputter.java#L104

**Comment by loretoparisi** [comment]
@gangeli the latter is the live demo project not the CoreNLP server. The former is the output of the CoreNLP SDK i.e. `edu.stanford.nlp.pipeline.Annotation"`.
So do I need to change the `JSONOutputter` to something else to get the whole output?
