### ISSUE TITLE
CoreNLP Server does not support Chinese?

### ISSUE THREAD

**Issue by xulihang** [stanfordnlp/CoreNLP#221]
I downloaded the CoreNLP 3.6.0. I am able to have a right result using this command:
```
java -Xmx6g edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-chinese.properties -file chinese-example-2.txt -outputFormat text
```

But when I start it as a server, like
```
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -props StanfordCoreNLP-chinese.properties
```

and use wget:
```
wget   --post-data '你是谁？' 'localhost:9000/?properties={"annotators":"segment,pos","outputFormat":"json"}' -O -
```
It will go wrong saying "unknown annotators: segment".

I have searched all the results on the Internet and I found [an article](http://hujiaweibujidao.github.io/blog/2016/04/01/Head-First-Standford-NLP-4/) pointing out that the source code has problems. The part of server code does not receive the props parameter correctly and it just loads the default props.

**Comment by scottyli** [comment]
#165

**Comment by J38** [comment]
This issue has now been resolved in the current version of the code.  If you enter a command like this:

`wget --post-data '<insert Chinese text here>' 'localhost:9000/?properties={"pipelineLanguage":"zh", "outputFormat":"json"}'  -O -`  the server will load the appropriate Chinese resources.

**Comment by xulihang** [comment]
how to use it on the web page?

**Comment by hezhenghao** [comment]
I'm getting NullPointerException when using @J38 's command:
java.lang.NullPointerException
at java.util.Properties$LineReader.readLine(Properties.java:434)
at java.util.Properties.load0(Properties.java:353)
at java.util.Properties.load(Properties.java:341)
at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.getProperties(StanfordCoreNLPServer.java:681)
at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:540) at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
