### ISSUE TITLE
Stanford NLP Server:: Unknown annotator: sentiment

### ISSUE THREAD

**Issue by hassanz** [stanfordnlp/CoreNLP#238]
I just downloaded and ran Standfor NLP 3.6.0 http://stanfordnlp.github.io/CoreNLP/index.html by using the following command:

`java -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer --public --port 1062`
I tested other annotators like POS, Tokenizer and they work just ok. However, when I try to run sentiment annotator[ http://nlp.stanford.edu/sentiment/ ] I get following errors:
```

java.lang.IllegalArgumentException: Unknown annotator: sentiment
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.ensurePrerequisiteAnnotators(StanfordCoreNLP.java:281)
    at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.getProperties(StanfordCoreNLPServer.java:476)
    at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:350)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
I uploaded all the files I got from the download page[http://stanfordnlp.github.io/CoreNLP/index.html#download] not sure what am I missing?

**Comment by gangeli** [comment]
Can you try with the GitHub version of the code? There have been substantial updates to the server since the 3.6.0 release.

**Comment by atomicreach5** [comment]
Thank you. We will take a look.

Paul

**Comment by hassanz** [comment]
Thanks @gangeli 
Now I am getting the following error:

```
Starting server...
StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:1062
{annotators=tokenize, ssplit, pos, parse,sentiment, outputFormat=json}
[/127.0.0.1:56428] API call w/annotators tokenize,ssplit,pos,parse,sentiment
the quick brown fox jumped over the lazy dog
Adding annotator tokenize
No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator pos
java.lang.RuntimeException: edu.stanford.nlp.io.RuntimeIOException: Error while loading a tagger model (probably missing model file)
        at edu.stanford.nlp.pipeline.AnnotatorFactories$4.create(AnnotatorFactories.java:243)
        at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:120)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:452)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:155)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:146)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.mkStanfordCoreNLP(StanfordCoreNLPServer.java:231)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$500(StanfordCoreNLPServer.java:41)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:477)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: edu.stanford.nlp.io.RuntimeIOException: Error while loading a tagger model (probably missing model file)
        at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:794)
        at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:315)
        at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:266)
        at edu.stanford.nlp.pipeline.POSTaggerAnnotator.loadModel(POSTaggerAnnotator.java:85)
        at edu.stanford.nlp.pipeline.POSTaggerAnnotator.<init>(POSTaggerAnnotator.java:73)
        at edu.stanford.nlp.pipeline.AnnotatorImplementations.posTagger(AnnotatorImplementations.java:63)
        at edu.stanford.nlp.pipeline.AnnotatorFactories$4.create(AnnotatorFactories.java:241)
        ... 16 more
Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" as class path, filename or URL
        at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:478)
        at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:792)
        ... 22 more
```

**Comment by gangeli** [comment]
Make sure you have the models jar in your classpath. You can download the models from the link on our README (http://nlp.stanford.edu/software/stanford-corenlp-models-current.jar).

**Comment by hassanz** [comment]
Thanks again @gangeli 
I have included that file and now I am getting this:

```
[/127.0.0.1:36001] API call w/annotators tokenize,ssplit,pos,parse,sentiment
the quick brown fox jumped over the lazy dog
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Adding annotator parse
edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/models/srparser/englishSR.ser.gz" as class path, filename or URL
        at edu.stanford.nlp.parser.common.ParserGrammar.loadModel(ParserGrammar.java:187)
        at edu.stanford.nlp.pipeline.ParserAnnotator.loadModel(ParserAnnotator.java:217)
        at edu.stanford.nlp.pipeline.ParserAnnotator.<init>(ParserAnnotator.java:119)
        at edu.stanford.nlp.pipeline.AnnotatorImplementations.parse(AnnotatorImplementations.java:154)
        at edu.stanford.nlp.pipeline.AnnotatorFactories$11.create(AnnotatorFactories.java:357)
        at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:120)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:452)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:155)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:146)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.mkStanfordCoreNLP(StanfordCoreNLPServer.java:231)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$500(StanfordCoreNLPServer.java:41)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:477)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/srparser/englishSR.ser.gz" as class path, filename or URL
        at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:478)
        at edu.stanford.nlp.io.IOUtils.readObjectFromURLOrClasspathOrFileSystem(IOUtils.java:317)
        at edu.stanford.nlp.parser.common.ParserGrammar.loadModel(ParserGrammar.java:184)
        ... 20 more
{annotators=pos, outputFormat=json}

```

I cannot find any directory called `models` anywhere.

**Comment by gangeli** [comment]
Ah, you need the English models for the shift reduce parser. These can be
found at:
http://nlp.stanford.edu/software/stanford-english-corenlp-models-current.jar
(warning: very large download)

**Comment by hassanz** [comment]
works now!! Thanks @gangeli

**Comment by loretoparisi** [comment]
@gangeli I get a similar problem but for a different resource see https://github.com/stanfordnlp/CoreNLP/issues/340

thanks for the help in advance!
