### ISSUE TITLE
Cannot find org/joda/time/ReadablePartial when running SUTime

### ISSUE THREAD

**Issue by 666666fzl** [stanfordnlp/CoreNLP#256]
I'm trying to run SUTime, following the instruction from SUTime page.
The command I used is 
```
java -Dpos.model=edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger \
-cp stanford-corenlp-2016-01-10.jar:stanford-english-corenlp-2016-01-10-models.jar:xom-1.2.10.jar:joda-time.jar:jollyday-0.4.9.jar \
-Xmx3g edu.stanford.nlp.time.SUTimeMain \
-in.type TEXTFILE \
-date 2016-09-01 \
-i test.txt \
-o res.txt
```

However, I received this error msg:
```
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.6 sec].
Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial
	at edu.stanford.nlp.time.TimeAnnotator.<init>(TimeAnnotator.java:189)
	at edu.stanford.nlp.time.TimeAnnotator.<init>(TimeAnnotator.java:185)
	at edu.stanford.nlp.time.SUTimeMain.getPipeline(SUTimeMain.java:900)
	at edu.stanford.nlp.time.SUTimeMain.main(SUTimeMain.java:1058)
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadablePartial
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
```

It seems that something in joda time is missing? But I add joda-time.jar to the -cp arg already.
Has anyone run into this problem before? Thx a lot.

**Comment by manning** [comment]
This works for me. I think you just don't have jodatime validly on your classpath. Is your jar called exactly `jollyday-0.4.9.jar` and in the same directory?
