### ISSUE TITLE
Null Pointer exception during parsing

### ISSUE THREAD

**Issue by generall** [stanfordnlp/CoreNLP#276]
Faced following error while processing large dataset:

```
java.lang.NullPointerException
        at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.correctWHAttachment(UniversalEnglishGrammaticalStructure.java:690)
        at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.postProcessDependencies(UniversalEnglishGrammaticalStructure.java:173)
        at edu.stanford.nlp.trees.GrammaticalStructure.getDeps(GrammaticalStructure.java:560)
        at edu.stanford.nlp.trees.GrammaticalStructure.<init>(GrammaticalStructure.java:215)
        at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.<init>(UniversalEnglishGrammaticalStructure.java:92)
        at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.<init>(UniversalEnglishGrammaticalStructure.java:71)
        at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructureFactory.newGrammaticalStructure(UniversalEnglishGrammaticalStructureFactory.java:29)
        at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructureFactory.newGrammaticalStructure(UniversalEnglishGrammaticalStructureFactory.java:5)
        at edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations(ParserAnnotatorUtils.java:59)
        at edu.stanford.nlp.pipeline.ParserAnnotator.finishSentence(ParserAnnotator.java:290)
        at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:260)
        at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:98)
        at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:71)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:499)
```
Unfortunately can not reproduce this error nor say which data cause this exception

**Comment by sebschu** [comment]
Thanks for reporting this! Can you tell us a bit more about how you processed your data (e.g., which annotators did you use) and which version you used (e.g., 3.6.0 or the GitHub commit hash)?

**Comment by generall** [comment]
I used `"tokenize, ssplit, pos, lemma, parse"` annotators, version: `"edu.stanford.nlp" % "stanford-corenlp" % "3.6.0"`
