### ISSUE TITLE
openie can't work well with corenlp

### ISSUE THREAD

**Issue by ItGql** [stanfordnlp/CoreNLP#304]
when i run openie in eclipse with jar of the model,there is a error:
local class incompatible:stream classdesc serialVersionUID=4155...,local class serialVersionUID=-7360...
@gangeli

**Comment by gangeli** [comment]
Are you using the GitHub HEAD of the code, or the 3.7.0 beta? I know a bug like this existed near the 3.6.0 release, but I believe it's been fixed since then. If this is with the most recent code, can you reproduce the error on the command-line, and post the steps here?

**Comment by ItGql** [comment]
Thanks for your answer.
I'm using code on the github,version writed in pom.xml is 3.7.0.After importing the corenlp model jar(3.7.0)  ,when i run the main methods of OpenIEDemo.java,it reports:
`Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Could not load clause splitter model at edu/stanford/nlp/models/naturalli/clauseSearcherModel.ser.gz
	at edu.stanford.nlp.naturalli.OpenIE.<init>(OpenIE.java:205)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.openie(AnnotatorImplementations.java:291)
	at edu.stanford.nlp.pipeline.AnnotatorFactories$20.create(AnnotatorFactories.java:506)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:152)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:150)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:137)
	at edu.stanford.nlp.naturalli.OpenIEDemo.main(OpenIEDemo.java:35)
Caused by: java.io.InvalidClassException: edu.stanford.nlp.naturalli.ClauseSplitterSearchProblem$8; local class incompatible: stream classdesc serialVersionUID = 4145523451314579506, local class serialVersionUID = -7360029270983346606
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at edu.stanford.nlp.io.IOUtils.readObjectFromURLOrClasspathOrFileSystem(IOUtils.java:318)
	at edu.stanford.nlp.naturalli.ClauseSplitter.load(ClauseSplitter.java:283)
	at edu.stanford.nlp.naturalli.OpenIE.<init>(OpenIE.java:200)
	... 8 more
`

**Comment by J38** [comment]
This command works with the latest version of the code:

`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,mention,entitymentions,coref,natlog,openie -file sample-sentence.txt -outputFormat text`

**Comment by XiaohuanIT** [comment]
If you use the openie in the eclipse IDE, you can try to only use the file of OpenIEDemo.java to buid new a new java project, rather than use the whole openie source code to build java project. For the file of OpenIEDemo.java, you can access the website of http://stanfordnlp.github.io/CoreNLP/openie.html, the API is what you need. By the way, you should add stanford-openie.jar, stanford-openie-models.jar and stanford-english-corenlp-models-current.jar to the build path. For the reason why using whole source code will encounter the issue, I do not know. If you know, please tell me.

**Comment by sesimilar** [comment]
@ItGql Do you solve this problem? I also meet this error when I run 3.7.0 code downloading from github.
