### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by rylanchiu** [stanfordnlp/CoreNLP#313]
I am trying to do sentiment analysis on a text file with about 10, 000 lines and each line per sentence. I run the tool with command:

    java -cp "*" -Xmx10g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,parse,sentiment -file ../gp/post_content/DOTA2.txt_content.txt

But it throws an error: 

    Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at edu.stanford.nlp.util.logging.OutputHandler.handle(OutputHandler.java:393)
	at edu.stanford.nlp.util.logging.Redwood$RecordHandlerTree.process(Redwood.java:743)
	at edu.stanford.nlp.util.logging.Redwood$RecordHandlerTree.process(Redwood.java:779)
	at edu.stanford.nlp.util.logging.Redwood$RecordHandlerTree.access$000(Redwood.java:620)
	at edu.stanford.nlp.util.logging.Redwood.log(Redwood.java:306)
	at edu.stanford.nlp.util.logging.Redwood$RedwoodChannels.log(Redwood.java:1231)
	at edu.stanford.nlp.util.logging.Redwood$RedwoodChannels.info(Redwood.java:1283)
	at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:358)
	at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:254)
	at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:102)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:75)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:605)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:615)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$37/22429093.accept(Unknown Source)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1167)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:948)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.run(StanfordCoreNLP.java:1256)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1326)

I wonder how can I solve this issue? Thanks in advance!

**Comment by AngledLuffa** [comment]
My guess is one of the sentences is too long

**Comment by J38** [comment]
You need to add a "-ssplit.eolonly" to that command, I think that'll fix it.

**Comment by melbarosalind** [comment]
java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,parse,sentiment -file cleanreviews.txt -ssplit.eolonly
I get the following error while executing the above command. How to resolve it???????
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at edu.stanford.nlp.ling.SentenceUtils.listToString(SentenceUtils.java:186)
        at edu.stanford.nlp.ling.SentenceUtils.listToString(SentenceUtils.java:171)
        at edu.stanford.nlp.ling.SentenceUtils.listToString(SentenceUtils.java:150)
        at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:360)
        at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:254)
        at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:102)
        at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:637)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:647)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$45/2012846597.accept(Unknown Source)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1226)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1060)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.run(StanfordCoreNLP.java:1326)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1389)
