### ISSUE TITLE
NoClassDefFoundError - Message I keep getting

### ISSUE THREAD

**Issue by azmatzuberi** [stanfordnlp/CoreNLP#318]
Hi,

I've added all the jar files in NetBeans to the library folder, but I still keep getting the:

NoClassDefFoundError

error whenever I run the project. The class(es) that it's looking for are the Document and Sentence class. As this is the Core NLP Simple version, the import statement works and NetBeans doesn't show any problems in the editor, but when I run the project it gives me this error.

Would appreciate the help.

**Comment by gangeli** [comment]
What's the full error / stack trace? The most likely explanation is that you're missing the CoreNLP jar (and models jar) from your classpath. Try setting your `CLASSPATH` environment variable to include these jars, or specifying them with the `-cp` flag to Java.

**Comment by azmatzuberi** [comment]
Here's the full stack trace:

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessage$ExtendableMessageOrBuilder
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at edu.stanford.nlp.simple.Document.<init>(Document.java:433)
	at edu.stanford.nlp.simple.Document.<init>(Document.java:442)
	at nlp.standalone.SimpleCoreNLPDemo.main(SimpleCoreNLPDemo.java:14)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.GeneratedMessage$ExtendableMessageOrBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
/Users/azmatzuberi/Library/Caches/NetBeans/8.1/executor-snippets/run.xml:53: Java returned: 1
BUILD FAILED (total time: 2 seconds)

**Comment by gangeli** [comment]
Ah, you're trying to use the simple API, which is backed by protocol buffers You need to include the protobuf runtime library in your classpath. The version we use is 2.6.1: https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/2.6.1
