### ISSUE TITLE
Null pointer exception when using CoreNLP server for processing Chinese

### ISSUE THREAD

**Issue by hezhenghao** [stanfordnlp/CoreNLP#320]
Hi,

When I use `wget --post-data '<insert Chinese text here>' 'localhost:9000/?properties={"pipelineLanguage":"zh", "outputFormat":"json"}' -O -` to process Chinese, as suggested in [this thread](https://github.com/stanfordnlp/CoreNLP/issues/221), I get a NullPointerException:

java.lang.NullPointerException
at java.util.Properties$LineReader.readLine(Properties.java:434)
at java.util.Properties.load0(Properties.java:353)
at java.util.Properties.load(Properties.java:341)
at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.getProperties(StanfordCoreNLPServer.java:681)
at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:540) at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

I have already put the Chinese model file `stanford-chinese-corenlp-2016-01-19-models.jar` into the root folder of CoreNLP. To have better chance of getting things to work, I also put a copy of `StanfordCoreNLP-chinese.properties` into the root folder. However, I have no luck. The same NullPointerException keeps popping up. If I change `pipelineLanguage` to `en` it works. If I change `pipelineLanguage` to `fr` or `de` it doesn't work. (I haven't downloaded the French or German models, so that could be the reason why it fails on the last two occasions. But regardless, I have the Chinese models and I'm still getting the same error messages for setting `pipelineLanguage` to `zh`.)

I can get the non-server program to work with Chinese, using the command:
`java -mx3g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-chinese.properties -file chinese.txt -outputFormat text`

Someone please help. I only have a couple of days.

**Comment by J38** [comment]
This command will start the server:
`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties StanfordCoreNLP-chinese.properties`

This is how to make a request:
`wget --post-data 'insert text here' 'localhost:9000/?properties={"outputFormat":"json"}' -O -`
