### ISSUE TITLE
Training own true case  models

### ISSUE THREAD

**Issue by aliabbasjp** [stanfordnlp/CoreNLP#336]
Hi,
There seems to be many inconsistencies in the truce casing model , hence I need to retrain it on my data , how can I train the same using my own training data?

**Comment by AngledLuffa** [comment]
If you help us find errors in the data, we can also use them to train
better models ourselves, although there is no time frame for when that
would happen.

**Comment by aliabbasjp** [comment]
@AngledLuffa  I dont have the possession of the data trainFileList=/scr/nlp/data/gale/NIST09/truecaser/crf/noUN.input

where can I find this?
In my case the following input:

`3. l loss
`
changed to:


`3. L LOSS 
`

**Comment by aliabbasjp** [comment]
@AngledLuffa  Also can you guide me on the input data training format or a sample of the above training file?

**Comment by AngledLuffa** [comment]
This example seems kind of short, not much to go on.  The truecaser is
meant for actual sentences.

The input file can't be shared, unfortunately.  The format is properly
capitalized sentences tokenized like this:

It should be noted that the Iraqi president , whose father died when he was
very young , has four half - brothers from his mother who married his uncle
.

**Comment by manning** [comment]
Here's the command we used to train our model. The prop file is included in the jar. As John commented, we can't distribute the training data. But it is just already tokenized (whitespace-separated), one sentence per line text.

truecasing.fast.caseless.qn.ser.gz: truecasing.fast.caseless.prop
	$(JAVA) -mx110g edu.stanford.nlp.ie.crf.CRFClassifier -prop $^ -serializeTo $@ -multiThreadGrad 8 > $(addsuffix .out, $(basename $^)) 2> $(addsuffix .err, $(basename $^))

I agree the data isn't very good. It's decade old data from an MT project.

**Comment by aliabbasjp** [comment]
@manning What is the maximum train text data size for a 350 gb RAM machine with 40 cores?, I tried a 900MB file it crashed after 12 days.

**Comment by d-belyakin** [comment]
Tried to use my own model:
> java -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLP -props English.properties -file input.txt
Setting bias for class INIT_UPPER to 0.0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at edu.stanford.nlp.ie.crf.CRFBiasedClassifier.setBiasWeight(CRFBiasedClassifier.java:112)
        at edu.stanford.nlp.ie.crf.CRFBiasedClassifier.setBiasWeight(CRFBiasedClassifier.java:106)

What I'm doing wrong?
