### ISSUE TITLE
Custom Relationship

### ISSUE THREAD

**Issue by zingzai** [stanfordnlp/CoreNLP#344]
Hi all. I'm trying to create my own relationship model and be able to extract my own custom relationships using a training file. I'm trying to use what is provided on StanfordNLP's website as a test, http://nlp.stanford.edu/software/relationExtractor.shtml.

I'm using the default roth.properties file as follows:

```
#Below are some basic options. See edu.stanford.nlp.ie.machinereading.MachineReadingProperties class for more options.

# Pipeline options
annotators = tokenize,ssplit, pos, lemma, parse
parse.maxlen = 100

# MachineReading properties. You need one class to read the dataset into correct format. See edu.stanford.nlp.ie.machinereading.domains.ace.AceReader for another example.
datasetReaderClass = edu.stanford.nlp.ie.machinereading.domains.roth.RothCONLL04Reader

#Data directory for training. The datasetReaderClass reads data from this path and makes corresponding sentences and annotations.
trainPath = kill.corp (http://l2r.cs.uiuc.edu/~cogcomp/Data/ER/kill.corp)

#Whether to crossValidate, that is evaluate, or just train.
crossValidate = false
kfold = 10

#Change this to true if you want to use CoreNLP pipeline generated NER tags. The default model generated with the relation extractor release uses the CoreNLP pipeline provided tags (option set to true).
trainUsePipelineNER= false

# where to save training sentences. uses the file if it exists, otherwise creates it.
serializedTrainingSentencesPath = roth_sentences.ser

serializedEntityExtractorPath = roth_entity_model.ser

# where to store the output of the extractor (sentence objects with relations generated by the model). This is what you will use as the model when using 'relation' annotator in the CoreNLP pipeline.
serializedRelationExtractorPath = roth_relation_model_pipeline.ser

# uncomment to load a serialized model instead of retraining
# loadModel = true

#relationResultsPrinters = edu.stanford.nlp.ie.machinereading.RelationExtractorResultsPrinter,edu.stanford.nlp.ie.machinereading.domains.roth.RothResultsByRelation. For printing output of the model.
relationResultsPrinters = edu.stanford.nlp.ie.machinereading.RelationExtractorResultsPrinter

#In this domain, this is trivial since all the entities are given (or set using CoreNLP NER tagger).
entityClassifier = edu.stanford.nlp.ie.machinereading.domains.roth.RothEntityExtractor

extractRelations = true
extractEvents = false

#We are setting the entities beforehand so the model does not learn how to extract entities etc.
extractEntities = false

#Opposite of crossValidate. 
trainOnly=true

# The set chosen by feature selection using RothCONLL04:
relationFeatures = arg_words,arg_type,dependency_path_lowlevel,dependency_path_words,surface_path_POS,entities_between_args,full_tree_path

# The above features plus the features used in Bjorne BioNLP09:
# relationFeatures = arg_words,arg_type,dependency_path_lowlevel,dependency_path_words,surface_path_POS,entities_between_args,full_tree_path,dependency_path_POS_unigrams,dependency_path_word_n_grams,dependency_path_POS_n_grams,dependency_path_edge_lowlevel_n_grams,dependency_path_edge-node-edge-grams_lowlevel,dependency_path_node-edge-node-grams_lowlevel,dependency_path_directed_bigrams,dependency_path_edge_unigrams,same_head,entity_counts
```

My Java code is as follows:

```
    Properties props = StringUtils.propFileToProperties("roth.properties");
    props.setProperty("sup.relation.model", "roth_relation_model_pipeline.ser");

    StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
    String text = "James killed Mary. ";

    Annotation document = new Annotation(text);
    pipeline.annotate(document);

    List<CoreMap> sentences = document.get(SentencesAnnotation.class);

    for (CoreMap sentence : sentences) {
        List<RelationMention> relations = sentence.get(MachineReadingAnnotations.RelationMentionsAnnotation.class);
        for (RelationMention r : relations) {
            System.out.println(r.toString());
        }
    }

```

Serialised files should be created if they do not exists. However, no serialised files were created. I'm getting a NullExceptionPointer error.

Any help is greatly appreciated. Thank you for your time. :1st_place_medal:

**Comment by J38** [comment]
Can you provide the error message in full?

**Comment by zingzai** [comment]
The error message is as follows:
`[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.0 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.4 sec].
Exception in thread "main" java.lang.NullPointerException
	at test.test1.extractCustom(test1.java:84)
	at test.test1.main(test1.java:62)
`

**Comment by zingzai** [comment]
I've also tried the MachineReading class as I read on furthur. But failed while loading the properties file.

```
String[] arg = new String[1];
arg[0] = "roth.properties";
MachineReading.makeMachineReading(arg);
```

The error message is as follows:
```
[main] ERROR CoreNLP - Missing required option: datasetreaderclass   <in class: class edu.stanford.nlp.ie.machinereading.MachineReadingProperties>
[main] ERROR CoreNLP - Missing required option: serializedtrainingsentencespath   <in class: class edu.stanford.nlp.ie.machinereading.MachineReadingProperties>
Exception in thread "main" java.lang.RuntimeException: Not able to parse properties!!!
	at edu.stanford.nlp.util.ArgumentParser.fillOptionsImpl(ArgumentParser.java:568)
	at edu.stanford.nlp.util.ArgumentParser.fillOptionsImpl(ArgumentParser.java:579)
	at edu.stanford.nlp.util.ArgumentParser.fillOptions(ArgumentParser.java:628)
	at edu.stanford.nlp.util.ArgumentParser.fillOptions(ArgumentParser.java:653)
	at edu.stanford.nlp.ie.machinereading.MachineReading.makeMachineReading(MachineReading.java:207)
	at test.test1.main(test1.java:61)
```

Thank you for your help.

**Comment by thatguysimon** [comment]
The last error says your properties file can't be parsed.
try replacing
`trainPath = kill.corp (http://l2r.cs.uiuc.edu/~cogcomp/Data/ER/kill.corp)`
with
`trainPath = kill.corp`

**Comment by zingzai** [comment]
Hello. Thank you for the reply. Actually i didnt include it in my implementation. It was just to show where I download the file from. Any more suggestions? :)

**Comment by J38** [comment]
When I run the example command with the latest code and models it works fine.

`java -cp classpath edu.stanford.nlp.ie.machinereading.MachineReading --arguments roth.properties`

Note in your example you want `String[] args = new String[]{"-arguments", "roth.properties"};`
