### ISSUE TITLE
No roots in graph

### ISSUE THREAD

**Issue by alex-j-j** [stanfordnlp/CoreNLP#352]
I constantly get the following exception for single-token sentences (at least when the single token is a "." or a "..."):

```
java.lang.RuntimeException: No roots in graph:
dep                 reln                gov                 
---                 ----                ---                 

Find where this graph was created and make sure you're adding roots.
	at edu.stanford.nlp.semgraph.SemanticGraph.getFirstRoot(SemanticGraph.java:790)
	at edu.stanford.nlp.semgraph.semgrex.SemgrexPattern.matcher(SemgrexPattern.java:231)
	at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.demoteQuantificationalModifiers(UniversalEnglishGrammaticalStructure.java:1724)
	at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.addEnhancements(UniversalEnglishGrammaticalStructure.java:871)
	at edu.stanford.nlp.trees.GrammaticalStructure.typedDependenciesEnhancedPlusPlus(GrammaticalStructure.java:924)
	at edu.stanford.nlp.semgraph.SemanticGraphFactory.makeFromTree(SemanticGraphFactory.java:249)
	at edu.stanford.nlp.semgraph.SemanticGraphFactory.generateEnhancedPlusPlusDependencies(SemanticGraphFactory.java:129)
	at edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations(ParserAnnotatorUtils.java:67)
	at edu.stanford.nlp.pipeline.ParserAnnotator.finishSentence(ParserAnnotator.java:297)
	at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:267)
	at edu.stanford.nlp.pipeline.SentenceAnnotator$AnnotatorProcessor.process(SentenceAnnotator.java:31)
	at edu.stanford.nlp.pipeline.SentenceAnnotator$AnnotatorProcessor.process(SentenceAnnotator.java:21)
	at edu.stanford.nlp.util.concurrent.MulticoreWrapper$CallableJob.call(MulticoreWrapper.java:255)
	at edu.stanford.nlp.util.concurrent.MulticoreWrapper$CallableJob.call(MulticoreWrapper.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
When I look into the argument given to `edu.stanford.nlp.semgraph.SemanticGraphFactory.makeFromTree` I see the following tree: `(ROOT (NP (: ...)))`, so there seems to be a root set after all. The problem only happens when `SemanticGraphFactory.generateEnhancedPlusPlusDependencies(gsf.newGrammaticalStructure(tree))` is called in `edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations`

**Comment by sebschu** [comment]
Can you paste the exact command that you ran? I just tried to reproduce this error but I didn't get an exception if I try to parse "." or "...".

**Comment by alex-j-j** [comment]
The parser is called within another framework. If I try to parse the respective strings by command line, the parser doesn't crash.
