### ISSUE TITLE
Error in training a model for stanford Pos tagger 

### ISSUE THREAD

**Issue by tedjbnd** [stanfordnlp/CoreNLP#355]
hi every body, 
i am trying to train the stanford pos tagger for arabic language, to do so i followed this tutorial [tutorial](http://www.florianboudin.org/wiki/doku.php?id=nlp_tools_related&DokuWiki=9d6b70b2ee818e600edc0359e3d7d1e8), but when i do so i am getting this error : 
`Exception in thread "main" edu.stanford.nlp.util.ReflectionLoading$ReflectionLoa
dingException: Error creating edu.stanford.nlp.optimization.OWLQNMinimizer
        at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLo
ading.java:40)
        at edu.stanford.nlp.maxent.CGRunner.solveL1(CGRunner.java:184)
        at edu.stanford.nlp.tagger.maxent.MaxentTagger.trainAndSaveModel(MaxentT
agger.java:1199)
        at edu.stanford.nlp.tagger.maxent.MaxentTagger.runTraining(MaxentTagger.
java:1254)
        at edu.stanford.nlp.tagger.maxent.MaxentTagger.main(MaxentTagger.java:18
87)
Caused by: edu.stanford.nlp.util.MetaClass$ClassCreationException: java.lang.Cla
ssNotFoundException: edu.stanford.nlp.optimization.OWLQNMinimizer
        at edu.stanford.nlp.util.MetaClass.createFactory(MetaClass.java:364)
        at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:381)
        at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLo
ading.java:38)
        ... 4 more
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.optimization.OWLQN
Minimizer
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at edu.stanford.nlp.util.MetaClass$ClassFactory.construct(MetaClass.java
:135)
        at edu.stanford.nlp.util.MetaClass$ClassFactory.<init>(MetaClass.java:20
2)
        at edu.stanford.nlp.util.MetaClass$ClassFactory.<init>(MetaClass.java:69
)
        at edu.stanford.nlp.util.MetaClass.createFactory(MetaClass.java:360)
        ... 6 more`

**Comment by J38** [comment]
Can you provide the command and the properties you used?

**Comment by tedjbnd** [comment]
this is the .props file i used 
`## tagger training invoked at Fri Feb 14 00:55:55 PST 2014 with arguments:
                   model = mytagger.tagger
                    arch = words(-2,2),order(1),prefix(6),suffix(6),unicodeshapes(1)
            wordFunction = 
               trainFile = models/mytagger.train
         closedClassTags = 
 closedClassTagThreshold = 40
 curWordMinFeatureThresh = 1
                   debug = false
             debugPrefix = 
            tagSeparator = /
                encoding = UTF-8
              iterations = 100
                    lang = arabic
    learnClosedClassTags = false
        minFeatureThresh = 3
           openClassTags = 
rareWordMinFeatureThresh = 3
          rareWordThresh = 5
                  search = owlqn
                    sgml = false
            sigmaSquared = 0.0
                   regL1 = 0.75
               tagInside = 
                tokenize = false
        tokenizerFactory = edu.stanford.nlp.process.WhitespaceTokenizer
        tokenizerOptions = 
                 verbose = false
          verboseResults = true
    veryCommonWordThresh = 250
                xmlInput = 
              outputFile = 
            outputFormat = slashTags
     outputFormatOptions = 
                nthreads = 1
`
this is the command i used : 
`java -mx1g -classpath stanford-postagger.jar edu.stanford.nlp.tagger.maxent.MaxentTagger -props mytagger.props`

**Comment by J38** [comment]
In your properties file if you change `search = owlqn` to `search = qn` does that change anything?

**Comment by J38** [comment]
The full details of what options you can use for `search` are here:

http://www-nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/tagger/maxent/MaxentTagger.html

The OWLQNMinimizer class is not included in our distribution, but it is what we use when we build our pos tagger models.  I will either add it to future distributions or update documentation to not use that as a default.

**Comment by tedjbnd** [comment]
Thanks a lot i changed the search to qn and all works fine for me
