### ISSUE TITLE
Exception when sending a HEAD request on /

### ISSUE THREAD

**Issue by julien-c** [stanfordnlp/CoreNLP#368]
```
Feb 28, 2017 6:30:37 PM sun.net.httpserver.ExchangeImpl sendResponseHeaders
WARNING: sendResponseHeaders: being invoked with a content length for a HEAD request
java.io.IOException: response headers not sent yet
        at sun.net.httpserver.PlaceholderOutputStream.checkWrap(ExchangeImpl.java:428)
        at sun.net.httpserver.PlaceholderOutputStream.write(ExchangeImpl.java:438)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:623)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by manning** [comment]
I think we have this fixed now. In HEAD and will be in the next release:

```
lamrockcafe:javanlp manning$ curl -I http://corenlp.run/
HTTP/1.1 200 OK
Access-control-allow-credentials-header: *
Access-control-allow-headers: *
Date: Thu, 25 May 2017 18:44:30 GMT
Access-control-allow-methods: GET,POST,PUT,DELETE,OPTIONS
Transfer-encoding: chunked
Access-control-allow-origin: *
Access-control-allow-credentials: true
```
