### ISSUE TITLE
Exceptions crushing

### ISSUE THREAD

**Issue by ranlandau** [stanfordnlp/CoreNLP#394]
Hi,

I often get the following exceptions (1 or 2) and then server stops responding.
is there a common solution for it?
I'm running the 3.7.0 following the dedicated server guide on Ubuntu.

> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "server-timer"
Exception in thread "Thread-3" Exception in thread "Thread-5" java.lang.OutOfMemoryError: Java heap space
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(java.base@9-internal/FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(java.base@9-internal/FutureTask.java:207)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:593)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.AuthFilter.doFilter(jdk.httpserver@9-internal/AuthFilter.java:82)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:80)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(jdk.httpserver@9-internal/ServerImpl.java:685)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.ServerImpl$Exchange.run(jdk.httpserver@9-internal/ServerImpl.java:657)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: java.lang.OutOfMemoryError: Java heap space
Exception in thread "Timer-0" java.lang.OutOfMemoryError: Java heap space
        at java.util.IdentityHashMap$EntrySet.iterator(java.base@9-internal/IdentityHashMap.java:1186)
        at edu.stanford.nlp.pipeline.AnnotatorPool$1$1.run(AnnotatorPool.java:49)
        at java.util.TimerThread.mainLoop(java.base@9-internal/Timer.java:555)
        at java.util.TimerThread.run(java.base@9-internal/Timer.java:505)
java.lang.OutOfMemoryError: Java heap space
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(java.base@9-internal/FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(java.base@9-internal/FutureTask.java:207)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:593)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.AuthFilter.doFilter(jdk.httpserver@9-internal/AuthFilter.java:82)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:80)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(jdk.httpserver@9-internal/ServerImpl.java:685)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.ServerImpl$Exchange.run(jdk.httpserver@9-internal/ServerImpl.java:657)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: java.lang.OutOfMemoryError: Java heap space
java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(java.base@9-internal/FutureTask.java:206)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:593)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.AuthFilter.doFilter(jdk.httpserver@9-internal/AuthFilter.java:82)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:80)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(jdk.httpserver@9-internal/ServerImpl.java:685)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.ServerImpl$Exchange.run(jdk.httpserver@9-internal/ServerImpl.java:657)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)

2)

> java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(java.base@9-internal/FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(java.base@9-internal/FutureTask.java:207)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:593)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.AuthFilter.doFilter(jdk.httpserver@9-internal/AuthFilter.java:82)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:80)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(jdk.httpserver@9-internal/ServerImpl.java:685)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.ServerImpl$Exchange.run(jdk.httpserver@9-internal/ServerImpl.java:657)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at edu.stanford.nlp.util.StringUtils.editDistance(StringUtils.java:1497)
        at edu.stanford.nlp.coref.statistical.FeatureExtractor.getFeatures(FeatureExtractor.java:318)
        at edu.stanford.nlp.coref.statistical.FeatureExtractor.extract(FeatureExtractor.java:128)
        at edu.stanford.nlp.coref.statistical.StatisticalCorefAlgorithm.runCoref(StatisticalCorefAlgorithm.java:96)
        at edu.stanford.nlp.coref.CorefSystem.annotate(CorefSystem.java:59)
        at edu.stanford.nlp.coref.CorefSystem.annotate(CorefSystem.java:47)
        at edu.stanford.nlp.pipeline.CorefAnnotator.annotate(CorefAnnotator.java:76)
        at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:75)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:605)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.lambda$handle$353(StanfordCoreNLPServer.java:575)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler$$Lambda$88/595261723.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
        ... 3 more
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(java.base@9-internal/FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(java.base@9-internal/FutureTask.java:207)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:593)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.AuthFilter.doFilter(jdk.httpserver@9-internal/AuthFilter.java:82)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:80)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(jdk.httpserver@9-internal/ServerImpl.java:685)
        at com.sun.net.httpserver.Filter$Chain.doFilter(jdk.httpserver@9-internal/Filter.java:77)
        at sun.net.httpserver.ServerImpl$Exchange.run(jdk.httpserver@9-internal/ServerImpl.java:657)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at edu.stanford.nlp.stats.ClassicCounter.incrementCount(ClassicCounter.java:232)
        at edu.stanford.nlp.coref.statistical.FeatureExtractor.getFeatures(FeatureExtractor.java:320)
        at edu.stanford.nlp.coref.statistical.FeatureExtractor.extract(FeatureExtractor.java:128)
        at edu.stanford.nlp.coref.statistical.StatisticalCorefAlgorithm.runCoref(StatisticalCorefAlgorithm.java:96)
        at edu.stanford.nlp.coref.CorefSystem.annotate(CorefSystem.java:59)
        at edu.stanford.nlp.coref.CorefSystem.annotate(CorefSystem.java:47)
        at edu.stanford.nlp.pipeline.CorefAnnotator.annotate(CorefAnnotator.java:76)
        at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:75)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:605)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.lambda$handle$353(StanfordCoreNLPServer.java:575)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler$$Lambda$88/595261723.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
        ... 3 more
[pool-1-thread-3] INFO CoreNLP - [/10.0.32.92:55592] API call w/annotators tokenize,ssplit,pos,lemma,ner,depparse,mention,coref
Exception in thread "Thread-5" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-1-thread-5" java.lang.OutOfMemoryError: Java heap space

**Comment by loretoparisi** [comment]
@ranlandau this is a Java **OutOfMemoryError** error i.e. your heap space is out. You must set your JVM xargs to increase memory like

```
-Xms2048m -Xmx4096m -XX:MaxPermSize=1024m -XX:MaxNewSize=1024m
```

where

```
-Xms<size>        set initial Java heap size
-Xmx<size>        set maximum Java heap size
-Xss<size>        set java thread stack size
```
