### ISSUE TITLE
Running Init Script with the -serverProperties flag

### ISSUE THREAD

**Issue by ssmi4th98** [stanfordnlp/CoreNLP#402]
StanfordCore: 2016-10.13

Using the script for starting up stanfordNLP I added the -serverProperties flag such that 

nohup su "$SERVER_USER" -c "/usr/local/bin/authbind --deep java -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir="$CORENLP_DIR" -cp "$CLASSPATH" -mx15g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 80 -serverProperties server.properties"

In the $CORENLP_DIR I have the server.properties file with 664 permissions.  Yet, when I kick off the service I get the following error:

Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException:  argsToProperties could not read properties file: server.properties
  at edu.standord.nlp.util.StringUtiols.argsToProperties(StringUtils.java:1014)
 ......
.......
Caused by: java.io.IOException: Unable to open "server.properties" as class path, filenaem or URL
  at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLorClasspathOrFileSystem(IOUtils.java:470)

**Comment by J38** [comment]
`server.properties` needs to be in the working directory where you are executing the `java` command.

The simplest fix to this is to put the absolute path of the `server.properties` file, or alternatively to put `server.properties` in the working directory...you can determine the working directory with `System.getProperty("user.dir")`

Note that `Djava.io.tmpdir="..."` is not setting the working directory.
