### ISSUE TITLE
Server API NullPointerException when text contains a single quote

### ISSUE THREAD

**Issue by tastyminerals** [stanfordnlp/CoreNLP#403]
I have downloaded **CoreNLP 3.7.0** (English) as well as English (KBP) models.
Started the server:
`java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer & disown`

Created a python **pycorenlp** script that takes a single sentence and queries CoreNLP server.
For example:
```python
from pycorenlp import StanfordCoreNLP

nlp = StanfordCoreNLP('http://localhost:9000')
text = "Carrie would sneak rides on her sister Dan 's bike . "
output = nlp.annotate(text, properties={
  'annotators': 'tokenize,ssplit,pos,lemma,ner,parse,mention,coref',
  'coref.algorithm': 'neural',
  'outputFormat': 'json'
  })
print output
```

However, I am getting `NullPointerException` error.
Looks like sentences containing a **single quote** `'` crash the pipeline. 
```
[pool-1-thread-4] INFO CoreNLP - [/0:0:0:0:0:0:0:1:49410] API call w/annotators tokenize,ssplit,pos,lemma,ner,parse,mention,coref
Carrie would sneak rides on her sister Dan 's bike .
[pool-2-thread-4] ERROR edu.stanford.nlp.pipeline.StanfordCoreNLP - Attempted to fetch annotator "parse" before the annotator pool was created!
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:603)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I have tried the same sentence with other third-party APIs as well, the error persists.

**Comment by J38** [comment]
I don't know what is causing this issue at the moment, but it is not related to single quotes being in the input text.

This is the same as this issue: https://github.com/stanfordnlp/CoreNLP/issues/381

**Comment by J38** [comment]
Could you provide more of the stack trace so I can see where in the code this error is happening?

**Comment by tastyminerals** [comment]
Indeed, this is strange. Have just tried python script and it worked with this sentence. Same Lua implementation failed however. Here is a full stack trace.

```java
[tastyminerals@dell-tasty rocstories-event-chains]$ th coreNLP.lua 
[pool-1-thread-3] INFO CoreNLP - [/127.0.0.1:60322] API call w/annotators tokenize,ssplit,pos,lemma,ner,parse,mention,coref
Carrie would sneak rides on her sister Dan 's bike .
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[pool-1-thread-3] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/srparser/englishSR.ser.gz ... done [19.5 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator mention
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
[pool-2-thread-3] ERROR edu.stanford.nlp.pipeline.StanfordCoreNLP - Attempted to fetch annotator "parse" before the annotator pool was created!
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:603)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at edu.stanford.nlp.coref.md.CorefMentionFinder.parse(CorefMentionFinder.java:645)
	at edu.stanford.nlp.coref.md.CorefMentionFinder.findSyntacticHead(CorefMentionFinder.java:536)
	at edu.stanford.nlp.coref.md.CorefMentionFinder.findHead(CorefMentionFinder.java:456)
	at edu.stanford.nlp.coref.md.RuleBasedCorefMentionFinder.findMentions(RuleBasedCorefMentionFinder.java:100)
	at edu.stanford.nlp.pipeline.MentionAnnotator.annotate(MentionAnnotator.java:102)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:605)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.lambda$handle$358(StanfordCoreNLPServer.java:585)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
/home/tastyminerals/torch/install/bin/luajit: /home/tastyminerals/torch/install/share/lua/5.1/corenlp.lua:55: Request to http://localhost:9000/?properties=%7b%22outputFormat%22%3a%22json%22%2c%22tokenize%2ewhitespace%22%3atrue%2c%22annotators%22%3a%22tokenize%2cssplit%2cpos%2clemma%2cner%2cparse%2cmention%2ccoref%22%2c%22coref%2ealgorithm%22%3a%22neural%22%7d failed for document:
1
Carrie would sneak rides on her sister Dan 's bike . 


Check your sever log for errors.
stack traceback:
	[C]: in function 'assert'
	/home/tastyminerals/torch/install/share/lua/5.1/corenlp.lua:55: in function 'annotate'
	coreNLP.lua:28: in main chunk
	[C]: in function 'dofile'
	...rals/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x55cd67cde8a0
```

**Comment by J38** [comment]
What I'm seeing from everyone who has reported this error is that coref mention detection is trying to access a parser, and this is causing the crash.

It may be the case that text with a single quote causes a corner case where the coref mention detection needs to create it's own parser.  But ultimately the bug has to do with multi-threading and they way annotators are stored.

**Comment by tastyminerals** [comment]
The bug is easily reproducible. 
```python
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from pycorenlp import StanfordCoreNLP

nlp = StanfordCoreNLP('http://localhost:9000')

text = """
Carrie would sneak rides on her sister Dan 's bike . 
"""

output = nlp.annotate(text, properties={
  'annotators': 'tokenize,ssplit,pos,lemma,ner,parse,mention,coref',
  'coref.algorithm': 'neural',
  'outputFormat': 'xml'
  })

print output
```

Sentence: 
>Carrie would sneak rides on her sister Dan bike . 

won't crash the pipeline. While:

>Carrie would sneak rides on her sister Dan 's bike . 

will.

**Comment by Motwani** [comment]
@tastyminerals Are you able to reproduce with the `'coref.algorithm': 'neural'` property? By using the standard deterministic model?

**Comment by tastyminerals** [comment]
*neural*, *statistical*, *deterministic* all fail with the same error.

**Comment by tastyminerals** [comment]
**neural**,**statistical** fail with the same error.
**deterministic** produces different error:
```
./coreNLP.py 
[pool-1-thread-3] INFO CoreNLP - [/0:0:0:0:0:0:0:1:50588] API call w/annotators tokenize,ssplit,pos,lemma,ner,parse,mention,coref
Carrie would sneak rides on her sister Dan 's bike .
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator mention
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
[pool-1-thread-3] ERROR edu.stanford.nlp.pipeline.CorefAnnotator - cannot create CorefAnnotator!
TOP ELEMENT: edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:38)
[pool-1-thread-3] ERROR edu.stanford.nlp.pipeline.CorefAnnotator - java.lang.RuntimeException: Error initializing coref system
  edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:38)
  edu.stanford.nlp.pipeline.CorefAnnotator.<init>(CorefAnnotator.java:50)
  edu.stanford.nlp.pipeline.AnnotatorImplementations.coref(AnnotatorImplementations.java:243)
  edu.stanford.nlp.pipeline.AnnotatorFactories$13.create(AnnotatorFactories.java:402)
  edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:152)
  edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)
  edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
  edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:145)
  edu.stanford.nlp.pipeline.StanfordCoreNLPServer.mkStanfordCoreNLP(StanfordCoreNLPServer.java:273)
  edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$500(StanfordCoreNLPServer.java:50)
  edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:583)
  com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
  sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
  com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
  sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
  com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
  sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
Caused by: class java.lang.IllegalArgumentException: No enum constant edu.stanford.nlp.coref.CorefProperties.CorefAlgorithmType.DETERMINISTIC
  java.lang.Enum.valueOf(Enum.java:238)
  edu.stanford.nlp.coref.CorefProperties$CorefAlgorithmType.valueOf(CorefProperties.java:20)
  edu.stanford.nlp.coref.CorefProperties.algorithm(CorefProperties.java:25)
  edu.stanford.nlp.coref.CorefAlgorithm.fromProps(CorefAlgorithm.java:24)
  edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:34)
  ...19 more
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing coref system
	at edu.stanford.nlp.pipeline.CorefAnnotator.<init>(CorefAnnotator.java:55)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.coref(AnnotatorImplementations.java:243)
	at edu.stanford.nlp.pipeline.AnnotatorFactories$13.create(AnnotatorFactories.java:402)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:152)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:145)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.mkStanfordCoreNLP(StanfordCoreNLPServer.java:273)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$500(StanfordCoreNLPServer.java:50)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:583)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error initializing coref system
	at edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:38)
	at edu.stanford.nlp.pipeline.CorefAnnotator.<init>(CorefAnnotator.java:50)
	... 18 more
Caused by: java.lang.IllegalArgumentException: No enum constant edu.stanford.nlp.coref.CorefProperties.CorefAlgorithmType.DETERMINISTIC
	at java.lang.Enum.valueOf(Enum.java:238)
	at edu.stanford.nlp.coref.CorefProperties$CorefAlgorithmType.valueOf(CorefProperties.java:20)
	at edu.stanford.nlp.coref.CorefProperties.algorithm(CorefProperties.java:25)
	at edu.stanford.nlp.coref.CorefAlgorithm.fromProps(CorefAlgorithm.java:24)
	at edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:34)
	... 19 more
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing coref system
```

**Comment by Motwani** [comment]
@tastyminerals I have the same errors with neural and deterministic model, but oddly the statistical model (the default model) runs fine without errors. The text I run contains both single and double quotes.

This is the error produced using `'coref.algorithm': 'neural'` .

```
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[pool-1-thread-3] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.8 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[pool-1-thread-3] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [2.3 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.9 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [2.3 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[pool-1-thread-3] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.6 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator mention
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.MentionAnnotator - Using mention detector type: rule
[pool-1-thread-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
[pool-1-thread-3] INFO edu.stanford.nlp.coref.neural.NeuralCorefAlgorithm - Loading coref model edu/stanford/nlp/models/coref/neural/english-model-default.ser.gz ... done [0.6 sec].
[pool-1-thread-3] INFO edu.stanford.nlp.coref.neural.NeuralCorefAlgorithm - Loading coref embeddings edu/stanford/nlp/models/coref/neural/english-embeddings.ser.gz ... done [3.6 sec].
[pool-2-thread-1] ERROR edu.stanford.nlp.pipeline.StanfordCoreNLP - Attempted to fetch annotator "parse" before the annotator pool was created!
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:644)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at edu.stanford.nlp.coref.md.CorefMentionFinder.parse(CorefMentionFinder.java:645)
	at edu.stanford.nlp.coref.md.CorefMentionFinder.findSyntacticHead(CorefMentionFinder.java:536)
	at edu.stanford.nlp.coref.md.CorefMentionFinder.findHead(CorefMentionFinder.java:456)
	at edu.stanford.nlp.coref.md.RuleBasedCorefMentionFinder.findMentions(RuleBasedCorefMentionFinder.java:100)
	at edu.stanford.nlp.pipeline.MentionAnnotator.annotate(MentionAnnotator.java:102)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:603)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.lambda$handle$0(StanfordCoreNLPServer.java:626)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**deterministic** produces the following error when run with `'coref.algorithm':'deterministic'`. It executes fairly quickly indicating that there is some problem in calling the model.

```
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[pool-1-thread-4] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.4 sec].
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[pool-1-thread-4] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [0.8 sec].
[pool-1-thread-4] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.0 sec].
[pool-1-thread-4] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.5 sec].
[pool-1-thread-4] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[pool-1-thread-4] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.2 sec].
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator mention
java.lang.IllegalArgumentException: No enum constant edu.stanford.nlp.coref.CorefProperties.CorefAlgorithmType.DETERMINISTIC
	at java.lang.Enum.valueOf(Enum.java:238)
	at edu.stanford.nlp.coref.CorefProperties$CorefAlgorithmType.valueOf(CorefProperties.java:20)
	at edu.stanford.nlp.coref.CorefProperties.algorithm(CorefProperties.java:25)
	at edu.stanford.nlp.coref.CorefProperties.useConstituencyParse(CorefProperties.java:44)
	at edu.stanford.nlp.coref.CorefProperties.mdType(CorefProperties.java:71)
	at edu.stanford.nlp.pipeline.MentionAnnotator.getMentionFinder(MentionAnnotator.java:130)
	at edu.stanford.nlp.pipeline.MentionAnnotator.<init>(MentionAnnotator.java:64)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.mention(AnnotatorImplementations.java:175)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$11(StanfordCoreNLP.java:507)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$constructAnnotatorPool$27(StanfordCoreNLP.java:577)
	at edu.stanford.nlp.util.Lazy$2.compute(Lazy.java:42)
	at edu.stanford.nlp.util.Lazy.get(Lazy.java:17)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:137)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:145)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.mkStanfordCoreNLP(StanfordCoreNLPServer.java:310)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$500(StanfordCoreNLPServer.java:50)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:624)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.MentionAnnotator - Error with building coref mention annotator!
[pool-1-thread-4] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator coref
[pool-1-thread-4] ERROR edu.stanford.nlp.pipeline.CorefAnnotator - cannot create CorefAnnotator!
TOP ELEMENT: edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:38)
[pool-1-thread-4] ERROR edu.stanford.nlp.pipeline.CorefAnnotator - java.lang.RuntimeException: Error initializing coref system
  edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:38)
  edu.stanford.nlp.pipeline.CorefAnnotator.<init>(CorefAnnotator.java:50)
  edu.stanford.nlp.pipeline.AnnotatorImplementations.coref(AnnotatorImplementations.java:191)
  edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$13(StanfordCoreNLP.java:509)
  edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$constructAnnotatorPool$27(StanfordCoreNLP.java:577)
  edu.stanford.nlp.util.Lazy$2.compute(Lazy.java:42)
  edu.stanford.nlp.util.Lazy.get(Lazy.java:17)
  edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:137)
  edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)
  edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
  edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:145)
  edu.stanford.nlp.pipeline.StanfordCoreNLPServer.mkStanfordCoreNLP(StanfordCoreNLPServer.java:310)
  edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$500(StanfordCoreNLPServer.java:50)
  edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:624)
  com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
  sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
  com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
  sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
  com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
  sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
Caused by: class java.lang.IllegalArgumentException: No enum constant edu.stanford.nlp.coref.CorefProperties.CorefAlgorithmType.DETERMINISTIC
  java.lang.Enum.valueOf(Enum.java:238)
  edu.stanford.nlp.coref.CorefProperties$CorefAlgorithmType.valueOf(CorefProperties.java:20)
  edu.stanford.nlp.coref.CorefProperties.algorithm(CorefProperties.java:25)
  edu.stanford.nlp.coref.CorefAlgorithm.fromProps(CorefAlgorithm.java:24)
  edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:34)
  ...22 more
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing coref system
	at edu.stanford.nlp.pipeline.CorefAnnotator.<init>(CorefAnnotator.java:55)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.coref(AnnotatorImplementations.java:191)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$13(StanfordCoreNLP.java:509)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$constructAnnotatorPool$27(StanfordCoreNLP.java:577)
	at edu.stanford.nlp.util.Lazy$2.compute(Lazy.java:42)
	at edu.stanford.nlp.util.Lazy.get(Lazy.java:17)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:137)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:145)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.mkStanfordCoreNLP(StanfordCoreNLPServer.java:310)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$500(StanfordCoreNLPServer.java:50)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:624)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error initializing coref system
	at edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:38)
	at edu.stanford.nlp.pipeline.CorefAnnotator.<init>(CorefAnnotator.java:50)
	... 21 more
Caused by: java.lang.IllegalArgumentException: No enum constant edu.stanford.nlp.coref.CorefProperties.CorefAlgorithmType.DETERMINISTIC
	at java.lang.Enum.valueOf(Enum.java:238)
	at edu.stanford.nlp.coref.CorefProperties$CorefAlgorithmType.valueOf(CorefProperties.java:20)
	at edu.stanford.nlp.coref.CorefProperties.algorithm(CorefProperties.java:25)
	at edu.stanford.nlp.coref.CorefAlgorithm.fromProps(CorefAlgorithm.java:24)
	at edu.stanford.nlp.coref.CorefSystem.<init>(CorefSystem.java:34)
	... 22 more

```

Have you tried using CoreNLP 3.6.0 ?

**Comment by tastyminerals** [comment]
@Motwani **CoreNLP 3.6.0** works without issues on the same example sentences. I am getting `java.util.concurrent.TimeoutException` if I attempt to shove too many sentences but I don't think it is related.

**Comment by J38** [comment]
This issue should be fixed now.
