### ISSUE TITLE
Bug: Using Neural Coref with ShiftReduce Parser

### ISSUE THREAD

**Issue by DerekTBrown** [stanfordnlp/CoreNLP#408]
Whenever I use the Neural Coref annotator with the ShiftReduce parser, I get the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Input word not tagged
	at edu.stanford.nlp.parser.shiftreduce.ShiftReduceParser.initialStateFromTaggedSentence(ShiftReduceParser.java:236)
	at edu.stanford.nlp.parser.shiftreduce.ShiftReduceParserQuery.parse(ShiftReduceParserQuery.java:54)
	at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:323)
	at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:254)
	at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:102)
	at edu.stanford.nlp.coref.md.CorefMentionFinder.parse(CorefMentionFinder.java:645)
	at edu.stanford.nlp.coref.md.CorefMentionFinder.findSyntacticHead(CorefMentionFinder.java:536)
	at edu.stanford.nlp.coref.md.CorefMentionFinder.findHead(CorefMentionFinder.java:456)
	at edu.stanford.nlp.coref.md.RuleBasedCorefMentionFinder.findMentions(RuleBasedCorefMentionFinder.java:100)
	at edu.stanford.nlp.pipeline.MentionAnnotator.annotate(MentionAnnotator.java:102)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:605)
	at annotation.DefaultPipeline.annotate(DefaultPipeline.java:25)
	at NLPeeps.getRelations(NLPeeps.java:53)
	at Ask.ask(Ask.java:13)
	at Ask.main(Ask.java:47)
```

**Comment by J38** [comment]
Hi I don't have a crash issue when I run using the shift reduce parser.

Could you show the sample text that causes this failure?  It appears to be a special case.

**Comment by DerekTBrown** [comment]
I have the error with the following Wikipedia article:

https://gist.github.com/DerekTBrown/1004d1046ea51b90dc0bff80233b6f6e

Here is my configuration:

```
	// Set Properties
		this.properties = PropertiesUtils.asProperties("annotators","tokenize,ssplit,pos,lemma,ner,parse,mention,coref,kbp");
		
		// Enable Shift-Reduce Parser
		this.properties.setProperty("parse.model", "edu/stanford/nlp/models/srparser/englishSR.ser.gz");
		
		// Split on Newlines
		this.properties.setProperty("ssplit.newlineIsSentenceBreak", "always");
		
		// Enable Neural CoRef
		this.properties.setProperty("coref.algorithm", "neural");
				
		// Create Pipeline
		this.pipeline = new StanfordCoreNLP(this.properties);
```

**Comment by J38** [comment]
@DerekTBrown were you still having this issue ?  If so could you please repost the text that caused the error, your current link no longer contains the text.

**Comment by DerekTBrown** [comment]
I ended up finding the issue,as I only encountered errors with input with whitespace.  Seems like the neural coref is more sensitive to this sort of thing.
