### ISSUE TITLE
java.lang.ClassNotFoundException: edu.stanford.nlp.parser.lexparser.ArabicUnknownWordModel error

### ISSUE THREAD

**Issue by Alshmowkh** [stanfordnlp/CoreNLP#424]
How can i fix ClassNotFoundException problem while reading arabicFactored.ser for loading model into LexicalizedParser?

please, help me.

thanks in advance.

**Comment by J38** [comment]
What jars are in your CLASSPATH and what command are you issuing that is causing this error?

**Comment by Alshmowkh** [comment]
Thanks J38 for responding timely.
The jar that is included to project library is stanford-parser.jar. As for the command:

 LexicalizedParser lp=LexicalizedParser.loadModel("arabicFactored.ser");

even if I only read the .ser file alone, the same error issues:

FileInputStream is = new FileInputStream(new File("arabicFactored.ser"));
        ObjectInputStream ois = new ObjectInputStream(is);
        Object o = ois.readObject();
The full error:

Exception in thread "main" java.lang.ClassNotFoundException: edu.stanford.nlp.parser.lexparser.ArabicUnknownWordModel
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501)
	at edu.stanford.nlp.parser.lexparser.BaseLexicon.readObject(BaseLexicon.java:731)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at corenlp02.ser01.main(ser01.java:22)
Java Result: 1

**Comment by J38** [comment]
Make sure to download version 3.7.0.

`edu.stanford.nlp.parser.lexparser.ArabicUnknownWordModel` should be in that jar.

You can see if a class is available in a jar with the command `jar -tf stanford-parser.jar`
