### ISSUE TITLE
regresstion test suite

### ISSUE THREAD

**Issue by ngrdtcs** [stanfordnlp/CoreNLP#444]
I would like to the procedure to run the regression test suite. Upon submitting the fix for one of the issues, integration fails quoting test failure for edu.stanford.nlp.pipeline.QuoteAnnotatorTest...

testMultiParagraphQuoteSingle(edu.stanford.nlp.pipeline.QuoteAnnotatorTest) Time elapsed: 0.008 sec <<< FAILURE!

junit.framework.AssertionFailedError: expected:<1> but was:<2>

at junit.framework.Assert.fail(Assert.java:57)

at junit.framework.Assert.failNotEquals(Assert.java:329)

at junit.framework.Assert.assertEquals(Assert.java:78)

at junit.framework.Assert.assertEquals(Assert.java:234)

at junit.framework.Assert.assertEquals(Assert.java:241)

at junit.framework.TestCase.assertEquals(TestCase.java:409)

at edu.stanford.nlp.pipeline.QuoteAnnotatorTest.assertInnerAnnotationValues(QuoteAnnotatorTest.java:471)

at edu.stanford.nlp.pipeline.QuoteAnnotatorTest.testMultiParagraphQuoteSingle(QuoteAnnotatorTest.java:383)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

May I know the procedure to run this test on our custom solution?

**Comment by J38** [comment]
If you go into this directory `javanlp/projects/core` and enter the command `mvn package` it will run the tests as a final step.
