### ISSUE TITLE
Stream Closed IOException in PTBTokenizer.java

### ISSUE THREAD

**Issue by shreshthamundra** [stanfordnlp/CoreNLP#460]
I am trying to run the code given at https://github.com/abisee/cnn-dailymail to tokenize cnn and dailymail data using PTBTokenizer. 

While executing this line: 
$ java edu.stanford.nlp.process.PTBTokenizer -ioFileList -preserveLines mapping.txt 

by calling subprocess.command(...) in python, I get the following exception:

Exception in thread "main" java.io.IOException: Stream closed
        at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116)
        at java.io.BufferedWriter.write(BufferedWriter.java:221)
        at java.io.Writer.write(Writer.java:157)
        at edu.stanford.nlp.process.PTBTokenizer.tokReader(PTBTokenizer.java:505)
        at edu.stanford.nlp.process.PTBTokenizer.tok(PTBTokenizer.java:450)
        at edu.stanford.nlp.process.PTBTokenizer.main(PTBTokenizer.java:813)

I looked at the file PTBTokenizer.java, and looks like the output file is not being closed anywhere and apparently that is causing this exception.

Could you please look into this issue?

Thanks!

**Comment by manning** [comment]
Agreed, this was clearly a bug that got introduced into the code over the last year.

For a practical solution for now, the easiest thing would be to use exactly the version mentioned in that repository: download version 3.7.0 from https://stanfordnlp.github.io/CoreNLP/history.html and it works without problems. 

But I will also fix the GitHub HEAD later today. The problem isn't that the output file _isn't_ being closed, it is that it _is_ being closed but due to faulty logic a new one wasn't being opened before more code was written.

**Comment by becxer** [comment]
Here got same error too!
