### ISSUE TITLE
CleanXmlAnnotator Exception

### ISSUE THREAD

**Issue by panx27** [stanfordnlp/CoreNLP#469]
For these two documents (from kbp 2016 source collection):
```
LDC2016E63_TAC_KBP_2016_Evaluation_Source_Corpus_V1.1/data/cmn/df/CMN_DF_000191_20160310_G00A0CFR9.xml
LDC2016E63_TAC_KBP_2016_Evaluation_Source_Corpus_V1.1/data/cmn/df/CMN_DF_000311_20160317_G00A0DM2Y.xml
```

I got the following exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Got a close tag a which does not match any open tag
        at edu.stanford.nlp.pipeline.CleanXmlAnnotator.process(CleanXmlAnnotator.java:832)
        at edu.stanford.nlp.pipeline.CleanXmlAnnotator.annotate(CleanXmlAnnotator.java:345)
        at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:599)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:609)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1172)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:945)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.run(StanfordCoreNLP.java:1274)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1345)
```

But it looks like 'tag a' is aligned perfect in these two documents.

**Comment by manning** [comment]
Yes, we discovered this problem over the summer too.... This has been fixed in HEAD for several months now, and will be fixed in v3.9.
