### ISSUE TITLE
How to use "batch processing" when training in CoreNLP?

### ISSUE THREAD

**Issue by rehmanursami** [stanfordnlp/CoreNLP#521]
I am trying to train this huge dataset of addresses (NER with 11 target classes). There are ~220 million lines in the training file, with each document consisting of 10 lines on average... I have access to 2 Titan X GPUs, but I still keep running into "Out of Memory" errors. 
So, Is there a way to batch process the training in CoreNLP? If yes, how to do that from command line?

I am using this command to run the training from command line. I have tried using up till 20Gb as the memory flag, but to no avail.
<java -mx7g -cp stanford-ner.jar edu.stanford.nlp.ie.crf.CRFClassifier -prop my.prop>

=================================
                              ERROR 
=================================
Exception in thread "main" java.lang.OutOfMemoryError
	at java.lang.AbstractStringBuilder.hugeCapacity(java.base@9-internal/AbstractStringBuilder.java:188)
	at java.lang.AbstractStringBuilder.newCapacity(java.base@9-internal/AbstractStringBuilder.java:180)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(java.base@9-internal/AbstractStringBuilder.java:147)
	at java.lang.AbstractStringBuilder.append(java.base@9-internal/AbstractStringBuilder.java:510)
	at java.lang.StringBuilder.append(java.base@9-internal/StringBuilder.java:141)
	at edu.stanford.nlp.objectbank.DelimitRegExIterator.<init>(DelimitRegExIterator.java:40)
	at edu.stanford.nlp.objectbank.DelimitRegExIterator$DelimitRegExIteratorFactory.getIterator(DelimitRegExIterator.java:122)
	at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter.getIterator(ColumnDocumentReaderAndWriter.java:58)
	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.setNextObject(ObjectBank.java:436)
	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.<init>(ObjectBank.java:415)
	at edu.stanford.nlp.objectbank.ObjectBank.iterator(ObjectBank.java:253)
	at edu.stanford.nlp.sequences.ObjectBankWrapper.iterator(ObjectBankWrapper.java:45)
	at edu.stanford.nlp.ie.crf.CRFClassifier.train(CRFClassifier.java:1585)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:765)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:753)
	at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3012)

**Comment by J38** [comment]
To the best of my knowledge there is not a way to train a CRF in the manner you are suggesting.  I think we train our model on 2.5 million lines.  Your best bet is to reduce the size of your training data.
