### ISSUE TITLE
When I train my own NER model, got the java.lang.OutofMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by xyjsjruiliu** [stanfordnlp/CoreNLP#523]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceede
d
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.StringBuilder.toString(Unknown Source)
        at edu.stanford.nlp.process.WordShapeClassifier.wordShapeChris2Short(Wor
dShapeClassifier.java:408)
        at edu.stanford.nlp.process.WordShapeClassifier.wordShapeChris2(WordShap
eClassifier.java:364)
        at edu.stanford.nlp.process.WordShapeClassifier.wordShape(WordShapeClass
ifier.java:180)
        at edu.stanford.nlp.sequences.ObjectBankWrapper.doBasicStuff(ObjectBankW
rapper.java:141)
        at edu.stanford.nlp.sequences.ObjectBankWrapper.processDocument(ObjectBa
nkWrapper.java:92)
        at edu.stanford.nlp.sequences.ObjectBankWrapper$WrappedIterator.next(Obj
ectBankWrapper.java:85)
        at edu.stanford.nlp.sequences.ObjectBankWrapper$WrappedIterator.next(Obj
ectBankWrapper.java:49)
        at edu.stanford.nlp.ie.crf.CRFClassifier.train(CRFClassifier.java:1585)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequence
Classifier.java:765)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequence
Classifier.java:753)
        at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3012)

**Comment by mcavdar** [comment]
Did you try adding an argument to increase java memory? (e.g. `-mx2g`)
If not, please see [this](https://nlp.stanford.edu/software/parser-faq.shtml#k).
