### ISSUE TITLE
Errors parsing Web Treebank to Universal Dependency

### ISSUE THREAD

**Issue by loganpeng1992** [stanfordnlp/CoreNLP#528]
Hi there,

I was using my Windows system to use both stanford-parser and coreNLP to parse Web Treebank (in bracket form to UD Conllx form)

The following code fails with stanford-parser with the following error:
C:\Users\hp\Documents\Georgetown\GUM\SD-UD_converter_test\stanford-parser-full-2017-06-09\stanford-parser-full-2017-06-09>(java -cp "*;" -mx1g edu.stanford.nlp.trees.ud.UniversalDependenciesConverter -treeFile  20070404104007AAY1Chs_ans.xml.tree  1>20070404104007AAY1Chs_ans.xml_UD.conllu )
Exception in thread "main" java.lang.RuntimeException: Error loading flags.readerAndWriter: 'edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter'
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.makeReaderAndWriter(AbstractSequenceClassifier.java:227)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.reinit(AbstractSequenceClassifier.java:194)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.<init>(AbstractSequenceClassifier.java:171)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.<init>(AbstractSequenceClassifier.java:139)
        at edu.stanford.nlp.ie.ClassifierCombiner.<init>(ClassifierCombiner.java:139)
        at edu.stanford.nlp.ie.NERClassifierCombiner.<init>(NERClassifierCombiner.java:128)
        at edu.stanford.nlp.ie.NERClassifierCombiner.createNERClassifierCombiner(NERClassifierCombiner.java:273)
        at edu.stanford.nlp.ie.NERClassifierCombiner.createNERClassifierCombiner(NERClassifierCombiner.java:212)
        at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter.addNERTags(UniversalDependenciesConverter.java:144)
        at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter.convertTreeToBasic(UniversalDependenciesConverter.java:68)
        at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter.access$000(UniversalDependenciesConverter.java:27)
        at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter$TreeToSemanticGraphIterator.next(UniversalDependenciesConverter.java:99)
        at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter$TreeToSemanticGraphIterator.next(UniversalDependenciesConverter.java:81)
        at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter.main(UniversalDependenciesConverter.java:196)
Caused by: edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter
        at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:40)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.makeReaderAndWriter(AbstractSequenceClassifier.java:225)
        ... 13 more
Caused by: edu.stanford.nlp.util.MetaClass$ClassCreationException: java.lang.ClassNotFoundException: edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter
        at edu.stanford.nlp.util.MetaClass.createFactory(MetaClass.java:364)
        at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:381)
        at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:38)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at edu.stanford.nlp.util.MetaClass$ClassFactory.construct(MetaClass.java:135)
        at edu.stanford.nlp.util.MetaClass$ClassFactory.<init>(MetaClass.java:202)
        at edu.stanford.nlp.util.MetaClass$ClassFactory.<init>(MetaClass.java:69)
        at edu.stanford.nlp.util.MetaClass.createFactory(MetaClass.java:360)
        ... 16 more

It somehow runs with coreNLP but takes 10 seconds per file due to loadings:
>java -mx1024m -cp "*;" edu.stanford.nlp.trees.ud.UniversalDependenciesConverter -treeFile 20070404104007AAY1Chs_ans.xml.tree
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [7.2 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [2.1 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [5.1 sec].
[main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
1       where   where   ADV     WRB     _       4       advmod  _       _
2       can     can     AUX     MD      _       4       aux     _       _
3       I       I       PRON    PRP     _       4       nsubj   _       _

I would like to get some help with this issue (hopefully it could run on both stanford-parser and coreNLP).

Thank you all.
Best,
Logan Peng

**Comment by J38** [comment]
You need to include the NER classes to run this.  So basically you need the full Stanford CoreNLP jar or you need to add the NER standalone distribution to your CLASSPATH.

You need to put all of the trees into one file.  The file should be in PTB format.
