### ISSUE TITLE
edu.stanford.nlp.pipeline.ChineseSegmenterAnnotator.loadModel(String,Properties) failed

### ISSUE THREAD

**Issue by zzyyabc** [stanfordnlp/CoreNLP#531]
my problem is that ,I have downloaded the standford-corenlp-3.7.0-chinese-models.jar by maven,but when I run my project ,I meet the error as follow:

> Caused by: edu.stanford.nlp.util.MetaClass$ClassCreationException: MetaClass couldn't create public edu.stanford.nlp.pipeline.ChineseSegmenterAnnotator(java.lang.String,java.util.Properties) with args [segment, {segment.sighanPostProcessing=true, coref.input.type=raw, segment.serDictionary=edu/stanford/nlp/models/segmenter/chinese/dict-chris6.ser.gz, ner.language=chinese, regexner.noDefaultOverwriteLabels=CITY, coref.path.word2vec=, tokenize.language=zh, coref.defaultPronounAgreement=true, kbp.tokensregex=edu/stanford/nlp/models/kbp/chinese/tokensregex, ner.useSUTime=false, customAnnotatorClass.segment=edu.stanford.nlp.pipeline.ChineseSegmenterAnnotator, coref.md.type=RULE, coref.postprocessing=true, kbp.model=none]
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:237)
	at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:382)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.custom(AnnotatorImplementations.java:188)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$1.create(StanfordCoreNLP.java:562)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:152)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:170)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:162)
	at com.nlp.job.Standalone.<init>(Standalone.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 44 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:233)
	... 57 more
Caused by: java.lang.RuntimeException: java.io.IOException: Unable to open "edu/stanford/nlp/models/segmenter/chinese/ctb.gz" as class path, filename or URL
	at edu.stanford.nlp.pipeline.ChineseSegmenterAnnotator.loadModel(ChineseSegmenterAnnotator.java:105)
	at edu.stanford.nlp.pipeline.ChineseSegmenterAnnotator.<init>(ChineseSegmenterAnnotator.java:83)
	... 62 more
Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/segmenter/chinese/ctb.gz" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:470)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1492)
	at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2963)
	at edu.stanford.nlp.pipeline.ChineseSegmenterAnnotator.loadModel(ChineseSegmenterAnnotator.java:101)
	... 63 more

this is my corenlp.properties : 

> # Pipeline options - lemma is no-op for Chinese but currently needed because coref demands it (bad old requirements system)
#annotators = tokenize, ssplit, pos, lemma, ner, parse, depparse, relation
annotators = segment, ssplit, pos, lemma, ner

# segment
customAnnotatorClass.segment = edu.stanford.nlp.pipeline.ChineseSegmenterAnnotator

tokenize.language = zh

segment.model =edu/stanford/nlp/models/segmenter/chinese/ctb.gz
segment.sighanCorporaDict = edu/stanford/nlp/models/segmenter/chinese
segment.serDictionary = edu/stanford/nlp/models/segmenter/chinese/dict-chris6.ser.gz
segment.sighanPostProcessing = true
...

I guess my problem maybe caused by the path of segment.model,but I just copy the tutorial of
Standford-NLP,properties ,so I don't know how to make it   .

**Comment by soap-tastes-ok** [comment]
I'm stuck with the same issue for quite a while now.. Anyone please help?

**Comment by J38** [comment]
Just use the properties in the `StanfordCoreNLP-chinese.properties` file (and use version 3.9.2).  You don't need to make a custom annotator, the tokenize annotator will run the Chinese segmenter if you use the properties in that file.

**Comment by yangle9567** [comment]
do you have file named by ctb.gz? could you send it  to me ?
