### ISSUE TITLE
KBP relation extraction breaking with -ssplit.eolonly (ProtobufAnnotationSerializer issue)

### ISSUE THREAD

**Issue by J38** [stanfordnlp/CoreNLP#568]
Command:

`java -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,regexner,entitymentions,parse,mention,coref,kbp -ssplit.eolonly -file missing-relations.txt -outputFormat text`

Error:

```
Exception in thread "main" java.lang.NullPointerException
	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.fromProto(ProtobufAnnotationSerializer.java:1556)
	at edu.stanford.nlp.simple.Document.asAnnotation(Document.java:1064)
	at edu.stanford.nlp.simple.Sentence.asCoreMap(Sentence.java:1089)
	at edu.stanford.nlp.ie.KBPTokensregexExtractor.classify(KBPTokensregexExtractor.java:88)
	at edu.stanford.nlp.ie.KBPEnsembleExtractor.classify(KBPEnsembleExtractor.java:61)
	at edu.stanford.nlp.pipeline.KBPAnnotator.annotate(KBPAnnotator.java:430)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:652)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:662)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$73/102227435.accept(Unknown Source)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1231)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1002)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.run(StanfordCoreNLP.java:1336)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1407)
```

**Comment by aimerlavie** [comment]
This seems a larger issue. I tested kbp on larger datasets and got many errors due to ProtobufAnnotationSerializer that could often be traced back to the "fromProto(CoreNLPProtos.SentenceFragment fragment, SemanticGraph tree)" method.  
The problem seems to be that the stream over the fragmentTree concurrently modifies the data structure. I solved the problem by having the changes done on a soft copy of the fragmentTree:
`// Apparently this sometimes screws up the tree

    SemanticGraph fragmentTree2 = fragmentTree.makeSoftCopy();

    fragmentTree.vertexSet().stream()

        .filter(vertex -> fragmentTree.getFirstRoot() != vertex &&

            tree.getFirstRoot() != vertex &&

            !fragmentTree.incomingEdgeIterable(vertex).iterator().hasNext())

        .forEach(vertex -> {
          SemanticGraphEdge edge = tree.incomingEdgeIterable(vertex).iterator().next();

          fragmentTree2.addEdge(fragmentTree2.getFirstRoot(), edge.getDependent(), edge.getRelation(),

              edge.getWeight(), edge.isExtra());

        });
    // Return the fragment

    //noinspection SimplifiableConditionalExpression

    return new SentenceFragment(fragmentTree2,

        fragment.hasAssumedTruth() ? fragment.getAssumedTruth() : true,
        false)

        .changeScore(fragment.hasScore() ? fragment.getScore() : 1.0);`

Since, for some reason, the (de)serialization of the annotation is an integral part of KBP, it would be nice to have that fixed, rather than using a fixed copy of the ProtobufAnnotationSerializer. 
Thanks a bunch.
