### ISSUE TITLE
error message when trying to parse nonsensical datetime

### ISSUE THREAD

**Issue by brendano** [stanfordnlp/CoreNLP#57]
I see this a lot when parsing gigaword.

```
java.lang.NumberFormatException: For input string: "1438143814381434"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.valueOf(Integer.java:766)
        at edu.stanford.nlp.ie.pascal.ISODateInstance.extractDay(ISODateInstance.java:1107)
        at edu.stanford.nlp.ie.pascal.ISODateInstance.extractFields(ISODateInstance.java:398)
        at edu.stanford.nlp.ie.pascal.ISODateInstance.<init>(ISODateInstance.java:82)
        at edu.stanford.nlp.ie.QuantifiableEntityNormalizer.normalizedDateString(QuantifiableEntityNormalizer.java:363)
        at edu.stanford.nlp.ie.QuantifiableEntityNormalizer.normalizedDateString(QuantifiableEntityNormalizer.java:338)
        at edu.stanford.nlp.ie.QuantifiableEntityNormalizer.processEntity(QuantifiableEntityNormalizer.java:1025)
        at edu.stanford.nlp.ie.QuantifiableEntityNormalizer.addNormalizedQuantitiesToEntities(QuantifiableEntityNormalizer.java:1374)
        at edu.stanford.nlp.ie.NERClassifierCombiner.classifyWithGlobalInformation(NERClassifierCombiner.java:133)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifySentenceWithGlobalInformation(AbstractSequenceClassifier.java:327)
        at edu.stanford.nlp.pipeline.NERCombinerAnnotator.doOneSentence(NERCombinerAnnotator.java:148)
        at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:95)
        at edu.stanford.nlp.pipeline.NERCombinerAnnotator.annotate(NERCombinerAnnotator.java:137)
        at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:68)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:411)
```

**Comment by AngledLuffa** [comment]
Please give an example text (minimal, if possible)

**Comment by brendano** [comment]
Gigaword version 5, docid AFP_ENG_20020604.0312

ah, it's the line of numbers one of the lines there.  i've seen instances of this bug at least a year ago fyi.

```
"Palm oil prices in ringgit per tonne at the close of trade Tuesday on\nMalaysia's Derivatives Exchange:\n\nAverage prices for     June   July   Aug   Sept  Oct   Nov\n\ncrude palm oil         1450   1452   1450  1450  1450  1440\n\nThe Malaysian crude palm oil market traded higher."
```

**Comment by manning** [comment]
This make sense. Looks like we're just getting integer overflow. We should fix this. (Longer term, the plan is to get rid of this code, and just use SUTime.

**Comment by manning** [comment]
I think this was fixed a while ago. I can't reproduce it now. So closing this issue.

**Comment by demongolem** [comment]
Chris, can you tell which version the fix was applied in?  I am using an older version (out of necessity I think it is 3.4.2) and I see the exact same issue for the String "200912031000" (which is supposed to be Dec 3, 2009 at 10:00:00).
