### ISSUE TITLE
Error while trying to load the StanfordCoreNLP module

### ISSUE THREAD

**Issue by kmr0877** [stanfordnlp/CoreNLP#582]
while trying to run the following i got the below error.Couldnt figure out whats the issue with it.If its with the python version syntax error or any thing else.It would be great if someone who knows this can help me fix this.Thanks for your time
>>> from corenlp import *
>>> corenlp = StanfordCoreNLP()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "corenlp.py", line 163, in __init__
    self.corenlp = pexpect.spawn(start_corenlp)
  File "/usr/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 194, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 267, in _spawn
    'executable: %s.' % self.command)
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: java.

**Comment by gangeli** [comment]
It looks like you don't have java installed, or don't have it in your path.
