### ISSUE TITLE
Basic Example From Install Page Not Working

### ISSUE THREAD

**Issue by dborncamp** [stanfordnlp/CoreNLP#595]
I went to the download page and downloaded `stanford-corenlp-full-2017-06-09` as the instructions on the [download page](https://stanfordnlp.github.io/CoreNLP/download.html#steps-to-setup-from-the-official-release) said. I set up my class path using:
```
for file in `find . -name "*.jar"`; do export
CLASSPATH="$CLASSPATH:`realpath $file`"; done
```

Made an input text file that contained: `the quick brown fox jumped over the lazy dog` per the instructions. But when I ran it I got this, any idea where I went wrong in the setup?

```
bash$ java -mx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat json -file input.txt --add-modules java.xml.bind --add-modules java.se.ee
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: StanfordCoreNLP.properties ... not found.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: edu/stanford/nlp/pipeline/StanfordCoreNLP.properties ... found.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.0 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.5 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.8 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.7 sec].
[main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
Exception in thread "main" edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl
	at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:38)
	at edu.stanford.nlp.time.TimeExpressionExtractorFactory.create(TimeExpressionExtractorFactory.java:60)
	at edu.stanford.nlp.time.TimeExpressionExtractorFactory.createExtractor(TimeExpressionExtractorFactory.java:43)
	at edu.stanford.nlp.ie.regexp.NumberSequenceClassifier.<init>(NumberSequenceClassifier.java:86)
	at edu.stanford.nlp.ie.NERClassifierCombiner.<init>(NERClassifierCombiner.java:138)
	at edu.stanford.nlp.pipeline.NERCombinerAnnotator.<init>(NERCombinerAnnotator.java:131)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.ner(AnnotatorImplementations.java:68)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$5(StanfordCoreNLP.java:545)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$constructAnnotatorPool$30(StanfordCoreNLP.java:624)
	at edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:126)
	at edu.stanford.nlp.util.Lazy.get(Lazy.java:31)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:149)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:494)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:201)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:194)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:181)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1413)
Caused by: edu.stanford.nlp.util.MetaClass$ClassCreationException: MetaClass couldn't create public edu.stanford.nlp.time.TimeExpressionExtractorImpl(java.lang.String,java.util.Properties) with args [sutime, {}]
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:237)
	at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:382)
	at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:36)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:233)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at de.jollyday.util.CalendarUtil.<init>(CalendarUtil.java:42)
	at de.jollyday.HolidayManager.<init>(HolidayManager.java:66)
	at de.jollyday.impl.DefaultHolidayManager.<init>(DefaultHolidayManager.java:46)
	at edu.stanford.nlp.time.JollyDayHolidays$MyXMLManager.<init>(JollyDayHolidays.java:148)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:558)
	at de.jollyday.caching.HolidayManagerValueHandler.instantiateManagerImpl(HolidayManagerValueHandler.java:60)
	at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:41)
	at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:13)
	at de.jollyday.util.Cache.get(Cache.java:51)
	at de.jollyday.HolidayManager.createManager(HolidayManager.java:168)
	at de.jollyday.HolidayManager.getInstance(HolidayManager.java:148)
	at edu.stanford.nlp.time.JollyDayHolidays.init(JollyDayHolidays.java:57)
	at edu.stanford.nlp.time.Options.<init>(Options.java:90)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.init(TimeExpressionExtractorImpl.java:44)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.<init>(TimeExpressionExtractorImpl.java:39)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 42 more
```

Using Java version:

```
bash$ java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

On Mac OSX 10.13.2

**Comment by J38** [comment]
You should set up your CLASSPATH this way: `export CLASSPATH=stanford-corenlp-full-2017-06-09/*:`

**Comment by dborncamp** [comment]
@J38 I still get the same error when doing that. Is there a dependency that I need to get? Or does this only work in Java 1.8?

``` bash
bash 4% export CLASSPATH=~/playpen/stanford/stanford-corenlp-full-2017-06-09/*
bash 5% echo $CLASSPATH
/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/BasicPipelineExample.java /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/CoreNLP-to-HTML.xsl /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/LIBRARY-LICENSES /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/LICENSE.txt /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/Makefile /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/README.txt /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/SemgrexDemo.java /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/ShiftReduceDemo.java /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/StanfordCoreNlpDemo.java /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/StanfordDependenciesManual.pdf /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/build.xml /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/corenlp.sh /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/ejml-0.23-src.zip /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/ejml-0.23.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/input.txt /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/input.txt.xml /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/javax.json-api-1.0-sources.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/javax.json.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/joda-time-2.9-sources.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/joda-time.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/jollyday-0.4.9-sources.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/jollyday.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/patterns /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/pom.xml /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/protobuf.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/slf4j-api.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/slf4j-simple.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/stanford-corenlp-3.8.0-javadoc.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/stanford-corenlp-3.8.0-models.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/stanford-corenlp-3.8.0-sources.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/stanford-corenlp-3.8.0.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/sutime /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/tokensregex /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/xom-1.2.10-src.jar /Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/xom.jar
bash 6% java -mx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat json -file input.txt
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: StanfordCoreNLP.properties ... not found.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Searching for resource: edu/stanford/nlp/pipeline/StanfordCoreNLP.properties ... found.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.9 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.5 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.7 sec].
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.8 sec].
[main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
Exception in thread "main" edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl
	at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:40)
	at edu.stanford.nlp.time.TimeExpressionExtractorFactory.create(TimeExpressionExtractorFactory.java:57)
	at edu.stanford.nlp.time.TimeExpressionExtractorFactory.createExtractor(TimeExpressionExtractorFactory.java:38)
	at edu.stanford.nlp.ie.regexp.NumberSequenceClassifier.<init>(NumberSequenceClassifier.java:86)
	at edu.stanford.nlp.ie.NERClassifierCombiner.<init>(NERClassifierCombiner.java:136)
	at edu.stanford.nlp.pipeline.NERCombinerAnnotator.<init>(NERCombinerAnnotator.java:91)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.ner(AnnotatorImplementations.java:70)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$44(StanfordCoreNLP.java:498)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getDefaultAnnotatorPool$65(StanfordCoreNLP.java:533)
	at edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:118)
	at edu.stanford.nlp.util.Lazy.get(Lazy.java:31)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:146)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:447)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:150)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:146)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:133)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1344)
Caused by: edu.stanford.nlp.util.MetaClass$ClassCreationException: MetaClass couldn't create public edu.stanford.nlp.time.TimeExpressionExtractorImpl(java.lang.String,java.util.Properties) with args [sutime, {}]
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:237)
	at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:382)
	at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:38)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:233)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at de.jollyday.util.CalendarUtil.<init>(CalendarUtil.java:42)
	at de.jollyday.HolidayManager.<init>(HolidayManager.java:66)
	at de.jollyday.impl.DefaultHolidayManager.<init>(DefaultHolidayManager.java:46)
	at edu.stanford.nlp.time.JollyDayHolidays$MyXMLManager.<init>(JollyDayHolidays.java:148)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:558)
	at de.jollyday.caching.HolidayManagerValueHandler.instantiateManagerImpl(HolidayManagerValueHandler.java:60)
	at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:41)
	at de.jollyday.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:13)
	at de.jollyday.util.Cache.get(Cache.java:51)
	at de.jollyday.HolidayManager.createManager(HolidayManager.java:168)
	at de.jollyday.HolidayManager.getInstance(HolidayManager.java:148)
	at edu.stanford.nlp.time.JollyDayHolidays.init(JollyDayHolidays.java:57)
	at edu.stanford.nlp.time.Options.<init>(Options.java:90)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.init(TimeExpressionExtractorImpl.java:44)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.<init>(TimeExpressionExtractorImpl.java:39)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 42 more```

**Comment by J38** [comment]
You definitely need Java 1.8.

**Comment by dborncamp** [comment]
@J38 Thanks for that! I installed java 1.8 but am still having issues (at least they are different issues than before...) any ideas what I did wrong?:

```bash
bash 7% javac BasicPipelineExample1.java
BasicPipelineExample1.java:1: error: package edu.stanford.nlp.pipeline does not exist
import edu.stanford.nlp.pipeline.*;
^
BasicPipelineExample1.java:2: error: package edu.stanford.nlp.ling does not exist
import edu.stanford.nlp.ling.*;
^
BasicPipelineExample1.java:3: error: package edu.stanford.nlp.util does not exist
import edu.stanford.nlp.util.CoreMap;
                            ^
BasicPipelineExample1.java:4: error: package edu.stanford.nlp.trees does not exist
import edu.stanford.nlp.trees.Tree;
                             ^
BasicPipelineExample1.java:5: error: package edu.stanford.nlp.trees does not exist
import edu.stanford.nlp.trees.TreeCoreAnnotations;
                             ^
BasicPipelineExample1.java:6: error: package edu.stanford.nlp.trees.TreeCoreAnnotations does not exist
import edu.stanford.nlp.trees.TreeCoreAnnotations.TreeAnnotation;
                                                 ^
BasicPipelineExample1.java:7: error: package edu.stanford.nlp.ling.CoreAnnotations does not exist
import edu.stanford.nlp.ling.CoreAnnotations.TextAnnotation;
                                            ^
BasicPipelineExample1.java:8: error: package edu.stanford.nlp.ling.CoreAnnotations does not exist
import edu.stanford.nlp.ling.CoreAnnotations.PartOfSpeechAnnotation;
                                            ^
BasicPipelineExample1.java:9: error: package edu.stanford.nlp.ling.CoreAnnotations does not exist
import edu.stanford.nlp.ling.CoreAnnotations.LemmaAnnotation;
                                            ^
BasicPipelineExample1.java:10: error: package edu.stanford.nlp.ling.CoreAnnotations does not exist
import edu.stanford.nlp.ling.CoreAnnotations.NamedEntityTagAnnotation;
                                            ^
BasicPipelineExample1.java:21: error: cannot find symbol
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
        ^
  symbol:   class StanfordCoreNLP
  location: class BasicPipelineExample1
BasicPipelineExample1.java:21: error: cannot find symbol
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
                                       ^
  symbol:   class StanfordCoreNLP
  location: class BasicPipelineExample1
BasicPipelineExample1.java:27: error: cannot find symbol
        Annotation document = new Annotation(text);
        ^
  symbol:   class Annotation
  location: class BasicPipelineExample1
BasicPipelineExample1.java:27: error: cannot find symbol
        Annotation document = new Annotation(text);
                                  ^
  symbol:   class Annotation
  location: class BasicPipelineExample1
BasicPipelineExample1.java:38: error: package CoreAnnotations does not exist
 	for (CoreMap sentence: document.get(CoreAnnotations.SentencesAnnotation.class)) {
 	                                                   ^
BasicPipelineExample1.java:38: error: cannot find symbol
 	for (CoreMap sentence: document.get(CoreAnnotations.SentencesAnnotation.class)) {
 	     ^
  symbol:   class CoreMap
  location: class BasicPipelineExample1
BasicPipelineExample1.java:40: error: cannot find symbol
 	    Tree tree = sentence.get(TreeAnnotation.class);
 	    ^
  symbol:   class Tree
  location: class BasicPipelineExample1
BasicPipelineExample1.java:40: error: cannot find symbol
 	    Tree tree = sentence.get(TreeAnnotation.class);
 	                             ^
  symbol:   class TreeAnnotation
  location: class BasicPipelineExample1
BasicPipelineExample1.java:42: error: package CoreAnnotations does not exist
 	    for (CoreLabel token: sentence.get(CoreAnnotations.TokensAnnotation.class)) {
 	                                                      ^
BasicPipelineExample1.java:42: error: cannot find symbol
 	    for (CoreLabel token: sentence.get(CoreAnnotations.TokensAnnotation.class)) {
 	         ^
  symbol:   class CoreLabel
  location: class BasicPipelineExample1
BasicPipelineExample1.java:44: error: cannot find symbol
 	    String tokenText = token.get(TextAnnotation.class);
 	                                 ^
  symbol:   class TextAnnotation
  location: class BasicPipelineExample1
BasicPipelineExample1.java:45: error: cannot find symbol
 	    String tokenPOS = token.get(PartOfSpeechAnnotation.class);
 	                                ^
  symbol:   class PartOfSpeechAnnotation
  location: class BasicPipelineExample1
BasicPipelineExample1.java:46: error: cannot find symbol
 	    String tokenLemma = token.get(LemmaAnnotation.class);
 	                                  ^
  symbol:   class LemmaAnnotation
  location: class BasicPipelineExample1
BasicPipelineExample1.java:47: error: cannot find symbol
 	    String tokenNE = token.get(NamedEntityTagAnnotation.class);
 	                               ^
  symbol:   class NamedEntityTagAnnotation
  location: class BasicPipelineExample1
24 errors
bash 8% echo $CLASSPATH
:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/CopyLibs/org-netbeans-modules-java-j2seproject-copylibstask.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/javax.json-api-1.0-sources.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/ejml-0.23.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/slf4j-api.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/stanford-corenlp-3.8.0-models.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/protobuf.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/joda-time.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/joda-time-2.9-sources.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/xom-1.2.10-src.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/xom.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/javax.json.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/stanford-corenlp-3.8.0-javadoc.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/jollyday.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/stanford-corenlp-3.8.0-sources.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/slf4j-simple.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/stanford-corenlp-3.8.0.jar:/Users/dborncamp/playpen/stanford/stanford-corenlp-full-2017-06-09/jollyday-0.4.9-sources.jar
bash 9% javac -version
javac 1.8.0_152
```

The code for BasicExample1.java:
``` java
import edu.stanford.nlp.pipeline.*;
import edu.stanford.nlp.ling.*;
import edu.stanford.nlp.util.CoreMap;
import edu.stanford.nlp.trees.Tree;
import edu.stanford.nlp.trees.TreeCoreAnnotations;
import edu.stanford.nlp.trees.TreeCoreAnnotations.TreeAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.TextAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.PartOfSpeechAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.LemmaAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations.NamedEntityTagAnnotation;
import java.util.*;


public class BasicPipelineExample1 {

    public static void main(String[] args) {

        // creates a StanfordCoreNLP object, with POS tagging, lemmatization, NER, parsing, and coreference resolution
        Properties props = new Properties();
        props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

        // read some text in the text variable
        String text = "This is a test of the Stanford CoreNLP Code. Stanford makes some interesting code!";

        // create an empty Annotation just with the given text
        Annotation document = new Annotation(text);

        // run all Annotators on this text
        pipeline.annotate(document);
	System.out.println("Almost done!!");
 	// demonstrate typical usage

	ArrayList<String> textList = new ArrayList<String>();
	ArrayList<String> posList = new ArrayList<String>();
	ArrayList<String> lemmaList = new ArrayList<String>();
	ArrayList<String> namedList = new ArrayList<String>();
 	for (CoreMap sentence: document.get(CoreAnnotations.SentencesAnnotation.class)) {
 	    // get the tree for the sentence
 	    Tree tree = sentence.get(TreeAnnotation.class);
 	    // get the tokens for the sentence and iterate over them
 	    for (CoreLabel token: sentence.get(CoreAnnotations.TokensAnnotation.class)) {
 	    // get token attributes
 	    String tokenText = token.get(TextAnnotation.class);
 	    String tokenPOS = token.get(PartOfSpeechAnnotation.class);
 	    String tokenLemma = token.get(LemmaAnnotation.class);
 	    String tokenNE = token.get(NamedEntityTagAnnotation.class);

	    textList.add(tokenText);
	    posList.add(tokenPOS);
	    lemmaList.add(tokenLemma);
	    namedList.add(tokenNE);
	    }
	}

	System.out.println("");
	System.out.println("Input text: " + text);
	System.out.println("Parsed text:");
	System.out.println(textList);
	System.out.println("Parts of Speach:");
	System.out.println(posList);
	System.out.println("Lemma Annotation:");
	System.out.println(lemmaList);
	System.out.println("Named Entity:");
	System.out.println(namedList);
	System.out.println("Done");
    }

}
```

**Comment by alajlan66** [comment]
Did you find a solution? because I have the same issue that you have in the first place

**Comment by dborncamp** [comment]
My solution was to run it in a jdk1.8 docker container. Still not working locally so it is probably something to do with the environment.
