### ISSUE TITLE
Not Training For Multiple Files

### ISSUE THREAD

**Issue by Varun-Epi** [stanfordnlp/CoreNLP#606]
TrainFileList flag option is not working in stanford-ner version 3.8

Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.FileNotFoundException: ['sample_2113.conll'] (No such file 
or directory)
        at edu.stanford.nlp.io.IOUtils.inputStreamFromFile(IOUtils.java:519)
        at edu.stanford.nlp.io.IOUtils.readerFromFile(IOUtils.java:560)
        at edu.stanford.nlp.objectbank.ReaderIteratorFactory$ReaderIterator.setNextObject(ReaderIteratorFactory.java:189)
        at edu.stanford.nlp.objectbank.ReaderIteratorFactory$ReaderIterator.<init>(ReaderIteratorFactory.java:161)
        at edu.stanford.nlp.objectbank.ResettableReaderIteratorFactory.iterator(ResettableReaderIteratorFactory.java:98)
        at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.<init>(ObjectBank.java:414)
        at edu.stanford.nlp.objectbank.ObjectBank.iterator(ObjectBank.java:253)
        at edu.stanford.nlp.sequences.ObjectBankWrapper.iterator(ObjectBankWrapper.java:45)
        at edu.stanford.nlp.ie.crf.CRFClassifier.train(CRFClassifier.java:1585)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:780)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:751)
        at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3012)
Caused by: java.io.FileNotFoundException: ['sample_2113.conll'] (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)

**Comment by manning** [comment]
I can't reproduce this. Are you quite sure that the given files exist? What is your properties file? Note that the file list should be comma separated, but doesn't have any square brackets, quotes, etc. The error message looks like you're passing in a string with square brackets....  If that's not the problem, you'd need to give instructions that recreate a problem.

cf.

```
$ cat a.conll
The	O
Onyx	ANIMAL
was	O
beautiful	O
.	O

$ cat b.conll
Onyx	ANIMAL
like	O
Pandas	ANIMAL
.	O

$ cat c.conll
Did	O
you	O
see	O
a	O
Onyx	ANIMAL
.	O

$ java edu.stanford.nlp.ie.crf.CRFClassifier -useWord -map "word=0,answer=1" -trainFileList a.conll,b.conll -testFile c.conll
...
[main] INFO edu.stanford.nlp.sequences.SeqClassifierFlags - trainFileList=a.conll,b.conll
[main] INFO edu.stanford.nlp.sequences.SeqClassifierFlags - map=word=0,answer=1
[main] INFO edu.stanford.nlp.sequences.SeqClassifierFlags - useWord=true
[main] INFO edu.stanford.nlp.ie.crf.CRFClassifier - numFeatures = 7
[main] INFO edu.stanford.nlp.ie.crf.CRFClassifier - Time to convert docs to feature indices: 0.0 seconds
[main] INFO edu.stanford.nlp.ie.crf.CRFClassifier - numClasses: 2 [0=O,1=ANIMAL]
[main] INFO edu.stanford.nlp.ie.crf.CRFClassifier - numDocuments: 2
...
[main] INFO edu.stanford.nlp.ie.crf.CRFClassifier - CRFClassifier training ... done [0.1 sec].
Did	O	O
you	O	O
see	O	O
a	O	O
Onyx	ANIMAL	ANIMAL
.	O	O

[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - CRFClassifier tagged 6 words in 1 documents at 600.00 words per second.
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -          Entity	P	R	F1	TP	FP	FN
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -          ANIMAL	1.0000	1.0000	1.0000	1	0	0
[main] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier -          Totals	1.0000	1.0000	1.0000	1	0	0

# With non-existent file
$ java edu.stanford.nlp.ie.crf.CRFClassifier -useWord -map "word=0,answer=1" -trainFileList a.conll,x.conll -testFile c.conll
[main] INFO edu.stanford.nlp.ie.crf.CRFClassifier - Invoked on Tue Feb 27 14:53:12 PST 2018 with arguments: -useWord -map word=0,answer=1 -trainFileList a.conll,x.conll -testFile c.conll
[main] INFO edu.stanford.nlp.sequences.SeqClassifierFlags - testFile=c.conll
[main] INFO edu.stanford.nlp.sequences.SeqClassifierFlags - trainFileList=a.conll,x.conll
[main] INFO edu.stanford.nlp.sequences.SeqClassifierFlags - map=word=0,answer=1
[main] INFO edu.stanford.nlp.sequences.SeqClassifierFlags - useWord=true
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.FileNotFoundException: x.conll (No such file or directory)
	at edu.stanford.nlp.io.IOUtils.inputStreamFromFile(IOUtils.java:519)
	at edu.stanford.nlp.io.IOUtils.readerFromFile(IOUtils.java:560)
	at edu.stanford.nlp.objectbank.ReaderIteratorFactory$ReaderIterator.setNextObject(ReaderIteratorFactory.java:189)
	at edu.stanford.nlp.objectbank.ReaderIteratorFactory$ReaderIterator.next(ReaderIteratorFactory.java:243)
	at edu.stanford.nlp.objectbank.ReaderIteratorFactory$ReaderIterator.next(ReaderIteratorFactory.java:152)
	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.setNextObjectHelper(ObjectBank.java:434)
	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.setNextObject(ObjectBank.java:419)
	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.<init>(ObjectBank.java:412)
	at edu.stanford.nlp.objectbank.ObjectBank.iterator(ObjectBank.java:250)
	at edu.stanford.nlp.sequences.ObjectBankWrapper.iterator(ObjectBankWrapper.java:45)
	at edu.stanford.nlp.ie.crf.CRFClassifier.train(CRFClassifier.java:1579)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:785)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:756)
	at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:2991)
Caused by: java.io.FileNotFoundException: x.conll (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:196)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
	at edu.stanford.nlp.io.IOUtils.inputStreamFromFile(IOUtils.java:513)
	... 13 more
```
