### ISSUE TITLE
CoreNLP Server error -> Unknown annotator: mention

### ISSUE THREAD

**Issue by algope** [stanfordnlp/CoreNLP#624]
Hello!

I'm trying to run the server for CoreNLP but when I start it using all annotators (no -anotators flag in the start command) I get this error:

```
ubuntu@ip:~/CoreNLP/stanford-corenlp-full-2018-01-31$ java -mx10g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - using SR parser: edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP -     Threads: 4
[main] INFO CoreNLP - Starting server...
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9000
java.lang.IllegalArgumentException: Unknown annotator: mention
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.ensurePrerequisiteAnnotators(StanfordCoreNLP.java:352)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.getProperties(StanfordCoreNLPServer.java:423)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$200(StanfordCoreNLPServer.java:54)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:710)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I have tried downloading http://nlp.stanford.edu/software/stanford-english-corenlp-models-current.jar as suggested in other similar issue #238 but I still get the same error. 

Thank you for your help!

**Comment by Kuz-man** [comment]
I also had the same problem and ended up with two different solutions:
- Download an older version, for example 3.8 from here: https://stanfordnlp.github.io/CoreNLP/history.html

**Comment by J38** [comment]
Ok I've pushed a bug fix for this.  Very shortly we will submit a revised version of Stanford CoreNLP 3.9.0 that fixes this issue as well.  The final version of 3.9.0 will be when we put it up on Maven.

**Comment by J38** [comment]
At the moment, the current GitHub version (as soon as the commit passes through Jenkins) will have this issue fixed.  Basically by default the `coref` annotator calls `coref.mention`, the goal was to make the list of annotators smaller, and it's pretty common for `coref` to call `coref.mention`.  Also I renamed `mention` to `coref.mention`.  The server code had some defaults that didn't reflect this.

**Comment by ammarasmro** [comment]
I got a similar error with Stanford CoreNLP 3.9.1
```shell
Exception in thread "main" java.lang.IllegalArgumentException: No annotator named mention
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:151)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:495)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:201)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:194)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:181)
	at clients.CorefClient.<init>(CorefClient.java:25)
	at clients.CorefClient.main(CorefClient.java:75)
```
I got that by following the sample API code on [StanfordCoreNLP](https://stanfordnlp.github.io/CoreNLP/coref.html)
It lists the mention annotator as `mention`:
```java
props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,parse,mention,coref");
```

I followed the last comment by @J38 and changed it to coref.mention and it works now
Will it stay this way or is this temporary?

**Comment by goat98** [comment]
yesterday i met with the problem:
my evn : 3.9.1
error:
Exception in thread "main" java.lang.IllegalArgumentException: No annotator named mention
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:151)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:495)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:201)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:194)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:181)

**Comment by ammarasmro** [comment]
@goat98 
The mention annotator is now a part of the coref annotator. If you want to call it use `coref.mention` instead.

**Comment by goat98** [comment]
about Exception in thread "main" java.lang.IllegalArgumentException: No annotator named mention
i make mistake:
in nlp 3.9.1 ,I use the nlp 3.8.0's StanfordCoreNLP-chinese.properties,
in practice， I use 3.9.1‘s StanfordCoreNLP-chinese.properties, the problem solving
if somenone happened the error:
check  your StanfordCoreNLP-chinese.properties version
