### ISSUE TITLE
Unable to start CoreNLP server

### ISSUE THREAD

**Issue by siddharthravindran** [stanfordnlp/CoreNLP#663]
Getting the below error when I run this code 'java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000'

I changed to the path where I placed the CoreNLP folder to load the code, libraries, and model jars that the CoreNLP uses: java -cp "/Users/stanford-corenlp-full-2018-01-31/*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -file inputFile

I also created the configuration file: java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -props sampleProps.properties

Please let me know what next steps I should take to fix this.

[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
[main] INFO CoreNLP -     Threads: 8
[main] INFO CoreNLP - Starting server...
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:414)
	at sun.nio.ch.Net.bind(Net.java:406)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
	at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
	at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.run(StanfordCoreNLPServer.java:1297)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1389)
[Thread-0] INFO CoreNLP - CoreNLP Server is shutting down.

**Comment by J38** [comment]
This error is probably related to you having a different process using port 9000.  Make sure no process is using port 9000, or have the server use a different port.

**Comment by johnarchie1** [comment]
I met the same problem, did you solve it at last？

**Comment by bifeng** [comment]
[site](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html#stopping-the-server), first stopping the server, then start it again

**Comment by bifeng** [comment]
where is the "corenlp.shutdown" file in windows?
