### ISSUE TITLE
IndexOutOfBoundsException on empty `CoreDocument`s

### ISSUE THREAD

**Issue by ansvonwa** [stanfordnlp/CoreNLP#664]
If a document is empty (i.e. because a previous Annotator removed some tokens), and thus, the list of sentences is empty, `wrapAnnotations` in `CoreDocument` fails:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at edu.stanford.nlp.pipeline.CoreDocument.wrapAnnotations(CoreDocument.java:37)
```
Example code:
```
import edu.stanford.nlp.ling.CoreAnnotations;
import edu.stanford.nlp.pipeline.*;

import java.util.Properties;

public class UnclosedSentence {
    public static void main(String[] args) {
        Properties props = new Properties();
        props.setProperty("annotators", "tokenize,cleanxml,ssplit");
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

        CoreDocument doc = new CoreDocument("<random> <xml/> </stuff>");
        pipeline.annotate(doc.annotation());
        System.out.println(doc.annotation().get(CoreAnnotations.SentencesAnnotation.class)); // annotation works
        doc.wrapAnnotations(); // fails with IndexOutOfBoundsException: Index: 0, Size: 0
    }
}
```

**Comment by J38** [comment]
Ok I added a check for `sentences.size() > 0` that should fix this.  Thank you for reporting this bug.
