### ISSUE TITLE
Issue in getting the relation.

### ISSUE THREAD

**Issue by PvsManiyan** [stanfordnlp/CoreNLP#678]
hi 
  I try to get the relation from the RelationAnnatator but null is getting returned every time.I don't know the reason why it's not working I go through the codes but I can't get any idea.Please, can anyone help me on this issue?

java.lang.NullPointerException
	at edu.stanford.nlp.ie.machinereading.MachineReading.assignSyntacticHeadToEntities(MachineReading.java:650)
	at edu.stanford.nlp.ie.machinereading.MachineReading.annotate(MachineReading.java:596)
	at edu.stanford.nlp.ie.machinereading.MachineReading.annotate(MachineReading.java:567)
	at edu.stanford.nlp.pipeline.RelationExtractorAnnotator.annotate(RelationExtractorAnnotator.java:55)
	at com.nlp.main.RelationFinder.main(RelationFinder.java:31)

This is the exception i got.

**Comment by J38** [comment]
Can you please provide more details about the problem you are having.

**Comment by J38** [comment]
What types of relations are you trying to extract ?
