### ISSUE TITLE
JSONDecodeError: Expecting value with CoreNLP 3.9.0 and 3.9.1 NOT with 3.7.0

### ISSUE THREAD

**Issue by The-Gupta** [stanfordnlp/CoreNLP#704]
```
DEBUG:urllib3.connectionpool:http://localhost:9000 "POST /?properties=%7B%27annotators%27%3A+%27coref%27%2C+%27pinelineLanguage%27%3A+%27en%27%7D HTTP/1.1" 500 57
Traceback (most recent call last):

  File "<ipython-input-9-1877aa015047>", line 104, in <module>
    keywords = extract_phrases(df.iloc[:,1].tolist())

  File "<ipython-input-9-1877aa015047>", line 51, in extract_phrases
    result = json.loads(nlp.annotate(doc[i].replace('\n', ' ').replace('\r', ' '), properties= {'annotators': 'coref', 'pinelineLanguage': 'en'}))

  File "D:\Anaconda3\envs\traceability\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)

  File "D:\Anaconda3\envs\traceability\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "D:\Anaconda3\envs\traceability\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value
```

**Comment by The-Gupta** [comment]
Adding 'timeout': '500000' to properties worked for me as nlp.annotate method takes longer to execute with CoreNLP version 3.9.0 and 3.9.1 wrt 3.7.0 [at least for coref and depparse for which I'm using], so it was returning nothing for larger strings (because of time out) and thus, causing the error.

`json.loads(nlp.annotate(doc[i].replace('\n', ' ').replace('\r', ' '), properties= { 'timeout': '500000', 'annotators': 'coref', 'pinelineLanguage': 'en'}))`
