### ISSUE TITLE
StackOverflowError in SemanticGraph object

### ISSUE THREAD

**Issue by gkiril** [stanfordnlp/CoreNLP#719]
I am running the neural dependency parser from CoreNLP 3.8.0 large-scale by using Apache Spark. The CoreNLP pipeline I am using for parsing is this:

```
public static StanfordCoreNLP StanfordDepNNParser(){
    Properties props = new Properties();

    props.put("language", "english");
    props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, depparse");
    props.put("depparse.model", "edu/stanford/nlp/models/parser/nndep/english_SD.gz");
    props.put("parse.originalDependencies", true);

    return new StanfordCoreNLP(props);
}
```

However, after a while, I get the following error:

```
18/06/08 08:16:40 WARN scheduler.TaskSetManager: Lost task 136.0 in stage 0.0 (TID 140, server.com): java.lang.StackOverflowError
    at java.util.HashMap.putVal(HashMap.java:630)
    at java.util.HashMap.put(HashMap.java:611)
    at java.util.HashSet.add(HashSet.java:219)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1526)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    at edu.stanford.nlp.semgraph.SemanticGraph.toCompactStringHelper(SemanticGraph.java:1541)
    . . . .
```

Unfortunately, I cannot locate the exact sentence (or document) that triggers this exception. Is it possible to make some sort of check upfront that would just skip this sentence?

**Comment by gkiril** [comment]
Also, I am eliminating the sentences longer than 100 words before doing the parsing, so it's not some unusually long sentence.

**Comment by J38** [comment]
Hi thanks for bringing up this issue.  If you can find an example sentence that is producing this error, I can try to look more into it.

**Comment by gkiril** [comment]
Unfortunately, I don't see a way I could get an example sentence (I cannot catch StackOverflowError).

**Comment by J38** [comment]
Where is your code for running the pipeline?  Or are you using the Databricks stuff for CoreNLP?  Maybe you could log completed/failed documents somewhere and we could get an example document with this failure.

**Comment by gkiril** [comment]
I have my own pipeline, and I think it's going to be complicated to actually paste the whole thing. Thanks a lot for your efforts to help, I guess I'll have to find some sort of work-around. Cheers!
