### ISSUE TITLE
throwing NPE sutime

### ISSUE THREAD

**Issue by bibekshakya35** [stanfordnlp/CoreNLP#725]
I'm using 3.9.1 version and it is throwing me an error after this line
`Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.`

Here is stacktrace
```
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:638)
	... 22 more
Caused by: java.lang.RuntimeException: Error initializing binder 1
	at edu.stanford.nlp.time.Options.<init>(Options.java:121)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.init(TimeExpressionExtractorImpl.java:44)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.<init>(TimeExpressionExtractorImpl.java:39)
	at edu.stanford.nlp.time.TimeAnnotator.<init>(TimeAnnotator.java:189)
	at edu.stanford.nlp.time.TimeAnnotator.<init>(TimeAnnotator.java:185)
	at com.prasnottar.solr.StanfordFactory.<init>(StanfordFactory.java:29)
	... 27 more
Caused by: java.lang.NullPointerException
	at de.jollyday.configuration.impl.DefaultConfigurationProvider.getProperties(DefaultConfigurationProvider.java:59)
	at de.jollyday.configuration.ConfigurationProviderManager.addInternalConfigurationProviderProperies(ConfigurationProviderManager.java:63)
	at de.jollyday.configuration.ConfigurationProviderManager.mergeConfigurationProperties(ConfigurationProviderManager.java:57)
	at de.jollyday.HolidayManager.createManager(HolidayManager.java:163)
	at de.jollyday.HolidayManager.getInstance(HolidayManager.java:148)
	at edu.stanford.nlp.time.JollyDayHolidays.init(JollyDayHolidays.java:57)
	at edu.stanford.nlp.time.Options.<init>(Options.java:119)
	... 32 more

I don't know what seem to be the problem, when i do normal test to run following line of code it is working as expected.

`       Properties properties = new Properties();
        properties.setProperty("annotators","tokenize, cleanxml,ssplit,pos,lemma,ner");
        properties.setProperty("ner.useSUTime", "false");
        this.pipeline = new StanfordCoreNLP(properties);
        this.pipeline.addAnnotator(new TimeAnnotator("sutime", properties));`

When I used along with Apache Solr 7.3.1 app, It is giving me above stacktrace. I have loaded all the required jar.

**Comment by J38** [comment]
Do you want to use custom SUTime rules?  You should just put `ner.useSUTime` to true and set the SUTime stuff in the overall properties file for the pipeline, and that will run SUTime with your custom properties.  That might fix this error.
