### ISSUE TITLE
Issue with ProtobufAnnotationSerializer

### ISSUE THREAD

**Issue by ghaddarAbs** [stanfordnlp/CoreNLP#730]
Hi, 

I tried to use `ProtobufAnnotationSerializer` to serialize an `Annotation` object  as follow:
```
String text = "Stanford University is located in California. It is a great university, founded in 1891.";
 Annotation document = new Annotation(text);
 Properties props = new Properties();
 props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse,depparse");    
 StanfordCoreNLP pip = new StanfordCoreNLP(props);
 pip.annotate(document);
 
ProtobufAnnotationSerializer serializer = new ProtobufAnnotationSerializer();
FileOutputStream fileOut = new FileOutputStream("path/to/anno.ser");
ObjectOutputStream out = new ObjectOutputStream(fileOut);
serializer.write(document, out);

```
This bug came out:
```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/google/protobuf/GeneratedMessageV3$ExtendableMessage.getExtension(Lcom/google/protobuf/Extension;I)Ljava/lang/Object; @3: invokevirtual
  Reason:
    Type 'com/google/protobuf/Extension' (current frame, stack[1]) is not assignable to 'com/google/protobuf/ExtensionLite'
  Current Frame:
    bci: @3
    flags: { }
    locals: { 'com/google/protobuf/GeneratedMessageV3$ExtendableMessage', 'com/google/protobuf/Extension', integer }
    stack: { 'com/google/protobuf/GeneratedMessageV3$ExtendableMessage', 'com/google/protobuf/Extension', integer }
  Bytecode:
    0x0000000: 2a2b 1cb6 0024 b0                      

	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.toProtoBuilder(ProtobufAnnotationSerializer.java:611)
	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.toProto(ProtobufAnnotationSerializer.java:579)
	at edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer.write(ProtobufAnnotationSerializer.java:184)
at xxxxxxxxxxxxxx.main(xxxxxxx.java:303)  \\ line: serializer.write(document, out);

```
I think that there is an inconsistency between CoreNLP ProtobufAnnotationSerializer and protobuf package. I am using version 3.9.1 downloaded directly from [CoreNLP home page](https://stanfordnlp.github.io/CoreNLP/download.html), and I even tried some alternative solutions but none of them work. I tried:

- versions 3.9 3.8
- download the package and its dependencies directly from maven
- download and build (with ant) the source code on github.

The error occurs with other languages (i tested with French) and even when calling the server.

**Comment by ghaddarAbs** [comment]
Oooops my bad ... one of my dependencies includes protobuf-lite which cause the collision with corenlp
