### ISSUE TITLE
java.lang.NullPointerException when adding certain dcoref.sievePasses flags

### ISSUE THREAD

**Issue by e01c-dat10** [stanfordnlp/CoreNLP#732]
`-dcoref.sievePasses MarkRole,DiscourseMatch,ExactStringMatch,RelaxedExactStringMatch,PreciseConstructs,StrictHeadMatch1,StrictHeadMatch2,StrictHeadMatch3,StrictHeadMatch4,RelaxedHeadMatch,PronounMatch` plus certain other flags results in 

```
done.
Adding true-case annotation...
Exception in thread "main" java.lang.NullPointerException
	at edu.stanford.nlp.dcoref.ScorerMUC.calculateRecall(ScorerMUC.java:23)
	at edu.stanford.nlp.dcoref.CorefScorer.calculateScore(CorefScorer.java:58)
	at edu.stanford.nlp.dcoref.SieveCoreferenceSystem.coreference(SieveCoreferenceSystem.java:987)
	at edu.stanford.nlp.dcoref.SieveCoreferenceSystem.corefReturnHybridOutput(SieveCoreferenceSystem.java:830)
	at edu.stanford.nlp.pipeline.DeterministicCorefAnnotator.annotate(DeterministicCorefAnnotator.java:160)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:660)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:670)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1265)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.processFiles(StanfordCoreNLP.java:1010)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.run(StanfordCoreNLP.java:1382)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1427)
```

version 3.9.1

**Comment by AngledLuffa** [comment]
As of 4.5.0, the following command line works fine, but feel free to reopen or file a new bug if a different command line still has a problem:

```
 java edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators "tokenize,pos,lemma,ner,parse,dcoref" -dcoref.sievePasses MarkRole,DiscourseMatch,ExactStringMatch,RelaxedExactStringMatch,PreciseConstructs,StrictHeadMatch1,StrictHeadMatch2,StrictHeadMatch3,StrictHeadMatch4,RelaxedHeadMatch,PronounMatch
```
