### ISSUE TITLE
getting Exception in thread "main" java.io.IOException: Unable to open "-file" as class path, filename or URL

### ISSUE THREAD

**Issue by galsk87** [stanfordnlp/CoreNLP#737]
when i run the next command : 
java  -cp "*" edu.stanford.nlp.scenegraph.RuleBasedParser -file input.txt

i get the next error 

Exception in thread "main" java.io.IOException: Unable to open "-file" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.io.IOUtils.readerFromString(IOUtils.java:617)
	at edu.stanford.nlp.scenegraph.RuleBasedParser.main(RuleBasedParser.java:266)

**Comment by J38** [comment]
Does it work if you remove the "-file".  Looking at the code it expects `args[0]` to be the file name.

**Comment by galsk87** [comment]
Yes it does, so i should put the file name first?

בתאריך יום ב׳, 2 ביולי 2018, 4:34, מאת J38 ‏<notifications@github.com>:

**Comment by J38** [comment]
Yes, but don't even use `-file` at all.

**Comment by galsk87** [comment]
i tired this command

java  omcs-sentences-free.txt -cp "*"
edu.stanford.nlp.scenegraph.RuleBasedParser

and got the next error

Caused by: java.lang.ClassNotFoundException: omcs-sentences-free.txt

which doesnt make sence because the file is there...

Gal.

**Comment by gandevijay** [comment]
unsubscribe

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
