### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded - while training NER 

### ISSUE THREAD

**Issue by prajvalbavi** [stanfordnlp/CoreNLP#744]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.String.substring(String.java:1969)
	at java.lang.String.split(String.java:2353)
	at java.lang.String.split(String.java:2422)
	at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter$ColumnDocParser.apply(ColumnDocumentReaderAndWriter.java:85)
	at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter$ColumnDocParser.apply(ColumnDocumentReaderAndWriter.java:64)
	at edu.stanford.nlp.objectbank.DelimitRegExIterator.parseString(DelimitRegExIterator.java:71)
	at edu.stanford.nlp.objectbank.DelimitRegExIterator.setNext(DelimitRegExIterator.java:67)
	at edu.stanford.nlp.objectbank.DelimitRegExIterator.<init>(DelimitRegExIterator.java:63)
	at edu.stanford.nlp.objectbank.DelimitRegExIterator$DelimitRegExIteratorFactory.getIterator(DelimitRegExIterator.java:128)
	at edu.stanford.nlp.sequences.ColumnDocumentReaderAndWriter.getIterator(ColumnDocumentReaderAndWriter.java:58)
	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.setNextObjectHelper(ObjectBank.java:435)
	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.setNextObject(ObjectBank.java:419)
	at edu.stanford.nlp.objectbank.ObjectBank$OBIterator.next(ObjectBank.java:459)
	at edu.stanford.nlp.sequences.ObjectBankWrapper$WrappedIterator.primeNextHelper(ObjectBankWrapper.java:61)
	at edu.stanford.nlp.sequences.ObjectBankWrapper$WrappedIterator.hasNext(ObjectBankWrapper.java:71)
	at edu.stanford.nlp.ie.crf.CRFClassifier.train(CRFClassifier.java:1579)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:785)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.train(AbstractSequenceClassifier.java:756)
	at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:2991)

**Comment by J38** [comment]
What command did you run that generated this?  How much memory did you allocate the process ?
The first thing to try is to allocate more memory.

**Comment by ladiesman6969** [comment]
Use -Xms2g as program arguments
This will allocate 2 GB memory to the JVM heap space.

**Comment by prajvalbavi** [comment]
I had used the below command:
java -mx4g -cp stanford-corenlp-3.9.1.jar edu.stanford.nlp.ie.crf.CRFClassifier -prop train_file.prop

**Comment by J38** [comment]
What is the max RAM you have?  Have you tried increasing the memory?

**Comment by prajvalbavi** [comment]
Max RAM - 8G, increased till 6G, I have around 2000 files with average character count ~ 3000, and have 2 labels

**Comment by J38** [comment]
So you ran with 6GB of RAM and it gave you that error?

Could you show your properties file and a sample of your training data file.

**Comment by J38** [comment]
If you haven't already, make sure to review these instructions on training located on this page:

https://stanfordnlp.github.io/CoreNLP/ner.html#training-or-retraining-new-models

**Comment by J38** [comment]
Another thing you could try is to reduce the size of your training data to pinpoint the amount where the out of RAM issue does not occur.

**Comment by prajvalbavi** [comment]
It did not give any problem with 1 file or 300 files, but with increasing the number of files to ~2000 it gives error. What is the limit on the training set data one can use to train stanford ner ?
