### ISSUE TITLE
Using too much RAM

### ISSUE THREAD

**Issue by Vincent-Li-9701** [stanfordnlp/CoreNLP#760]
I'm trying to run the example code using IntelliJ.

Here is a link to the code I run.
https://stanfordnlp.github.io/CoreNLP/api.html

I give IntelliJ 7GB of memory by setting -Xmx7g -Xms256m, but I still received below error.

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/vincent/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/vincent/Desktop/stanford-corenlp-full-2018-02-27/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (edu.stanford.nlp.pipeline.StanfordCoreNLP).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at edu.stanford.nlp.parser.nndep.Classifier.initGradientHistories(Classifier.java:606)
	at edu.stanford.nlp.parser.nndep.Classifier.<init>(Classifier.java:140)
	at edu.stanford.nlp.parser.nndep.Classifier.<init>(Classifier.java:115)
	at edu.stanford.nlp.parser.nndep.DependencyParser.loadModelFile(DependencyParser.java:624)
	at edu.stanford.nlp.parser.nndep.DependencyParser.loadFromModelFile(DependencyParser.java:499)
	at edu.stanford.nlp.pipeline.DependencyParseAnnotator.<init>(DependencyParseAnnotator.java:57)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.dependencies(AnnotatorImplementations.java:240)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$57(StanfordCoreNLP.java:559)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$29/1418621776.apply(Unknown Source)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$null$69(StanfordCoreNLP.java:625)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$$Lambda$38/1007603019.get(Unknown Source)
	at edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:126)
	at edu.stanford.nlp.util.Lazy.get(Lazy.java:31)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:149)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:495)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:201)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:194)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:181)
	at com.chatmeter.grimore.scripts.BasicPipelineExample.main(BasicPipelineExample.java:29)

Has anyone encountered a similar problem using IntelliJ before?

**Comment by Vincent-Li-9701** [comment]
Solved it. I found out I have to edit both the VM Options in that script's Configuration and the VM Setting for IntelliJ.
