### ISSUE TITLE
Readiness endpoint throws an exception

### ISSUE THREAD

**Issue by Sytten** [stanfordnlp/CoreNLP#771]
Hi!
It seems like the `/ready` endpoints throws an exception every time it is queried:
```
java.lang.IllegalArgumentException: Unknown annotator: mention
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.ensurePrerequisiteAnnotators(StanfordCoreNLP.java:352)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.getProperties(StanfordCoreNLPServer.java:423)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$200(StanfordCoreNLPServer.java:54)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:710)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

We start our server with:
`java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 8080 -timeout 15000`
it is a bit annoying because our service discovery ping the service every 30s and it pollutes the logs.
Not sure what can be done to silence this exception.

Thanks!

**Comment by J38** [comment]
Are you using the latest code from GitHub or 3.9.1 ?  This issue should be fixed now, there was just some annotator renaming going on before.  You could also try adding this to your command:

`-annotators tokenize,ssplit,pos,lemma,ner,parse,depparse,coref,natlog,openie,kbp`

(or remove any annotators you don't want)

**Comment by Sytten** [comment]
Im using an older version I think, thanks for the response
