### ISSUE TITLE
PTB trees to UD conversion: error in applying NER tags

### ISSUE THREAD

**Issue by Shaul1321** [stanfordnlp/CoreNLP#777]
Hello,

I try to convert the Penn constituency treebank to UD format using the current release of CoreNLP. I use the following command:

`java -cp stanford-corenlp-3.9.2.jar -mx1g edu.stanford.nlp.trees.ud.UniversalDependenciesConverter -treeFile ptb-treebank.txt > ud-treeabank.txt`

The conversion process is completed. However, during the run it displays the following error, stating that NER tags were not applied:

```
java.io.IOException: Unable to open "edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:481)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1503)
	at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2926)
	at edu.stanford.nlp.ie.ClassifierCombiner.loadClassifierFromPath(ClassifierCombiner.java:286)
	at edu.stanford.nlp.ie.ClassifierCombiner.loadClassifiers(ClassifierCombiner.java:270)
	at edu.stanford.nlp.ie.ClassifierCombiner.<init>(ClassifierCombiner.java:142)
	at edu.stanford.nlp.ie.NERClassifierCombiner.<init>(NERClassifierCombiner.java:130)
	at edu.stanford.nlp.ie.NERClassifierCombiner.createNERClassifierCombiner(NERClassifierCombiner.java:275)
	at edu.stanford.nlp.ie.NERClassifierCombiner.createNERClassifierCombiner(NERClassifierCombiner.java:214)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter.setupNERTagger(UniversalDependenciesConverter.java:153)
	at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter.addNERTags(UniversalDependenciesConverter.java:183)
	at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter.convertTreeToBasic(UniversalDependenciesConverter.java:70)
	at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter.access$000(UniversalDependenciesConverter.java:28)
	at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter$TreeToSemanticGraphIterator.next(UniversalDependenciesConverter.java:101)
	at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter$TreeToSemanticGraphIterator.next(UniversalDependenciesConverter.java:83)
	at edu.stanford.nlp.trees.ud.UniversalDependenciesConverter.main(UniversalDependenciesConverter.java:238)
Error setting up NERClassifierCombiner!  Not applying NER tags!
Error running NERClassifierCombiner on Tree!  Not applying NER tags!
```

The same error appears when using other versions of CoreNLP. What causes this error? Is the use of NER crucial for a valid conversion process?

Thanks!

**Comment by J38** [comment]
You need to add the models jar to your CLASSPATH, and yes you need the NER for the conversion.
