### ISSUE TITLE
Server crashes when using regexner

### ISSUE THREAD

**Issue by shoeffner** [stanfordnlp/CoreNLP#792]
# Crash description and steps to reproduce
When trying to run the CoreNLP server inside a docker container using the Dockerfile available in my PR to https://github.com/vineetvermait/corenlp-docker/pull/1, the server will crash whenever the regexner annotator is used (It is still similar to the recommend [frnkenstien/corenlp](https://hub.docker.com/r/frnkenstien/corenlp/), just with the latest release version). `docker build . -t corenlp && docker run --rm -p 9000:9000 corenlp`

A common crash report looks like this:
```
[pool-1-thread-1] INFO CoreNLP - [/172.17.0.1:52686] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner,coref,kbp
The quick brown fox jumps over the lazy dog.
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[pool-1-thread-1] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.5 sec].
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator depparse
[pool-1-thread-1] INFO edu.stanford.nlp.parser.nndep.DependencyParser - Loading depparse model: edu/stanford/nlp/models/parser/nndep/english_UD.gz ... 
[pool-1-thread-1] INFO edu.stanford.nlp.parser.nndep.Classifier - PreComputed 99996, Elapsed Time: 13.546 (s)
[pool-1-thread-1] INFO edu.stanford.nlp.parser.nndep.DependencyParser - Initializing dependency parser ... done [15.2 sec].
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
[pool-1-thread-1] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [2.7 sec].
[pool-1-thread-1] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.8 sec].
[pool-1-thread-1] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.9 sec].
[pool-1-thread-1] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
[pool-1-thread-1] INFO edu.stanford.nlp.time.TimeExpressionExtractorImpl - Using following SUTime rules: edu/stanford/nlp/models/sutime/defs.sutime.txt,edu/stanford/nlp/models/sutime/english.sutime.txt,edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 580704 unique entries out of 581863 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_caseless.tab, 0 TokensRegex patterns.
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 4869 unique entries out of 4869 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_cased.tab, 0 TokensRegex patterns.
[pool-1-thread-1] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 585573 unique entries from 2 files
```

## Affected annotator selections

While this looks similar to #789, openie is working fine on the example sentence and the server is not crashing for this annotator.
The following annotator selections cause the server to use the regexner annotator and thus crash given the example sentence "The quick brown fox jumps over the lazy dog.":
- named entities (regexner)
- coreference
- relations

## Using the latest version

I also used the following Dockerfile (`docker build -f Dockerfile.develop . -t corenlp:develop && docker --rm -p 9000:9000 corenlp:develop`) to run the latest version (this one takes a long time to build as it needs to download many things):
```Dockerfile
FROM openjdk:8-alpine

MAINTAINER Sebastian Höffner <shoeffner@tzi.de>

ARG PORT=9000
ENV PORT=${PORT:-9000}
EXPOSE ${PORT}

RUN apk update \
    && apk add git maven \
    && git clone https://github.com/stanfordnlp/CoreNLP.git \
    && cd CoreNLP \
    && mvn package \
    && mv target/stanford-corenlp-*.jar .

RUN wget https://nlp.stanford.edu/software/stanford-corenlp-models-current.jar -P /CoreNLP \
    & wget https://nlp.stanford.edu/software/stanford-english-corenlp-models-current.jar -P /CoreNLP \
    & wget https://nlp.stanford.edu/software/stanford-english-kbp-corenlp-models-current.jar -P /CoreNLP

WORKDIR /CoreNLP

CMD java -cp '*' -Xmx8g edu.stanford.nlp.pipeline.StanfordCoreNLPServer
```

### Coreference & Relations

In this version, the same happens again for coreference and relations (log for relations):
```
--- StanfordCoreNLPServer#main() called ---
setting default constituency parser
warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
to use shift reduce parser download English models jar from:
http://stanfordnlp.github.io/CoreNLP/download.html
    Threads: 4
Starting server...
StanfordCoreNLPServer listening at /0.0.0.0:9000
[/172.17.0.1:52882] API call w/annotators tokenize,ssplit,pos,depparse,lemma,ner,coref,kbp
The quick brown fox jumps over the lazy dog.
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.8 sec].
Adding annotator depparse
Loading depparse model: edu/stanford/nlp/models/parser/nndep/english_UD.gz ... 
PreComputed 99996, Elapsed Time: 14.951 (s)
Initializing dependency parser ... done [16.8 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [3.2 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.8 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [2.4 sec].
ner.fine.regexner: Read 580704 unique entries out of 581863 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_caseless.tab, 0 TokensRegex patterns.
ner.fine.regexner: Read 4869 unique entries out of 4869 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_cased.tab, 0 TokensRegex patterns.
ner.fine.regexner: Read 585573 unique entries from 2 files
```

### Named entities (regexner)

For the named entities (regexner) call `http://localhost:9000/?properties=%7B%22annotators%22%3A%20%22tokenize%2Cssplit%2Cregexner%22%2C%20%22date%22%3A%20%222018-11-09T19%3A15%3A55%22%7D&pipelineLanguage=en` the server returns a proper response in the latest version, but the client website does not seem to process it:
```json
{
  "docDate": "2018-11-09T19:15:55",
  "sentences": [
    {
      "index": 0,
      "tokens": [
        {
          "index": 1,
          "word": "The",
          "originalText": "The",
          "characterOffsetBegin": 0,
          "characterOffsetEnd": 3,
          "before": "",
          "after": " "
        },
        {
          "index": 2,
          "word": "quick",
          "originalText": "quick",
          "characterOffsetBegin": 4,
          "characterOffsetEnd": 9,
          "before": " ",
          "after": " "
        },
        {
          "index": 3,
          "word": "brown",
          "originalText": "brown",
          "characterOffsetBegin": 10,
          "characterOffsetEnd": 15,
          "before": " ",
          "after": " "
        },
        {
          "index": 4,
          "word": "fox",
          "originalText": "fox",
          "characterOffsetBegin": 16,
          "characterOffsetEnd": 19,
          "before": " ",
          "after": " "
        },
        {
          "index": 5,
          "word": "jumps",
          "originalText": "jumps",
          "characterOffsetBegin": 20,
          "characterOffsetEnd": 25,
          "before": " ",
          "after": " "
        },
        {
          "index": 6,
          "word": "over",
          "originalText": "over",
          "characterOffsetBegin": 26,
          "characterOffsetEnd": 30,
          "before": " ",
          "after": " "
        },
        {
          "index": 7,
          "word": "the",
          "originalText": "the",
          "characterOffsetBegin": 31,
          "characterOffsetEnd": 34,
          "before": " ",
          "after": " "
        },
        {
          "index": 8,
          "word": "lazy",
          "originalText": "lazy",
          "characterOffsetBegin": 35,
          "characterOffsetEnd": 39,
          "before": " ",
          "after": " "
        },
        {
          "index": 9,
          "word": "dog",
          "originalText": "dog",
          "characterOffsetBegin": 40,
          "characterOffsetEnd": 43,
          "before": " ",
          "after": ""
        },
        {
          "index": 10,
          "word": ".",
          "originalText": ".",
          "characterOffsetBegin": 43,
          "characterOffsetEnd": 44,
          "before": "",
          "after": ""
        }
      ]
    }
  ]
}

```

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/1836815/48280610-618fcd00-e454-11e8-80de-d09976608a0e.png">

### Sentiment

For the sentiment annotator, I receive the following NoClassDefFoundError, but I might have made a mistake in setting up all dependencies properly. However, the server keeps running and doesn't time out on the client side – but a refresh fixes it:

```
--- StanfordCoreNLPServer#main() called ---
setting default constituency parser
warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
to use shift reduce parser download English models jar from:
http://stanfordnlp.github.io/CoreNLP/download.html
    Threads: 4
Starting server...
StanfordCoreNLPServer listening at /0.0.0.0:9000
[/172.17.0.1:52886] API call w/annotators tokenize,ssplit,pos,parse,sentiment
The quick brown fox jumps over the lazy dog.
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.8 sec].
Adding annotator parse
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.5 sec].
Adding annotator sentiment
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/ejml/simple/SimpleBase
	at edu.stanford.nlp.pipeline.SentimentAnnotator.<init>(SentimentAnnotator.java:52)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.sentiment(AnnotatorImplementations.java:217)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$16(StanfordCoreNLP.java:534)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$null$30(StanfordCoreNLP.java:602)
	at edu.stanford.nlp.util.Lazy$3.compute(Lazy.java:126)
	at edu.stanford.nlp.util.Lazy.get(Lazy.java:31)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:149)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:251)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:192)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:188)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.mkStanfordCoreNLP(StanfordCoreNLPServer.java:368)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.access$800(StanfordCoreNLPServer.java:50)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:855)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.ejml.simple.SimpleBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more
```

### Typo for dependency parse

The server additionally crashes without any error indications when I supply "The quick brown fox jumps over **th** lazy dog." and try the dependency parse (it works fine without the typo – and I haven't tried this with the stable image or any other annotator):
```
[/172.17.0.1:52872] API call w/annotators tokenize,ssplit,pos,depparse
The quick brown fox jumps over th lazy dog.
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Adding annotator depparse
Loading depparse model: edu/stanford/nlp/models/parser/nndep/english_UD.gz ... 
```

**Comment by J38** [comment]
A few thoughts...

1.) I am not entirely sure what using Docker gains for you, but let me know if you really need to use Docker.  If you just have Java 8 (or even later versions should be fine), all you need to do is have a  directory with all the appropriate jars and it will work fine.

2.) I recommend running the server in this manner:

- put all the jars you need in a directory
- `export CLASSPATH=/path/to/directory-with-jars`
- run this command:
```
java -Xmx14g edu.stanford.nlp.pipeline.StanfordCoreNLPServer
```
- if you want to run the server with certain properties (e..g set the annotators list), put the properties in a file call my-properties.props, and use this command:

```
java -Xmx14g edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties /path/to/my-properties.props
```
- you can of course set a lot of things with options as well to that command, such as the port etc...

- if you get mysterious crashes, you are probably missing a jar (though not sure what to make of the 'th' example)...the jars you need are the models jar your config script above downloads, and all of the jars in the `CoreNLP/lib` directory.  For instance, the ejml issue is probably related to missing jars.

Please let me know if you still have trouble getting things working.
