### ISSUE TITLE
NullPointerException with tokensregex

### ISSUE THREAD

**Issue by jmugan** [stanfordnlp/CoreNLP#826]
I get the following error with tokensregex in 3.9.2 (also got same result in 3.8)

```
java.lang.NullPointerException
	at edu.stanford.nlp.pipeline.DeterministicCorefAnnotator.setNamedEntityTagGranularity(DeterministicCorefAnnotator.java:93)
	at edu.stanford.nlp.pipeline.DeterministicCorefAnnotator.annotate(DeterministicCorefAnnotator.java:101)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:637)
at eu.fbk.dkm.pikes.tintop.AnnotationPipeline.parseAll(AnnotationPipeline.java:1081)
	at eu.fbk.dkm.pikes.tintop.AnnotationPipeline.parseAll(AnnotationPipeline.java:1048)
	at eu.fbk.dkm.pikes.tintop.AnnotationPipeline.parseFromString(AnnotationPipeline.java:1114)
	at eu.fbk.dkm.pikes.tintop.FolderOrchestrator$LocalTintopClient.run(FolderOrchestrator.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I saw somewhere that it might be because CoreNLP is pointed to the wrong model file. Is there a way to check that? This CoreNLP is integrated into a larger program (Pikes), so it is hard for me to know what is pointing where.

**Comment by J38** [comment]
Hi this issue has been fixed in the GitHub version.  A warning, we are currently upgrading to UD 2.0 so the current code base has some slight issues with it we are working to fix.

**Comment by amitru** [comment]
Is this issue resolved? i am using pom.xml with below two dependencies and getting the same error, i am in java 1.8. 

	```
<dependency>
		    <groupId>edu.stanford.nlp</groupId>
		    <artifactId>stanford-corenlp</artifactId>
		    <version>3.9.2</version>
		</dependency>
		
		<dependency>
		    <groupId>edu.stanford.nlp</groupId>
		    <artifactId>stanford-corenlp</artifactId>
		    <version>3.9.2</version>
		    <classifier>models</classifier>
		</dependency>
```
ERROR:
```
Exception in thread "main" java.lang.NullPointerException
	at edu.stanford.nlp.pipeline.DeterministicCorefAnnotator.setNamedEntityTagGranularity(DeterministicCorefAnnotator.java:93)
	at edu.stanford.nlp.pipeline.DeterministicCorefAnnotator.annotate(DeterministicCorefAnnotator.java:173)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:637)
	at com.amitru.psanalyzer.premptivesentimentanalyzer.StanfordCoreNLPTest.findSentiment(StanfordCoreNLPTest.java:27)
	at com.amitru.psanalyzer.premptivesentimentanalyzer.StanfordCoreNLPTest.main(StanfordCoreNLPTest.java:39)

```
