### ISSUE TITLE
re-train new model throws java.lang.NumberFormatException

### ISSUE THREAD

**Issue by dtsonov** [stanfordnlp/CoreNLP#834]
I'm having problem with CoreNLP when feed my own data for re-train.
I get the following error:
Exception in thread "main" java.lang.NumberFormatException: For input string: "Pouring"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.valueOf(Unknown Source)
        at edu.stanford.nlp.sentiment.SentimentUtils.attachLabels(SentimentUtils.java:37)
        at edu.stanford.nlp.sentiment.SentimentUtils.readTreesWithLabels(SentimentUtils.java:69)
        at edu.stanford.nlp.sentiment.SentimentUtils.readTreesWithGoldLabels(SentimentUtils.java:50)
        at edu.stanford.nlp.sentiment.SentimentTraining.main(SentimentTraining.java:184)

I found the sentences which contain "Pouring" and feed it one by one to the PENNTREE parser and everyone went fine to a bracket tree etc.
Anyway I did remove all sentences containing "Pouring", but then i get the same error, but for another strings.
My data set files are in ANSI format too.
Does anyone have similar problems ?

**Comment by J38** [comment]
This is an example of a properly formatted tree:

```
(3 (2 (2 The) (2 Rock)) (4 (3 (2 is) (4 (2 destined) (2 (2 (2 (2 (2 to) (2 (2 be) (2 (2 the) (2 (2 21st) (2 (2 (2 Century) (2 's)) (2 (3 new) (2 (2 ``) (2 Conan)))))))) (2 '')) (2 and)) (3 (2 that) (3 (2 he) (3 (2 's) (3 (2 going) (3 (2 to) (4 (3 (2 make) (3 (3 (2 a) (3 splash)) (2 (2 even) (3 greater)))) (2 (2 than) (2 (2 (2 (2 (1 (2 Arnold) (2 Schwarzenegger)) (2 ,)) (2 (2 Jean-Claud) (2 (2 Van) (2 Damme)))) (2 or)) (2 (2 Steven) (2 Segal))))))))))))) (2 .)))
```
