### ISSUE TITLE
I'm running edu.stanford.nlp.sentiment.SentimentPipeline and getting below error

### ISSUE THREAD

**Issue by velraman** [stanfordnlp/CoreNLP#837]
[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.5 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator sentiment
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.lang.ClassNotFoundException: edu.stanford.nlp.rnn.SimpleTensor
	at edu.stanford.nlp.sentiment.SentimentModel.loadSerialized(SentimentModel.java:633)
	at edu.stanford.nlp.pipeline.SentimentAnnotator.<init>(SentimentAnnotator.java:52)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.sentiment(AnnotatorImplementations.java:217)

**Comment by J38** [comment]
How are you trying to run this?  What jars do you have in your CLASSPATH?
