### ISSUE TITLE
Not using statistical NER model causing NPE

### ISSUE THREAD

**Issue by xiujunma** [stanfordnlp/CoreNLP#863]
props.setProperty("ner.model", "");

java.lang.NullPointerException
	at edu.stanford.nlp.pipeline.EntityMentionsAnnotator.determineEntityMentionConfidences(EntityMentionsAnnotator.java:236)
	at edu.stanford.nlp.pipeline.EntityMentionsAnnotator.annotate(EntityMentionsAnnotator.java:333)
	at edu.stanford.nlp.pipeline.NERCombinerAnnotator.annotate(NERCombinerAnnotator.java:353)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:637)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:629)

**Comment by manning** [comment]
@j38: This is a clear bug in the entity probability code that you added for a recent release. If I run the command `java -mx6g edu.stanford.nlp.pipeline.StanfordCoreNLP -ner.model "" -file short.txt` on the file:
> $75,000,000 is the aggregate principal amount.

then I get this error because `labelProbsForToken is {MONEY=null}`.

**Comment by J38** [comment]
This should be fixed now.
