### ISSUE TITLE
请问SegDemo.java类中引用的文件ctb.gz是否缺失？

### ISSUE THREAD

**Issue by yangle9567** [stanfordnlp/CoreNLP#882]
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "data/ctb.gz" as class path, filename or URL
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifierNoExceptions(AbstractSequenceClassifier.java:1518)
	at edu.stanford.nlp.wordseg.demo.SegDemo.main(SegDemo.java:46)
Caused by: java.io.IOException: Unable to open "data/ctb.gz" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1503)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifierNoExceptions(AbstractSequenceClassifier.java:1516)
	... 1 more

**Comment by yangle9567** [comment]
@Christopher Manning 是否缺失文件ctb.gz，还有组织basedir路径是否有点问题？

**Comment by AngledLuffa** [comment]
Where did you download this?  data/ctb.gz is available in the package
downloaded here:

https://nlp.stanford.edu/software/segmenter.html

**Comment by yangle9567** [comment]
我是在这个链接中下载stanfordnlp / CoreNLP项目代码的，同时在您发给的那个链接中没有找到如何下载ctb.gz文件。

**Comment by yangle9567** [comment]
我是在这个链接（https://github.com/stanfordnlp/CoreNLP）中下载stanfordnlp / CoreNLP项目代码的，同时在您发给的那个链接中没有找到如何下载ctb.gz文件。

**Comment by AngledLuffa** [comment]
This link:

Download Stanford Word Segmenter version 3.9.2

https://nlp.stanford.edu/software/stanford-segmenter-2018-10-16.zip

look for

data/ctb.gz
