### ISSUE TITLE
3 tests are failing: "No extraction for sentence!"

### ISSUE THREAD

**Issue by reynoldsnlp** [stanfordnlp/CoreNLP#898]
Three tests fail for me, so I cannot package the current version: `testPassiveReflexive`, `testObamaPresidentOfRegressionFull`, and `testReflexive`. All three give the message `No extraction for sentence!`.

```bash
$ mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< edu.stanford.nlp:stanford-corenlp >------------------
[INFO] Building Stanford CoreNLP 3.9.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ stanford-corenlp ---
[INFO] Deleting /opt/CoreNLP/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ stanford-corenlp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /opt/CoreNLP/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ stanford-corenlp ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1707 source files to /opt/CoreNLP/target/classes
[WARNING] /opt/CoreNLP/src/edu/stanford/nlp/coref/docreader/CoNLLDocumentReader.java: Some input files use or override a deprecated API.
[WARNING] /opt/CoreNLP/src/edu/stanford/nlp/coref/docreader/CoNLLDocumentReader.java: Recompile with -Xlint:deprecation for details.
[WARNING] /opt/CoreNLP/src/edu/stanford/nlp/util/logging/OutputHandler.java: Some input files use unchecked or unsafe operations.
[WARNING] /opt/CoreNLP/src/edu/stanford/nlp/util/logging/OutputHandler.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ stanford-corenlp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /opt/CoreNLP/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ stanford-corenlp ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 173 source files to /opt/CoreNLP/target/test-classes
[WARNING] /opt/CoreNLP/test/src/edu/stanford/nlp/patterns/CreatePatternsTest.java: Some input files use or override a deprecated API.
[WARNING] /opt/CoreNLP/test/src/edu/stanford/nlp/patterns/CreatePatternsTest.java: Recompile with -Xlint:deprecation for details.
[WARNING] /opt/CoreNLP/test/src/edu/stanford/nlp/util/ComparatorsTest.java: Some input files use unchecked or unsafe operations.
[WARNING] /opt/CoreNLP/test/src/edu/stanford/nlp/util/ComparatorsTest.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ stanford-corenlp ---
[INFO] Surefire report directory: /opt/CoreNLP/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
...

Running edu.stanford.nlp.naturalli.RelationTripleSegmenterTest
Tests run: 66, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.811 sec <<< FAILURE!
testPassiveReflexive(edu.stanford.nlp.naturalli.RelationTripleSegmenterTest)  Time elapsed: 0.048 sec  <<< FAILURE!
junit.framework.AssertionFailedError: No extraction for sentence!
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at edu.stanford.nlp.naturalli.RelationTripleSegmenterTest.testPassiveReflexive(RelationTripleSegmenterTest.java:460)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testObamaPresidentOfRegressionFull(edu.stanford.nlp.naturalli.RelationTripleSegmenterTest)  Time elapsed: 0.019 sec  <<< FAILURE!
junit.framework.AssertionFailedError: No extraction for sentence!
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at edu.stanford.nlp.naturalli.RelationTripleSegmenterTest.testObamaPresidentOfRegressionFull(RelationTripleSegmenterTest.java:661)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testReflexive(edu.stanford.nlp.naturalli.RelationTripleSegmenterTest)  Time elapsed: 0.009 sec  <<< FAILURE!
junit.framework.AssertionFailedError: No extraction for sentence!
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at edu.stanford.nlp.naturalli.RelationTripleSegmenterTest.testReflexive(RelationTripleSegmenterTest.java:448)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running edu.stanford.nlp.naturalli.PolarityTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec
Running edu.stanford.nlp.naturalli.UtilTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec
Running edu.stanford.nlp.naturalli.NaturalLogicRelationTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running edu.stanford.nlp.naturalli.OpenIETest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 sec
Running edu.stanford.nlp.parser.metrics.TreeSpanScoringTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 sec
Running edu.stanford.nlp.parser.shiftreduce.ShiftReduceUtilsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec
Running edu.stanford.nlp.parser.shiftreduce.BinaryTransitionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running edu.stanford.nlp.parser.shiftreduce.ShiftTransitionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running edu.stanford.nlp.parser.shiftreduce.ShiftReduceParserTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.046 sec
Running edu.stanford.nlp.parser.shiftreduce.ReorderingOracleTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec
Running edu.stanford.nlp.parser.shiftreduce.OracleTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 sec
Running edu.stanford.nlp.parser.lexparser.SpanishUnknownWordModelTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec
Running edu.stanford.nlp.patterns.surface.PatternsForEachTokenTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running edu.stanford.nlp.patterns.surface.SurfacePatternTest
pats size is 1
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec
Running edu.stanford.nlp.patterns.surface.AnnotatedTextReaderTest
[[TextAnnotation=I am going to be in Italy sometime , soon . TokensAnnotation=[I, am, going, to, be, in, Italy, sometime, ,, soon, .] DocIDAnnotation=0-0], [TextAnnotation=Specifically in Tuscany . TokensAnnotation=[Specifically, in, Tuscany, .] DocIDAnnotation=0-1]]
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running edu.stanford.nlp.patterns.CreatePatternsTest
Size of othersemantic class variables is 0
graph is -> present/VBP (root)
  -> We/PRP (nsubj)
  -> paper/NN (obj)
    -> a/DT (det)
  -> applied/VBN (ccomp)
    -> that/IN (mark)
    -> focuses/NN (nsubj)
      -> graphs/NNS (nmod:on)
        -> semantic/JJ (amod)
    -> language/NN (nmod:to)

{sent1={0=[], 2=[], 4=[], 7=[], 11=[]}}
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 sec

Results :

Failed tests:   testPassiveReflexive(edu.stanford.nlp.naturalli.RelationTripleSegmenterTest): No extraction for sentence!
  testObamaPresidentOfRegressionFull(edu.stanford.nlp.naturalli.RelationTripleSegmenterTest): No extraction for sentence!
  testReflexive(edu.stanford.nlp.naturalli.RelationTripleSegmenterTest): No extraction for sentence!

Tests run: 1153, Failures: 3, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:23 min
[INFO] Finished at: 2019-06-26T02:14:12-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project stanford-corenlp: There are test failures.
[ERROR]
[ERROR] Please refer to /opt/CoreNLP/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by AngledLuffa** [comment]
Well, good news is that fixing this has been my task for the last few
days... not sure when that will be available, though.

For future reference, please don't dump the entire output of the test
suite.  Just the one(s) failing is sufficient.

John

**Comment by reynoldsnlp** [comment]
Do you know which commit I can rewind to to get all the tests passing?

**Comment by manning** [comment]
You need to roll back to Jan 15, commit b2f936a4f8c6076e5acc542563ba0bd267d9f9f8 . 

We've been spending quite a while converting things over from UD v1 to UD v2....

**Comment by J38** [comment]
I believe all the tests currently pass with the current version of master.

**Comment by reynoldsnlp** [comment]
Thanks!
