### ISSUE TITLE
Issues when concurrently deserializing Annotation objects

### ISSUE THREAD

**Issue by jiepujiang** [stanfordnlp/CoreNLP#96]
Hello,

I try to deserialize previously stored Annotation objects (the annotation includes tokenization, ssplit, POS tag, pcfg parsing, and NER tag) concurrently in different threads as follows:

Annotation annotation = (Annotation) objin.readObject();

and it caused the following exception:

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at edu.stanford.nlp.trees.GrammaticalRelation.valueOf(GrammaticalRelation.java:165)
	at edu.stanford.nlp.trees.UniversalEnglishGrammaticalRelations.valueOf(UniversalEnglishGrammaticalRelations.java:1674)
	at edu.stanford.nlp.trees.GrammaticalRelation.readResolve(GrammaticalRelation.java:566)

**Comment by jiepujiang** [comment]
Version 3.5.2

**Comment by manning** [comment]
Thanks for this report. I agree that there was a problem here with the new Universal Dependencies code. I believe the commit that I'm about to make fixes it, but it would be great if you get a chance to check, since concurrency bugs are subtle and hard to test.
