### ISSUE TITLE
example.serialized.ncc.ncc.ser.gz not working  ::: JDK13 is Java version

### ISSUE THREAD

**Issue by BVSREDDY82** [stanfordnlp/CoreNLP#984]
```
from nltk.tag import StanfordNERTagger

stanford_classifier  =  '/home/test/stanford-ner-2018-10-16/classifiers/example.serialized.ncc.ncc.ser.gz'
stanford_ner = '/home/test/stanford-ner-2018-10-16/stanford-ner.jar'
# Build NER tagger object
st = StanfordNERTagger(stanford_classifier, stanford_ner)

# A sample text for NER tagging
text = 'Ram works at Google' 
# Tag the sentence and print output
tagged = st.tag(str(text).split())
print(tagged)
```

Error reported:
/home/test/Desktop/myenv/bin/python3 /home/test/NlpSource-master/sss.py
Traceback (most recent call last):
  File "/home/test/NlpSource-master/sss.py", line 32, in <module>
    tagged = st.tag(str(text).split())
  File "/home/test/Desktop/myenv/lib/python3.7/site-packages/nltk/tag/stanford.py", line 93, in tag
    return sum(self.tag_sents([tokens]), [])
  File "/home/test/Desktop/myenv/lib/python3.7/site-packages/nltk/tag/stanford.py", line 116, in tag_sents
    cmd, classpath=self._stanford_jar, stdout=PIPE, stderr=PIPE
  File "/home/test/Desktop/myenv/lib/python3.7/site-packages/nltk/internals.py", line 146, in java
    raise OSError('Java command failed : ' + str(cmd))
OSError: Java command failed : ['/usr/bin/java', '-mx1000m', '-cp', '/home/test/stanford-ner-2018-10-16/stanford-ner.jar', 'edu.stanford.nlp.ie.crf.CRFClassifier', '-loadClassifier', '/home/test/stanford-ner-2018-10-16/classifiers/example.serialized.ncc.ncc.ser.gz', '-textFile', '/tmp/tmph8k3mnol', '-outputFormat', 'slashTags', '-tokenizerFactory', 'edu.stanford.nlp.process.WhitespaceTokenizer', '-tokenizerOptions', '"tokenizeNLs=false"', '-encoding', 'utf8']
Invoked on Tue Jan 14 13:52:00 IST 2020 with arguments: -loadClassifier /home/test/stanford-ner-2018-10-16/classifiers/example.serialized.ncc.ncc.ser.gz -textFile /tmp/tmph8k3mnol -outputFormat slashTags -tokenizerFactory edu.stanford.nlp.process.WhitespaceTokenizer -tokenizerOptions "tokenizeNLs=false" -encoding utf8
tokenizerOptions="tokenizeNLs=false"
loadClassifier=/home/test/stanford-ner-2018-10-16/classifiers/example.serialized.ncc.ncc.ser.gz
encoding=utf8
outputFormat=slashTags
textFile=/tmp/tmph8k3mnol
tokenizerFactory=edu.stanford.nlp.process.WhitespaceTokenizer
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassCastException: class java.util.Properties cannot be cast to class [Ledu.stanford.nlp.util.Index; (java.util.Properties is in module java.base of loader 'bootstrap'; [Ledu.stanford.nlp.util.Index; is in unnamed module of loader 'app')
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifierNoExceptions(AbstractSequenceClassifier.java:1520)
	at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:2993)
Caused by: java.lang.ClassCastException: class java.util.Properties cannot be cast to class [Ledu.stanford.nlp.util.Index; (java.util.Properties is in module java.base of loader 'bootstrap'; [Ledu.stanford.nlp.util.Index; is in unnamed module of loader 'app')
	at edu.stanford.nlp.ie.crf.CRFClassifier.loadClassifier(CRFClassifier.java:2600)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1473)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1505)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifierNoExceptions(AbstractSequenceClassifier.java:1516)
	... 1 more

Process finished with exit code 1

**Comment by BVSREDDY82** [comment]
Please provide working example on latest JDK with clear fix for the issue. Tried all earlier suggestions from other thread none of them are worked

**Comment by AngledLuffa** [comment]
We don't interact with nltk at all.  Hopefully they can help provide answers
